import { Injectable } from '@angular/core';
import * as XLSX from 'xlsx';

export interface OverallPerformanceExcelSection {
  title: string;
  departmentName?: string;
  reportTitle?: string;
  reportKind?: 'release' | 'task' | 'issue' | 'ticket';
  sheetName?: string;
  summary?: Array<[string, any]>;
  headers: string[];
  rows: any[][];
}

export interface TableWorkbookExcelSection {
  title: string;
  departmentName?: string;
  reportTitle?: string;
  sheetName?: string;
  summary?: Array<[string, any]>;
  headers: string[];
  rows: any[][];
}

export interface TableWorkbookExcelOptions {
  filename?: string;
  workbookTitle?: string;
  author?: string;
  fromDate?: string;
  toDate?: string;
  departmentName?: string;
}

interface OverallPerformanceWorksheetStyleConfig {
  headers: string[];
  headerRow: number;
  dataStartRow: number;
  freezeYSplit: number;
  freezeTopLeftCell: string;
  rowCellStyles: Array<Record<number, number>>;
}

interface ReleaseOverviewExportSection {
  departmentName: string;
  managerName?: string;
  releases: any[];
}

type ReleasePerformanceState = 'none' | 'excellent' | 'very-good' | 'good' | 'poor';

@Injectable({
  providedIn: 'root'
})
export class ExcelService {
  generateOverallPerformanceExcel(
    filters: any,
    sections: OverallPerformanceExcelSection[]
  ): void {
    if (typeof XLSX === 'undefined') {
      throw new Error('Excel export library is not available.');
    }

    if (filters?.separateSheets) {
      this.generateOverallPerformanceDepartmentWorkbook(filters, sections);
      return;
    }

    const generatedBy = filters?.generatedBy || 'System User';
    const fromDate = filters?.fromDate || '-';
    const toDate = filters?.toDate || '-';
    const selectedCompany = filters?.selectedCompany || 'All Companies';
    const exportedAt = new Date().toLocaleString();
    const maxColumns = Math.max(
      10,
      ...sections.map(section => Math.max(section.headers.length, ...section.rows.map(row => row.length)))
    );
    const lastColumn = XLSX.utils.encode_col(maxColumns - 1);
    const merges: XLSX.Range[] = [];
    const rows: any[][] = [];
    const rowKinds: string[] = [];
    const rowCellStyles: Array<Record<number, number>> = [];
    const padRow = (row: any[]) => [
      ...row,
      ...Array(Math.max(maxColumns - row.length, 0)).fill('')
    ];
    const pushRow = (row: any[], kind: string, cellStyles: Record<number, number> = {}): void => {
      rows.push(padRow(row));
      rowKinds.push(kind);
      rowCellStyles.push(cellStyles);
    };
    const pushMergedRow = (row: any[], kind: string): void => {
      rows.push(padRow(row));
      rowKinds.push(kind);
      rowCellStyles.push({});
      merges.push(XLSX.utils.decode_range(`A${rows.length}:${lastColumn}${rows.length}`));
    };

    pushMergedRow(['OVERALL PERFORMANCE REPORT'], 'title');
    pushRow(['GENERATED BY', generatedBy, '', 'DATE RANGE', `${fromDate} to ${toDate}`, '', 'EXPORTED AT', exportedAt], 'meta');
    pushRow(['COMPANY FILTER', selectedCompany, '', 'TOTAL SECTIONS', sections.length], 'meta');
    pushRow([], 'spacer');

    sections.forEach(section => {
      pushMergedRow([`${section.title} (${section.rows.length})`], 'section');

      if (section.summary?.length) {
        for (let index = 0; index < section.summary.length; index += 3) {
          const summaryRow = section.summary
            .slice(index, index + 3)
            .flatMap(([label, value]) => [label, value, '']);
          pushRow(summaryRow, 'summary');
        }
      }

      pushRow(section.headers, 'header');
      if (section.rows.length) {
        section.rows.forEach(row => {
          const cellStyles = section.headers.reduce((styles, header, columnIndex) => {
            const styleId = this.getOverallPerformanceCellStyleId(header, row[columnIndex]);
            if (styleId !== null) {
              styles[columnIndex] = styleId;
            }
            return styles;
          }, {} as Record<number, number>);
          pushRow(row.map(value => this.normalizeOverallPerformanceExportValue(value)), 'data', cellStyles);
        });
      } else {
        pushRow(['No data available'], 'empty');
      }

      pushRow([], 'spacer');
    });

    const worksheet = XLSX.utils.aoa_to_sheet(rows);
    worksheet['!merges'] = merges;
    worksheet['!cols'] = Array.from({ length: maxColumns }, (_value, index) => ({
      wch: index === 0 ? 8 : index <= 2 ? 24 : index <= 5 ? 18 : 20
    }));
    worksheet['!rows'] = rows.map((row, index) => ({
      hpt: index === 0 ? 30 : row.some(value => `${value ?? ''}`.length > 42) ? 34 : 22
    }));
    worksheet['!margins'] = {
      left: 0.25, right: 0.25, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2
    };

    const workbook = XLSX.utils.book_new();
    workbook.Props = {
      Title: 'Overall Performance Report',
      Subject: `${selectedCompany} performance details`,
      Author: String(generatedBy),
      Company: 'RIDSYS'
    };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Overall Performance');

    const baseFile = XLSX.write(workbook, {
      bookType: 'xlsx',
      type: 'array',
      cellStyles: true
    });
    const file = this.applyProfessionalOverallPerformanceStyles(baseFile, rowKinds, rowCellStyles);
    const filename = `OVERALL_PERFORMANCE_${fromDate}_to_${toDate}.xlsx`;
    this.downloadWorkbook(file, filename);
  }

  private generateOverallPerformanceDepartmentWorkbook(
    filters: any,
    sections: OverallPerformanceExcelSection[]
  ): void {
    const generatedBy = filters?.generatedBy || 'System User';
    const fromDate = filters?.fromDate || '-';
    const toDate = filters?.toDate || '-';
    const reportPeriod = this.formatOverallPerformanceDateRange(fromDate, toDate);
    const selectedDepartments = filters?.selectedCompany || 'All Department';
    const totalDepartments = filters?.totalDepartments ?? this.countOverallPerformanceDepartments(sections);
    const exportedAt = new Date().toLocaleString();
    const workbook = XLSX.utils.book_new();
    const workbookStyleConfigs: OverallPerformanceWorksheetStyleConfig[] = [];
    const visibleSections = sections;
    const summaryHeaders = ['REPORT TYPE', 'TOTAL RECORDS'];
    const summaryTableRows = [
      ['Total Selected Departments', totalDepartments],
      ['Total Releases', this.countOverallPerformanceRowsByKind(visibleSections, 'release')],
      ['Total Tasks', this.countOverallPerformanceRowsByKind(visibleSections, 'task')],
      ['Total Issues', this.countOverallPerformanceRowsByKind(visibleSections, 'issue')],
      ['Total Tickets', this.countOverallPerformanceRowsByKind(visibleSections, 'ticket')]
    ];
    const summaryColumnCount = 6;
    const padSummaryRow = (row: any[]) => [
      ...row,
      ...Array(Math.max(summaryColumnCount - row.length, 0)).fill('')
    ];
    const summaryRows = [
      padSummaryRow(['OVERALL PERFORMANCE REPORT']),
      padSummaryRow(['DSR PRO | DEPARTMENT PERFORMANCE REPORT']),
      padSummaryRow([]),
      padSummaryRow(['GENERATED BY', generatedBy, '', '', 'REPORTING PERIOD', reportPeriod]),
      padSummaryRow(['DEPARTMENTS', selectedDepartments, '', '', 'TOTAL DEPARTMENTS', totalDepartments]),
      padSummaryRow(['TOTAL RELEASES', this.countOverallPerformanceRowsByKind(visibleSections, 'release'), '', '', 'TOTAL TASKS', this.countOverallPerformanceRowsByKind(visibleSections, 'task')]),
      padSummaryRow(['TOTAL ISSUES', this.countOverallPerformanceRowsByKind(visibleSections, 'issue'), '', '', 'TOTAL TICKETS', this.countOverallPerformanceRowsByKind(visibleSections, 'ticket')]),
      padSummaryRow([]),
      padSummaryRow(summaryHeaders),
      ...summaryTableRows.map(row => padSummaryRow(row))
    ];
    const summaryWorksheet = XLSX.utils.aoa_to_sheet(summaryRows);

    summaryWorksheet['!merges'] = [
      XLSX.utils.decode_range('A1:F1'),
      XLSX.utils.decode_range('A2:F2'),
      XLSX.utils.decode_range('B4:D4'),
      XLSX.utils.decode_range('F4:F4'),
      XLSX.utils.decode_range('B5:D5'),
      XLSX.utils.decode_range('F5:F5'),
      XLSX.utils.decode_range('B6:D6'),
      XLSX.utils.decode_range('F6:F6'),
      XLSX.utils.decode_range('B7:D7'),
      XLSX.utils.decode_range('F7:F7')
    ];
    summaryWorksheet['!cols'] = [
      { wch: 20 }, { wch: 28 }, { wch: 18 }, { wch: 18 }, { wch: 28 }, { wch: 18 }
    ];
    summaryWorksheet['!rows'] = this.getOverallPerformanceRowHeights(summaryRows, 10);
    summaryWorksheet['!autofilter'] = {
      ref: `A9:B${Math.max(summaryTableRows.length + 9, 9)}`
    };
    summaryWorksheet['!margins'] = this.getOverallPerformanceWorksheetMargins();
    XLSX.utils.book_append_sheet(workbook, summaryWorksheet, 'Overall Summary');
    workbookStyleConfigs.push({
      headers: summaryHeaders,
      headerRow: 9,
      dataStartRow: 10,
      freezeYSplit: 9,
      freezeTopLeftCell: 'A10',
      rowCellStyles: []
    });

    const usedSheetNames = new Set<string>(['overall summary']);
    visibleSections.forEach(section => {
      const reportSheet = this.createOverallPerformanceReportWorksheet(
        section,
        generatedBy,
        reportPeriod,
        exportedAt
      );

      XLSX.utils.book_append_sheet(
        workbook,
        reportSheet.worksheet,
        this.getUniqueWorksheetName(section.sheetName || section.title, usedSheetNames)
      );
      workbookStyleConfigs.push(reportSheet.styleConfig);
    });

    workbook.Props = {
      Title: 'Overall Performance Report',
      Subject: `${selectedDepartments} department-wise performance details`,
      Author: String(generatedBy),
      Company: 'RIDSYS'
    };

    const baseFile = XLSX.write(workbook, {
      bookType: 'xlsx',
      type: 'array',
      cellStyles: true
    });
    const file = this.applyOverallPerformanceWorkbookStyles(baseFile, workbookStyleConfigs);
    const filename = filters?.filename || `OVERALL_PERFORMANCE_REPORT_${fromDate}_to_${toDate}.xlsx`;
    this.downloadWorkbook(file, filename);
  }

  generateOverallPerformanceSectionExcel(
    filters: any,
    section: OverallPerformanceExcelSection
  ): void {
    if (typeof XLSX === 'undefined') {
      throw new Error('Excel export library is not available.');
    }

    const generatedBy = filters?.generatedBy || 'System User';
    const fromDate = filters?.fromDate || '-';
    const toDate = filters?.toDate || '-';
    const reportPeriod = this.formatOverallPerformanceDateRange(fromDate, toDate);
    const exportedAt = new Date().toLocaleString();
    const workbook = XLSX.utils.book_new();
    const reportSheet = this.createOverallPerformanceReportWorksheet(
      section,
      generatedBy,
      reportPeriod,
      exportedAt
    );

    workbook.Props = {
      Title: section.reportTitle || section.title || 'Performance Report',
      Subject: `${section.departmentName || 'Department'} ${section.reportTitle || 'report'}`,
      Author: String(generatedBy),
      Company: 'RIDSYS'
    };
    XLSX.utils.book_append_sheet(workbook, reportSheet.worksheet, this.sanitizeWorksheetName(section.sheetName || section.title));

    const baseFile = XLSX.write(workbook, {
      bookType: 'xlsx',
      type: 'array',
      cellStyles: true
    });
    const file = this.applyOverallPerformanceWorkbookStyles(baseFile, [reportSheet.styleConfig]);
    const fallbackReportName = this.sanitizeExportFileToken(section.reportTitle || section.title || 'REPORT');
    const filename = filters?.filename || `${fallbackReportName}_${fromDate}_to_${toDate}.xlsx`;
    this.downloadWorkbook(file, filename);
  }

  generateTableWorkbookExcel(
    options: TableWorkbookExcelOptions,
    sections: TableWorkbookExcelSection[]
  ): void {
    if (typeof XLSX === 'undefined') {
      throw new Error('Excel export library is not available.');
    }

    if (!sections.length) {
      throw new Error('No table sections available for Excel export.');
    }

    const workbook = XLSX.utils.book_new();
    const usedSheetNames = new Set<string>();
    const generatedBy = options.author || 'System User';
    const fromDate = options.fromDate || '-';
    const toDate = options.toDate || '-';
    const reportPeriod = this.formatOverallPerformanceDateRange(fromDate, toDate);
    const exportedAt = new Date().toLocaleString();
    const workbookStyleConfigs: OverallPerformanceWorksheetStyleConfig[] = [];

    workbook.Props = {
      Title: options.workbookTitle || 'Table Export',
      Subject: options.departmentName || options.workbookTitle || 'Table Export',
      Author: String(generatedBy),
      Company: 'RIDSYS'
    };

    sections.forEach(section => {
      const reportSheet = this.createOverallPerformanceReportWorksheet(
        {
          title: section.title,
          departmentName: section.departmentName || options.departmentName || 'Performance',
          reportTitle: section.reportTitle || section.title,
          sheetName: section.sheetName,
          summary: section.summary,
          headers: section.headers,
          rows: section.rows
        },
        generatedBy,
        reportPeriod,
        exportedAt
      );

      XLSX.utils.book_append_sheet(
        workbook,
        reportSheet.worksheet,
        this.getUniqueWorksheetName(section.sheetName || section.title, usedSheetNames)
      );
      workbookStyleConfigs.push(reportSheet.styleConfig);
    });

    const baseFile = XLSX.write(workbook, {
      bookType: 'xlsx',
      type: 'array',
      cellStyles: true
    });
    const file = this.applyOverallPerformanceWorkbookStyles(baseFile, workbookStyleConfigs);
    const filename = options.filename || `${this.sanitizeExportFileToken(options.workbookTitle || 'TABLE_EXPORT')}.xlsx`;
    this.downloadWorkbook(file, filename);
  }

  private createOverallPerformanceReportWorksheet(
    section: OverallPerformanceExcelSection,
    generatedBy: string,
    reportPeriod: string,
    exportedAt: string
  ): { worksheet: XLSX.WorkSheet; styleConfig: OverallPerformanceWorksheetStyleConfig } {
    const reportColumnCount = Math.max(
      section.headers.length,
      ...section.rows.map(row => row.length),
      6
    );
    const reportEndColumn = XLSX.utils.encode_col(reportColumnCount - 1);
    const padReportRow = (row: any[]) => [
      ...row,
      ...Array(Math.max(reportColumnCount - row.length, 0)).fill('')
    ];
    const normalizedRows = section.rows.map(row =>
      padReportRow(row.map(value => this.normalizeOverallPerformanceExportValue(value)))
    );
    const emptyRows = normalizedRows.length ? [] : [padReportRow(['No data available'])];
    const summaryText = this.formatOverallPerformanceSummary(section.summary);
    const rows = [
      padReportRow([`${section.reportTitle || section.title || 'PERFORMANCE REPORT'}`.toUpperCase()]),
      padReportRow([`DSR PRO | ${`${section.departmentName || 'Department'}`.toUpperCase()} DEPARTMENT`]),
      padReportRow([]),
      padReportRow(['DEPARTMENT', `${section.departmentName || '-'} Department`, '', '', 'REPORT', section.reportTitle || '-']),
      padReportRow(['REPORT PERIOD', reportPeriod, '', '', 'GENERATED BY', generatedBy]),
      padReportRow(['TOTAL RECORDS', section.rows.length, '', '', 'EXPORTED AT', exportedAt]),
      padReportRow(['SUMMARY', summaryText || '-', '', '', 'REPORT NAME', section.reportTitle || '-']),
      padReportRow([]),
      padReportRow(section.headers),
      ...normalizedRows,
      ...emptyRows
    ];
    const worksheet = XLSX.utils.aoa_to_sheet(rows);

    worksheet['!merges'] = [
      XLSX.utils.decode_range(`A1:${reportEndColumn}1`),
      XLSX.utils.decode_range(`A2:${reportEndColumn}2`),
      XLSX.utils.decode_range('B4:D4'),
      XLSX.utils.decode_range(`F4:${reportEndColumn}4`),
      XLSX.utils.decode_range('B5:D5'),
      XLSX.utils.decode_range(`F5:${reportEndColumn}5`),
      XLSX.utils.decode_range('B6:D6'),
      XLSX.utils.decode_range(`F6:${reportEndColumn}6`),
      XLSX.utils.decode_range('B7:D7'),
      XLSX.utils.decode_range(`F7:${reportEndColumn}7`)
    ];
    worksheet['!cols'] = Array.from({ length: reportColumnCount }, (_value, index) => ({
      wch: this.getOverallPerformanceColumnWidth(section.headers[index], index)
    }));
    worksheet['!rows'] = this.getOverallPerformanceRowHeights(rows, 10);
    worksheet['!autofilter'] = {
      ref: `A9:${reportEndColumn}${Math.max(section.rows.length + 9, 10)}`
    };
    worksheet['!margins'] = this.getOverallPerformanceWorksheetMargins();

    return {
      worksheet,
      styleConfig: {
        headers: section.headers,
        headerRow: 9,
        dataStartRow: 10,
        freezeYSplit: 9,
        freezeTopLeftCell: 'A10',
        rowCellStyles: section.rows.map(row => this.getOverallPerformanceRowCellStyles(section.headers, row))
      }
    };
  }

  private getOverallPerformanceRowCellStyles(headers: string[], row: any[]): Record<number, number> {
    return headers.reduce((styles, header, columnIndex) => {
      const styleId = this.getOverallPerformanceCellStyleId(header, row[columnIndex]);
      if (styleId !== null) {
        styles[columnIndex] = styleId;
      }
      return styles;
    }, {} as Record<number, number>);
  }

  private getOverallPerformanceColumnWidth(header: string | undefined, index: number): number {
    const key = `${header ?? ''}`.toLowerCase().replace(/[^a-z0-9]/g, '');

    if (index === 0 || key === 'sno') return 8;
    if (key.includes('title') || key.includes('task') || key.includes('ticket') || key.includes('issue') || key.includes('bug')) return 32;
    if (key.includes('remark') || key.includes('comment') || key.includes('description')) return 36;
    if (key.includes('department') || key.includes('assigned') || key.includes('workedby') || key.includes('releasedby') || key.includes('testedby')) return 24;
    if (key.includes('project') || key.includes('client') || key.includes('product')) return 22;
    if (key.includes('date')) return 16;
    if (key.includes('status') || key.includes('type') || key.includes('priority') || key.includes('category')) return 18;
    if (key.includes('version') || key.includes('code') || key.includes('hours') || key.includes('performance') || key.includes('overdue')) return 18;

    return 20;
  }

  private getOverallPerformanceRowHeights(rows: any[][], dataStartRow: number): Array<{ hpt: number }> {
    return rows.map((row, index) => {
      const rowNumber = index + 1;

      if (rowNumber === 1) return { hpt: 28 };
      if (rowNumber === 2) return { hpt: 19 };
      if (rowNumber === 3 || rowNumber === 8) return { hpt: 8 };
      if (rowNumber === 9) return { hpt: 29 };
      if (rowNumber < dataStartRow) return { hpt: 23 };

      const visibleLines = Math.max(
        1,
        ...row.map(value => Math.ceil(String(value ?? '').length / 32))
      );
      return { hpt: Math.min(66, Math.max(24, visibleLines * 18)) };
    });
  }

  private getOverallPerformanceWorksheetMargins(): XLSX.MarginInfo {
    return {
      left: 0.25,
      right: 0.25,
      top: 0.5,
      bottom: 0.5,
      header: 0.2,
      footer: 0.2
    };
  }

  private formatOverallPerformanceSummary(summary: Array<[string, any]> | undefined): string {
    return (summary || [])
      .slice(0, 6)
      .map(([label, value]) => `${label}: ${this.normalizeOverallPerformanceExportValue(value)}`)
      .join('  |  ');
  }

  private sanitizeExportFileToken(value: string): string {
    return `${value || 'REPORT'}`
      .replace(/\bdepartments?\b/gi, '')
      .replace(/[^a-z0-9]+/gi, '_')
      .replace(/^_+|_+$/g, '')
      .toUpperCase() || 'REPORT';
  }

  private formatOverallPerformanceDateRange(fromDate: any, toDate: any): string {
    return `${this.formatOverallPerformanceReportDate(fromDate)} to ${this.formatOverallPerformanceReportDate(toDate)}`;
  }

  private formatOverallPerformanceReportDate(value: any): string {
    const rawValue = `${value ?? ''}`.trim();
    if (!rawValue || rawValue === '-') {
      return '-';
    }

    const ymdParts = /^(\d{4})-(\d{2})-(\d{2})$/.exec(rawValue);
    const date = ymdParts
      ? new Date(Number(ymdParts[1]), Number(ymdParts[2]) - 1, Number(ymdParts[3]))
      : new Date(rawValue);

    if (Number.isNaN(date.getTime())) {
      return rawValue;
    }

    return date.toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric'
    }).replace(/ /g, '-');
  }

  private applyOverallPerformanceWorkbookStyles(
    file: ArrayBuffer,
    sheetStyleConfigs: OverallPerformanceWorksheetStyleConfig[]
  ): any {
    const archive = XLSX.CFB.read(new Uint8Array(file), { type: 'buffer' });
    const stylesFile = XLSX.CFB.find(archive, 'styles.xml');

    if (!stylesFile) {
      throw new Error('Unable to apply Excel report styling.');
    }

    stylesFile.content = new TextEncoder().encode(this.releaseStylesXml());

    sheetStyleConfigs.forEach((config, index) => {
      const sheetFile = XLSX.CFB.find(archive, `sheet${index + 1}.xml`);

      if (!sheetFile) {
        throw new Error('Unable to apply Excel worksheet styling.');
      }

      let sheetXml = new TextDecoder().decode(sheetFile.content);
      const sheetViewsXml = `<sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="${config.freezeYSplit}" topLeftCell="${config.freezeTopLeftCell}" activePane="bottomLeft" state="frozen"/><selection pane="bottomLeft" activeCell="${config.freezeTopLeftCell}" sqref="${config.freezeTopLeftCell}"/></sheetView></sheetViews>`;
      sheetXml = this.replaceWorksheetSheetViews(sheetXml, sheetViewsXml);
      sheetXml = sheetXml.replace(/<c r="([A-Z]+)(\d+)"([^>]*)>/g, (match, column, rowText, attributes) => {
        const row = Number(rowText);
        const columnIndex = this.excelColumnIndex(column);
        const styleId = this.getOverallPerformanceWorksheetStyleId(config, row, columnIndex);
        const cleanAttributes = String(attributes).replace(/\s+s="\d+"/, '');
        return `<c r="${column}${row}" s="${styleId}"${cleanAttributes}>`;
      });
      sheetFile.content = new TextEncoder().encode(sheetXml);
    });

    return XLSX.CFB.write(archive, {
      fileType: 'zip',
      type: 'array',
      compression: true
    });
  }

  private replaceWorksheetSheetViews(sheetXml: string, sheetViewsXml: string): string {
    if (/<sheetViews>[\s\S]*?<\/sheetViews>/.test(sheetXml)) {
      return sheetXml.replace(/<sheetViews>[\s\S]*?<\/sheetViews>/, sheetViewsXml);
    }

    return sheetXml.replace(/(<worksheet[^>]*>)/, `$1${sheetViewsXml}`);
  }

  private getOverallPerformanceWorksheetStyleId(
    config: OverallPerformanceWorksheetStyleConfig,
    row: number,
    columnIndex: number
  ): number {
    if (row === 1) return 1;
    if (row === 2) return 2;
    if (row >= 4 && row <= 7) return columnIndex === 0 || columnIndex === 4 ? 3 : 4;
    if (row === config.headerRow) return 5;

    if (row >= config.dataStartRow) {
      const dataIndex = row - config.dataStartRow;
      const cellStyleOverride = config.rowCellStyles[dataIndex]?.[columnIndex];
      if (cellStyleOverride !== undefined) {
        return cellStyleOverride;
      }

      const alternate = dataIndex % 2 === 1;
      return this.isOverallPerformanceCenteredColumn(config.headers[columnIndex], columnIndex)
        ? (alternate ? 9 : 7)
        : (alternate ? 8 : 6);
    }

    return 0;
  }

  private isOverallPerformanceCenteredColumn(header: string | undefined, index: number): boolean {
    const key = `${header ?? ''}`.toLowerCase().replace(/[^a-z0-9]/g, '');

    return index === 0
      || key.includes('date')
      || key.includes('status')
      || key.includes('type')
      || key.includes('priority')
      || key.includes('category')
      || key.includes('code')
      || key.includes('version')
      || key.includes('hours')
      || key.includes('performance')
      || key.includes('overdue');
  }

  private countOverallPerformanceDepartments(sections: OverallPerformanceExcelSection[]): number {
    const departments = new Set(
      sections
        .map(section => `${section.departmentName || ''}`.trim())
        .filter(Boolean)
    );

    return departments.size;
  }

  private countOverallPerformanceRowsByKind(
    sections: OverallPerformanceExcelSection[],
    reportKind: OverallPerformanceExcelSection['reportKind']
  ): number {
    return sections
      .filter(section => section.reportKind === reportKind)
      .reduce((total, section) => total + section.rows.length, 0);
  }

  private getUniqueWorksheetName(rawName: string, usedSheetNames: Set<string>): string {
    const baseName = this.sanitizeWorksheetName(rawName) || 'Report';
    let sheetName = baseName;
    let counter = 2;

    while (usedSheetNames.has(sheetName.toLowerCase())) {
      const suffix = ` ${counter}`;
      sheetName = `${baseName.slice(0, 31 - suffix.length)}${suffix}`;
      counter++;
    }

    usedSheetNames.add(sheetName.toLowerCase());
    return sheetName;
  }

  private sanitizeWorksheetName(value: string): string {
    return `${value || 'Report'}`
      .replace(/[:\\/?*[\]]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim()
      .slice(0, 31);
  }

  private applyProfessionalOverallPerformanceStyles(
    file: ArrayBuffer,
    rowKinds: string[],
    rowCellStyles: Array<Record<number, number>>
  ): any {
    const archive = XLSX.CFB.read(new Uint8Array(file), { type: 'buffer' });
    const stylesFile = XLSX.CFB.find(archive, 'styles.xml');
    const sheetFile = XLSX.CFB.find(archive, 'sheet1.xml');

    if (!stylesFile || !sheetFile) {
      throw new Error('Unable to apply Excel report styling.');
    }

    stylesFile.content = new TextEncoder().encode(this.releaseStylesXml());

    let sheetXml = new TextDecoder().decode(sheetFile.content);
    sheetXml = sheetXml.replace(
      /<sheetViews>[\s\S]*?<\/sheetViews>/,
      '<sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="4" topLeftCell="A5" activePane="bottomLeft" state="frozen"/><selection pane="bottomLeft" activeCell="A5" sqref="A5"/></sheetView></sheetViews>'
    );
    sheetXml = sheetXml.replace(/<c r="([A-Z]+)(\d+)"([^>]*)>/g, (match, column, rowText, attributes) => {
      const row = Number(rowText);
      const kind = rowKinds[row - 1] || 'data';
      const columnIndex = this.excelColumnIndex(column);
      let styleId = 0;

      if (kind === 'title' || kind === 'section') {
        styleId = 1;
      } else if (kind === 'meta' || kind === 'summary') {
        styleId = columnIndex % 3 === 0 ? 3 : 4;
      } else if (kind === 'header') {
        styleId = 5;
      } else if (kind === 'data') {
        const alternate = row % 2 === 0;
        styleId = columnIndex === 0 ? (alternate ? 9 : 7) : (alternate ? 8 : 6);
      } else if (kind === 'empty') {
        styleId = 17;
      }

      const cellStyleOverride = rowCellStyles[row - 1]?.[columnIndex];
      if (cellStyleOverride !== undefined) {
        styleId = cellStyleOverride;
      }

      const cleanAttributes = String(attributes).replace(/\s+s="\d+"/, '');
      return `<c r="${column}${row}" s="${styleId}"${cleanAttributes}>`;
    });
    sheetFile.content = new TextEncoder().encode(sheetXml);

    return XLSX.CFB.write(archive, {
      fileType: 'zip',
      type: 'array',
      compression: true
    });
  }

  private excelColumnIndex(column: string): number {
    return column.split('').reduce((total, char) => total * 26 + char.charCodeAt(0) - 64, 0) - 1;
  }

  private normalizeOverallPerformanceExportValue(value: any): any {
    if (value === null || value === undefined || `${value}`.trim() === '') {
      return '-';
    }

    return value;
  }

  private getOverallPerformanceCellStyleId(column: string, value: any): number | null {
    const columnKey = `${column ?? ''}`.toLowerCase().replace(/[^a-z0-9]/g, '');
    const valueKey = `${value ?? ''}`.trim().toLowerCase().replace(/[^a-z0-9]/g, '');
    if (!valueKey || valueKey === 'na') return null;

    if (columnKey === 'releasetype') {
      if (valueKey === 'internal') return 21;
      if (valueKey === 'external') return 23;
      return 24;
    }

    if (columnKey === 'releaseperformance' || columnKey === 'overdue' || columnKey === 'overduestatus') {
      if (['excellent'].includes(valueKey)) return 19;
      if (['good'].includes(valueKey)) return 21;
      if (['poor', 'overdue'].includes(valueKey)) return 20;
      if (valueKey.startsWith('duein') || ['duetoday', 'duetomorrow', 'pending'].includes(valueKey)) return 22;
      return 24;
    }

    if (columnKey === 'priority') {
      if (['critical', 'urgent', 'high'].includes(valueKey)) return 20;
      if (['medium', 'normal'].includes(valueKey)) return 22;
      if (['low'].includes(valueKey)) return 21;
      return 24;
    }

    if (columnKey === 'category') {
      if (['service', 'support'].includes(valueKey)) return 21;
      return 24;
    }

    if (columnKey === 'status') {
      if (['pass', 'passed', 'completed', 'approved', 'closed', 'production'].includes(valueKey)) return 19;
      if (['failed', 'rejected', 'cancelled', 'canceled'].includes(valueKey)) return 20;
      if (['inprogress', 'testing', 'intesting', 'tobetested', 'service'].includes(valueKey)) return 21;
      if (['open', 'pending', 'onhold', 'delayed', 'upcoming', 'upcomingrelease', 'reopen', 'reopened'].includes(valueKey)) return 22;
      return 24;
    }

    return null;
  }

  generateReleaseOverviewExcel(
    filters: any,
    fromDate: string,
    toDate: string,
    rawData: any[]
  ): void {
    if (typeof XLSX === 'undefined') {
      throw new Error('Excel export library is not available.');
    }

    const departmentSections = this.getReleaseOverviewDepartmentSections(filters, rawData);
    if (departmentSections.length) {
      this.generateDepartmentWiseReleaseOverviewExcel(filters, fromDate, toDate, departmentSections);
      return;
    }

    const data = this.getProjectOrderedReleaseData(rawData);
    const generatedBy = filters?.generatedBy || 'System User';
    const filteredEmployee = filters?.filteredEmployee || filters?.employee || 'All Employees';
    const project = filters?.filteredProject || 'All Projects';
    const releaseType = filters?.releaseType || 'All';
    const department = filters?.department || 'All Departments';
    const managerName = filters?.managerName || 'All Managers';
    const normalizedDepartment = String(department).trim().toLowerCase();
    const departmentFilePart = normalizedDepartment && !['all', 'all departments'].includes(normalizedDepartment)
      ? `_${this.sanitizeExportFileToken(department)}`
      : '';
    const internalReleaseCount = data.filter(
      (release: any) => String(release?.release_type || '').trim().toLowerCase() === 'internal'
    ).length;
    const externalReleaseCount = data.filter(
      (release: any) => String(release?.release_type || '').trim().toLowerCase() === 'external'
    ).length;
    const headers = [
      'S/NO', 'PROJECT', 'TITLE',  'VERSION','MANAGER / TL','WORKED BY / RELEASED BY', 'RELEASE PERFORMANCE',
      'PLANNED DATE', 'RELEASE DATE', 'TESTED BY', 'QC TESTING START DATE','QC TESTING END DATE',
      'QC RELEASED DATE', 'CLIENT', 'STATUS', 'RELEASE TYPE', 'OVERDUE', 'OVERDUE STATUS', 'REMARKS'
    ];
    const reportColumnCount = headers.length;
    const reportEndColumn = XLSX.utils.encode_col(reportColumnCount - 1);
    const padReportRow = (row: any[]) => [
      ...row,
      ...Array(Math.max(reportColumnCount - row.length, 0)).fill('')
    ];

    // Keep the Excel columns in the same order as the Release Overview PDF.
    const reportRows = data.map((release: any, index: number) => [
      index + 1,
      release.project_name || release.project_title || '-',
      release.title || '-',
      release.version || '-',
      release.manager_name || '-',
      release.assignee_from_name || '-',
      this.getReleasePerformance(release),
      release.planned_date || '-',
      release.released_date || '-',
      this.getReleaseTesterName(release),
      this.getReleaseQcTestingStartDate(release),
      release.qc_testing_end_date || '-',
      release.closed_date ? release.closed_date.split('T')[0] : '-',
      release.company_name || '-',
      release.status || '-',
      release.release_type || '-',
      this.getReleaseOverdueDate(release),
      this.getReleaseOverdueStatus(release),
      release.remarks || '-'
    ]);

    const worksheet = XLSX.utils.aoa_to_sheet([
      padReportRow(['RELEASE OVERVIEW REPORT']),
      padReportRow(['DSR PRO  |  RELEASE ACTIVITY REPORT']),
      padReportRow([]),
      padReportRow(['GENERATED BY', generatedBy, '', '', 'REPORTING PERIOD', `${fromDate} to ${toDate}`]),
      padReportRow(['PROJECT', project, '', '', 'DEPARTMENT', department]),
      padReportRow(['RELEASE TYPE', releaseType, '', '', 'TOTAL RELEASES', data.length]),
      padReportRow(['INTERNAL RELEASES', internalReleaseCount, '', '', 'EXTERNAL RELEASES', externalReleaseCount]),
      padReportRow(['EMPLOYEE', filteredEmployee, '', '', 'MANAGER', managerName]),
      headers,
      ...reportRows
    ]);

    worksheet['!merges'] = [
      XLSX.utils.decode_range(`A1:${reportEndColumn}1`),
      XLSX.utils.decode_range(`A2:${reportEndColumn}2`),
      XLSX.utils.decode_range('B4:D4'),
      XLSX.utils.decode_range(`F4:${reportEndColumn}4`),
      XLSX.utils.decode_range('B5:D5'),
      XLSX.utils.decode_range(`F5:${reportEndColumn}5`),
      XLSX.utils.decode_range('B6:D6'),
      XLSX.utils.decode_range(`F6:${reportEndColumn}6`),
      XLSX.utils.decode_range('B7:D7'),
      XLSX.utils.decode_range(`F7:${reportEndColumn}7`),
      XLSX.utils.decode_range('B8:D8'),
      XLSX.utils.decode_range(`F8:${reportEndColumn}8`),
    ];
    worksheet['!cols'] = [
      { wch: 8 }, { wch: 22 }, { wch: 30 }, { wch: 25 }, { wch: 30 }, { wch: 20 },
      { wch: 18 }, { wch: 15 }, { wch: 15 }, { wch: 18 }, { wch: 22 },
      { wch: 18 }, { wch: 18 }, { wch: 15 }, { wch: 15 }, { wch: 15 },
      { wch: 20 }, { wch: 25 }, { wch: 34 }
    ];
    const dataRowHeights = reportRows.map((row: any[]) => {
      const projectLines = Math.ceil(String(row[1] || '').length / 24);
      const titleLines = Math.ceil(String(row[2] || '').length / 36);
      const assigneeLines = Math.ceil(String(row[4] || '').length / 24);
      const testerLines = Math.ceil(String(row[8] || '').length / 24);
      const overdueStatusLines = Math.ceil(String(row[16] || '').length / 30);
      const remarksLines = Math.ceil(String(row[17] || '').length / 38);
      const visibleLines = Math.max(1, projectLines, titleLines, assigneeLines, testerLines, overdueStatusLines, remarksLines);
      return { hpt: Math.min(66, Math.max(24, visibleLines * 18)) };
    });
    worksheet['!rows'] = [
      { hpt: 28 }, { hpt: 19 }, { hpt: 8 },
      { hpt: 23 }, { hpt: 23 }, { hpt: 23 }, { hpt: 23 }, { hpt: 23 }, { hpt: 29 },
      ...dataRowHeights
    ];
    worksheet['!autofilter'] = { ref: `A9:${reportEndColumn}${Math.max(data.length + 9, 9)}` };
    worksheet['!margins'] = {
      left: 0.25, right: 0.25, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2
    };

    const workbook = XLSX.utils.book_new();
    workbook.Props = {
      Title: 'Release Overview Report',
      Subject: `${project} ${department} release activity`,
      Author: String(generatedBy),
      Company: 'RIDSYS'
    };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Release Overview');

    const statusStyles = data.map((release: any) => this.getStatusStyleId(release?.status));
    const releasePerformanceStyles = data.map((release: any) => this.getReleasePerformanceStyleId(release));
    const overdueStyles = data.map((release: any) => this.getReleaseOverdueStyleId(release));
    const overdueStatusStyles = data.map((release: any) => this.getReleaseOverdueStatusStyleId(release));
    const baseFile = XLSX.write(workbook, {
      bookType: 'xlsx',
      type: 'array',
      cellStyles: true
    });
    const styledFile = this.applyProfessionalReleaseStyles(baseFile, statusStyles, releasePerformanceStyles, overdueStyles, overdueStatusStyles);

    const filename = `RELEASE_REPORT${departmentFilePart}_${fromDate}_to_${toDate}.xlsx`;
    this.downloadWorkbook(styledFile, filename);
  }

  private getReleaseOverviewDepartmentSections(filters: any, rawData: any[]): ReleaseOverviewExportSection[] {
    if (!filters?.departmentWiseReleaseReport || !Array.isArray(filters?.departmentSections)) {
      return [];
    }

    const fallbackDepartmentName = filters?.department || 'All Departments';
    const fallbackManagerName = filters?.managerName || 'All Managers';
    const sections = filters.departmentSections
      .map((section: any): ReleaseOverviewExportSection => ({
        departmentName: `${section?.departmentName || section?.department || fallbackDepartmentName}`.trim(),
        managerName: `${section?.managerName || fallbackManagerName}`.trim(),
        releases: this.getProjectOrderedReleaseData(section?.releases || section?.data || [])
      }))
      .filter((section: ReleaseOverviewExportSection) => !!section.departmentName || section.releases.length > 0);

    if (sections.length) {
      return sections;
    }

    const data = this.getProjectOrderedReleaseData(rawData);
    return data.length
      ? [{
        departmentName: `${fallbackDepartmentName}`.trim(),
        managerName: `${fallbackManagerName}`.trim(),
        releases: data
      }]
      : [];
  }

  private generateDepartmentWiseReleaseOverviewExcel(
    filters: any,
    fromDate: string,
    toDate: string,
    sections: ReleaseOverviewExportSection[]
  ): void {
    const generatedBy = filters?.generatedBy || 'System User';
    const filteredEmployee = filters?.filteredEmployee || filters?.employee || 'All Employees';
    const project = filters?.filteredProject || 'All Projects';
    const releaseType = filters?.releaseType || 'All';
    const department = filters?.department || 'All Departments';
    const managerName = filters?.managerName || 'All Managers';
    const data = sections.flatMap(section => section.releases);
    const normalizedDepartment = String(department).trim().toLowerCase();
    const departmentFilePart = normalizedDepartment && !['all', 'all departments'].includes(normalizedDepartment)
      ? `_${this.sanitizeExportFileToken(department)}`
      : sections.length > 1
        ? '_DEPARTMENT_WISE'
        : '';
    const internalReleaseCount = data.filter(
      (release: any) => String(release?.release_type || '').trim().toLowerCase() === 'internal'
    ).length;
    const externalReleaseCount = data.filter(
      (release: any) => String(release?.release_type || '').trim().toLowerCase() === 'external'
    ).length;
    const headers = [
      'S/NO', 'PROJECT', 'TITLE', 'VERSION', 'MANAGER / TL', 'WORKED BY / RELEASED BY', 'RELEASE PERFORMANCE',
      'PLANNED DATE', 'RELEASE DATE', 'TESTED BY', 'QC TESTING START DATE', 'QC TESTING END DATE',
      'QC RELEASED DATE', 'CLIENT', 'STATUS', 'RELEASE TYPE', 'OVERDUE', 'OVERDUE STATUS', 'REMARKS'
    ];
    const reportColumnCount = headers.length;
    const reportEndColumn = XLSX.utils.encode_col(reportColumnCount - 1);
    const rows: any[][] = [];
    const rowKinds: string[] = [];
    const rowReleases: Array<any | null> = [];
    const merges: XLSX.Range[] = [];
    const padReportRow = (row: any[]) => [
      ...row,
      ...Array(Math.max(reportColumnCount - row.length, 0)).fill('')
    ];
    const pushRow = (row: any[], kind: string, release: any | null = null): void => {
      rows.push(padReportRow(row));
      rowKinds.push(kind);
      rowReleases.push(release);
    };
    const pushMergedRow = (row: any[], kind: string): void => {
      pushRow(row, kind);
      merges.push(XLSX.utils.decode_range(`A${rows.length}:${reportEndColumn}${rows.length}`));
    };
    const buildReportRow = (release: any, index: number): any[] => [
      index + 1,
      release.project_name || release.project_title || '-',
      release.title || '-',
      release.version || '-',
      release.manager_name || '-',
      release.assignee_from_name || '-',
      this.getReleasePerformance(release),
      release.planned_date || '-',
      release.released_date || '-',
      this.getReleaseTesterName(release),
      this.getReleaseQcTestingStartDate(release),
      release.qc_testing_end_date || '-',
      release.closed_date ? String(release.closed_date).split('T')[0] : '-',
      release.company_name || '-',
      release.status || '-',
      release.release_type || '-',
      this.getReleaseOverdueDate(release),
      this.getReleaseOverdueStatus(release),
      release.remarks || '-'
    ];

    pushMergedRow(['RELEASE OVERVIEW REPORT'], 'title');
    pushMergedRow(['DSR PRO  |  RELEASE ACTIVITY REPORT'], 'subtitle');
    pushRow([], 'spacer');
    pushRow(['GENERATED BY', generatedBy, '', '', 'REPORTING PERIOD', `${fromDate} to ${toDate}`], 'meta');
    pushRow(['PROJECT', project, '', '', 'DEPARTMENT', department], 'meta');
    pushRow(['RELEASE TYPE', releaseType, '', '', 'TOTAL RELEASES', data.length], 'meta');
    pushRow(['INTERNAL RELEASES', internalReleaseCount, '', '', 'EXTERNAL RELEASES', externalReleaseCount], 'meta');
    pushRow(['EMPLOYEE', filteredEmployee, '', '', 'MANAGER', managerName], 'meta');
    pushRow([], 'spacer');

    sections.forEach((section, sectionIndex) => {
      const releases = this.getProjectOrderedReleaseData(section.releases);

      if (sectionIndex > 0) {
        pushRow([], 'spacer');
      }

      pushMergedRow([`${section.departmentName.toUpperCase()} DEPARTMENT`], 'section');
      pushRow(['REPORT', 'Release Report', '', '', 'TOTAL RELEASES', releases.length], 'meta');
      pushRow(['DEPARTMENT', section.departmentName, '', '', 'MANAGER', section.managerName || managerName], 'meta');
      pushRow(headers, 'header');

      if (releases.length) {
        releases.forEach((release, index) => pushRow(buildReportRow(release, index), 'data', release));
      } else {
        pushMergedRow(['No release records found for this department.'], 'empty');
      }
    });

    const worksheet = XLSX.utils.aoa_to_sheet(rows);
    worksheet['!merges'] = [
      ...merges,
      XLSX.utils.decode_range('B4:D4'),
      XLSX.utils.decode_range(`F4:${reportEndColumn}4`),
      XLSX.utils.decode_range('B5:D5'),
      XLSX.utils.decode_range(`F5:${reportEndColumn}5`),
      XLSX.utils.decode_range('B6:D6'),
      XLSX.utils.decode_range(`F6:${reportEndColumn}6`),
      XLSX.utils.decode_range('B7:D7'),
      XLSX.utils.decode_range(`F7:${reportEndColumn}7`),
      XLSX.utils.decode_range('B8:D8'),
      XLSX.utils.decode_range(`F8:${reportEndColumn}8`)
    ];
    worksheet['!cols'] = [
      { wch: 8 }, { wch: 22 }, { wch: 30 }, { wch: 25 }, { wch: 30 }, { wch: 20 },
      { wch: 18 }, { wch: 15 }, { wch: 15 }, { wch: 18 }, { wch: 22 },
      { wch: 18 }, { wch: 18 }, { wch: 15 }, { wch: 15 }, { wch: 15 },
      { wch: 20 }, { wch: 25 }, { wch: 34 }
    ];
    worksheet['!rows'] = rows.map((row, index) => {
      const kind = rowKinds[index];

      if (kind === 'title') return { hpt: 28 };
      if (kind === 'subtitle') return { hpt: 19 };
      if (kind === 'section') return { hpt: 26 };
      if (kind === 'header') return { hpt: 29 };
      if (kind === 'spacer') return { hpt: 8 };
      if (kind === 'empty') return { hpt: 24 };
      if (kind === 'data') {
        const projectLines = Math.ceil(String(row[1] || '').length / 24);
        const titleLines = Math.ceil(String(row[2] || '').length / 36);
        const assigneeLines = Math.ceil(String(row[5] || '').length / 24);
        const testerLines = Math.ceil(String(row[9] || '').length / 24);
        const overdueStatusLines = Math.ceil(String(row[17] || '').length / 30);
        const remarksLines = Math.ceil(String(row[18] || '').length / 38);
        const visibleLines = Math.max(1, projectLines, titleLines, assigneeLines, testerLines, overdueStatusLines, remarksLines);
        return { hpt: Math.min(66, Math.max(24, visibleLines * 18)) };
      }

      return { hpt: 23 };
    });
    worksheet['!margins'] = {
      left: 0.25, right: 0.25, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2
    };

    const workbook = XLSX.utils.book_new();
    workbook.Props = {
      Title: 'Release Overview Report',
      Subject: `${project} ${department} department-wise release activity`,
      Author: String(generatedBy),
      Company: 'RIDSYS'
    };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Release Overview');

    const baseFile = XLSX.write(workbook, {
      bookType: 'xlsx',
      type: 'array',
      cellStyles: true
    });
    const styledFile = this.applyProfessionalReleaseStyles(baseFile, [], [], [], [], rowKinds, rowReleases);
    const filename = `RELEASE_REPORT${departmentFilePart}_${fromDate}_to_${toDate}.xlsx`;
    this.downloadWorkbook(styledFile, filename);
  }

  private applyProfessionalReleaseStyles(
    file: ArrayBuffer,
    statusStyles: number[],
    releasePerformanceStyles: number[],
    overdueStyles: number[],
    overdueStatusStyles: number[],
    rowKinds: string[] = [],
    rowReleases: Array<any | null> = []
  ): any {
    const archive = XLSX.CFB.read(new Uint8Array(file), { type: 'buffer' });
    const stylesFile = XLSX.CFB.find(archive, 'styles.xml');
    const sheetFile = XLSX.CFB.find(archive, 'sheet1.xml');

    if (!stylesFile || !sheetFile) {
      throw new Error('Unable to apply Excel report styling.');
    }

    stylesFile.content = new TextEncoder().encode(this.releaseStylesXml());

    let sheetXml = new TextDecoder().decode(sheetFile.content);
    sheetXml = sheetXml.replace(
      /<sheetViews>[\s\S]*?<\/sheetViews>/,
      '<sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="9" topLeftCell="A10" activePane="bottomLeft" state="frozen"/><selection pane="bottomLeft" activeCell="A10" sqref="A10"/></sheetView></sheetViews>'
    );
    const hasExplicitRowKinds = rowKinds.length > 0;
    const groupedDataRowIndexes = new Map<number, number>();
    let groupedDataRowIndex = 0;
    if (hasExplicitRowKinds) {
      rowKinds.forEach((kind, index) => {
        if (kind === 'data') {
          groupedDataRowIndexes.set(index + 1, groupedDataRowIndex++);
        }
      });
    }

    sheetXml = sheetXml.replace(/<c r="([A-Z]+)(\d+)"([^>]*)>/g, (match, column, rowText, attributes) => {
      const row = Number(rowText);
      let styleId = 0;

      if (hasExplicitRowKinds) {
        const rowKind = rowKinds[row - 1] || '';

        if (rowKind === 'title' || rowKind === 'section') styleId = 1;
        else if (rowKind === 'subtitle') styleId = 2;
        else if (rowKind === 'meta') styleId = column === 'A' || column === 'E' ? 3 : 4;
        else if (rowKind === 'header') styleId = 5;
        else if (rowKind === 'empty') styleId = 7;
        else if (rowKind === 'data') {
          const dataIndex = groupedDataRowIndexes.get(row) || 0;
          const alternate = dataIndex % 2 === 1;
          const centered = ['A', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R'].includes(column);
          const boldBodyColumn = ['D', 'E', 'I'].includes(column);
          if (boldBodyColumn && centered) {
            styleId = alternate ? 9 : 7;
          } else if (boldBodyColumn) {
            styleId = alternate ? 18 : 17;
          } else {
            styleId = centered ? (alternate ? 9 : 7) : (alternate ? 8 : 6);
          }

          const release = rowReleases[row - 1];
          if (release) {
            if (column === 'G') styleId = this.getReleasePerformanceStyleId(release) || styleId;
            if (column === 'O') styleId = this.getStatusStyleId(release?.status) || styleId;
            if (column === 'Q') styleId = this.getReleaseOverdueStyleId(release) || styleId;
            if (column === 'R') styleId = this.getReleaseOverdueStatusStyleId(release) || styleId;
          }
        }
      } else {
        if (row === 1) styleId = 1;
        else if (row === 2) styleId = 2;
        else if (row >= 4 && row <= 8) styleId = column === 'A' || column === 'E' ? 3 : 4;
        else if (row === 9) styleId = 5;
        else if (row >= 10) {
          const alternate = (row - 10) % 2 === 1;
          const centered = ['A', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R'].includes(column);
          const boldBodyColumn = ['D', 'E', 'I'].includes(column);
          if (boldBodyColumn && centered) {
            styleId = alternate ? 9 : 7;
          } else if (boldBodyColumn) {
            styleId = alternate ? 18 : 17;
          } else {
            styleId = centered ? (alternate ? 9 : 7) : (alternate ? 8 : 6);
          }
          if (column === 'G') styleId = releasePerformanceStyles[row - 10] || styleId;
          if (column === 'O') styleId = statusStyles[row - 10] || styleId;
          if (column === 'Q') styleId = overdueStyles[row - 10] || styleId;
          if (column === 'R') styleId = overdueStatusStyles[row - 10] || styleId;
        }
      }

      const cleanAttributes = String(attributes).replace(/\s+s="\d+"/, '');
      return `<c r="${column}${row}" s="${styleId}"${cleanAttributes}>`;
    });
    sheetFile.content = new TextEncoder().encode(sheetXml);
    
    return XLSX.CFB.write(archive, {
      fileType: 'zip',
      type: 'array',
      compression: true
    });
  }

  private getStatusStyleId(status: any): number {
    const key = String(status || '').trim().toLowerCase().replace(/[\s_]+/g, '-');
    if (key === 'open') return 7;
    if (['in-progress', 'active'].includes(key)) return 10;
    if (key === 'upcoming-release') return 15;
    if (key === 'on-hold') return 16;
    if (key === 'to-be-tested' || key === 'in-review') return 14;
    if (key === 'rejected') return 12;
    if (['pass', 'passed', 'completed', 'approved'].includes(key)) return 11;
    if (['failed', 'cancelled'].includes(key)) return 13;
    return 7;
  }

  private getProjectOrderedReleaseData(rawData: any[]): any[] {
    const data = Array.isArray(rawData) ? rawData : rawData ? [rawData] : [];

    return [...data].sort((first: any, second: any) => {
      const projectCompare = this.getReleaseProjectName(first).localeCompare(
        this.getReleaseProjectName(second),
        undefined,
        { sensitivity: 'base', numeric: true }
      );

      if (projectCompare !== 0) {
        return projectCompare;
      }

      const dateCompare = this.getReleaseDateSortValue(first?.released_date) - this.getReleaseDateSortValue(second?.released_date);

      if (dateCompare !== 0) {
        return dateCompare;
      }

      const titleCompare = `${first?.title ?? ''}`.localeCompare(`${second?.title ?? ''}`, undefined, {
        sensitivity: 'base',
        numeric: true
      });

      if (titleCompare !== 0) {
        return titleCompare;
      }

      return `${first?.version ?? ''}`.localeCompare(`${second?.version ?? ''}`, undefined, {
        sensitivity: 'base',
        numeric: true
      });
    });
  }

  private getReleaseProjectName(release: any): string {
    return `${release?.project_name || release?.project_title || ''}`.trim();
  }

  private getReleaseDateSortValue(value: any): number {
    const parsed = this.parseReleaseDate(`${value ?? ''}`.trim());
    return parsed ? parsed.getTime() : Number.MAX_SAFE_INTEGER;
  }

  private isReleaseOverdue(release: any): boolean {
    if (!this.isUpcomingRelease(release)) {
      return false;
    }

    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);
    return daysUntilRelease !== null && daysUntilRelease < 0;
  }

  private getReleaseOverdueDate(release: any): string {
    if (!this.isUpcomingRelease(release)) {
      const completionDate = this.getReleaseCompletionDate(release);
      return completionDate ? this.formatReleaseDateOnly(completionDate) : '-';
    }

    const overdueState = this.getReleaseOverdueState(release);

    if (overdueState === 'overdue') {
      return this.formatReleaseDateOnly(`${release?.released_date ?? ''}`.trim()) || '-';
    }

    return '-';
  }

  private getReleaseOverdueStatus(release: any): string {
    if (!this.isUpcomingRelease(release)) {
      return '-';
    }

    const overdueStatusState = this.getReleaseOverdueStatusState(release);
    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);

    if (overdueStatusState === 'overdue') {
      return 'Overdue';
    }

    if (overdueStatusState === 'high-warning') {
      return daysUntilRelease === 0 ? 'Due Today' : 'Due Tomorrow';
    }

    if (overdueStatusState === 'warning') {
      return `Due in ${daysUntilRelease} Days`;
    }

    return '-';
  }

  private getReleaseOverdueState(release: any): ReleasePerformanceState | 'warning' | 'high-warning' | 'overdue' {
    if (!this.isUpcomingRelease(release)) {
      return this.getReleasePerformanceState(release);
    }

    return this.isReleaseOverdue(release) ? 'overdue' : 'none';
  }

  private getReleaseOverdueStatusState(release: any): 'none' | 'warning' | 'high-warning' | 'overdue' {
    if (!this.isUpcomingRelease(release)) {
      return 'none';
    }

    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);

    if (daysUntilRelease === null) {
      return 'none';
    }

    if (daysUntilRelease < 0) {
      return 'overdue';
    }

    if (daysUntilRelease <= 1) {
      return 'high-warning';
    }

    return 'warning';
  }

  private getReleaseOverdueStyleId(release: any): number {
    const overdueState = this.getReleaseOverdueState(release);
    if (overdueState === 'excellent') return 11;
    if (overdueState === 'very-good') return 14;
    if (overdueState === 'good') return 10;
    if (overdueState === 'poor') return 13;
    if (overdueState === 'overdue') return 13;
    return 0;
  }

  private getReleaseOverdueStatusStyleId(release: any): number {
    const overdueStatusState = this.getReleaseOverdueStatusState(release);
    if (overdueStatusState === 'warning') return 12;
    if (overdueStatusState === 'high-warning') return 16;
    if (overdueStatusState === 'overdue') return 13;
    return 0;
  }

  private getReleaseTesterName(release: any): string {
    if (this.isUpcomingRelease(release)) {
      return '-';
    }

    return `${release?.assignee_to_name ?? ''}`.trim() || '-';
  }

  private getReleaseQcTestingStartDate(release: any): string {
    const qcTestingStartDate = this.getFirstDateValue(release, ['qc_testing_start_date', 'qcTestingStartDate']);

    if (qcTestingStartDate) {
      return this.formatReleaseDateOnly(qcTestingStartDate) || '';
    }

    return '';
  }

  private isUpcomingRelease(release: any): boolean {
    return this.normalizeReleaseStatus(release?.status) === 'upcoming-release';
  }

  private getReleasePerformance(release: any): string {
    if (this.isReleasePerformancePending(release)) {
      return 'Pending';
    }

    if (this.isUpcomingRelease(release)) {
      return 'Pending';
    }

    const performanceState = this.getReleasePerformanceState(release);
    if (performanceState === 'excellent') return 'Excellent';
    if (performanceState === 'very-good') return 'Very Good';
    if (performanceState === 'good') return 'Good';
    if (performanceState === 'poor') return 'Poor';
    return '-';
  }

  private getReleasePerformanceStyleId(release: any): number {
    const performance = this.getReleasePerformance(release);
    if (performance === 'Excellent') return 11;
    if (performance === 'Very Good') return 14;
    if (performance === 'Good') return 10;
    if (performance === 'Poor') return 13;
    return 0;
  }

  private isReleasePerformancePending(release: any): boolean {
    const statusKey = this.normalizeReleaseStatus(release?.status);
    return statusKey === 'pending';
  }

  private getReleasePerformanceState(release: any): ReleasePerformanceState {
    const releaseDate = this.parseReleaseDate(this.getFirstDateValue(release, [
      'released_date',
      'release_date',
      'releaseDate',
      'scheduled_release_date',
      'scheduledReleaseDate'
    ]) || '');
    const completedDate = this.parseReleaseDate(this.getReleaseCompletionDate(release) || '');

    if (!releaseDate || !completedDate) {
      return 'none';
    }

    const plannedDate = this.parseReleaseDate(this.getFirstDateValue(release, [
      'planned_date',
      'plannedDate',
      'scheduled_date',
      'scheduledDate'
    ]) || '');
    const releaseTime = this.getStartOfDayTime(releaseDate);
    const completedTime = this.getStartOfDayTime(completedDate);
    const plannedTime = plannedDate ? this.getStartOfDayTime(plannedDate) : null;
    const daysBeforeRelease = Math.floor((releaseTime - completedTime) / 86400000);

    if (daysBeforeRelease >= 2) {
      return 'excellent';
    }

    if (daysBeforeRelease === 1) {
      return 'very-good';
    }

    if (daysBeforeRelease === 0) {
      return plannedTime === releaseTime ? 'excellent' : 'good';
    }

    return 'poor';
  }

  private getReleaseCompletionDate(release: any): string | null {
    const transitionDate = this.getToBeTestedTransitionDate(release);

    if (transitionDate) {
      return transitionDate;
    }

    return this.getFirstDateValue(release, [
      'completed_date',
      'completedDate',
      'completion_date',
      'completionDate',
      'closed_date',
      'closedDate',
      'qc_released_date',
      'qcReleasedDate',
      'qc_release_date',
      'qcReleaseDate',
      'actual_release_date',
      'actualReleaseDate'
    ]);
  }

  private getToBeTestedTransitionDate(release: any): string | null {
    const explicitTransitionDate = this.getFirstDateValue(release, [
      'to_be_tested_date',
      'toBeTestedDate',
      'to_be_tested_at',
      'toBeTestedAt',
      'release_tested_date',
      'release_status_changed_date',
      'status_changed_date'
    ]);

    if (explicitTransitionDate) {
      return explicitTransitionDate;
    }

    const timelineDate = this.getFirstToBeTestedTimelineDate(
      release?.status_logs || release?.statusLogs || release?.activity_logs || release?.activityLogs || release?.logs
    );

    if (timelineDate) {
      return timelineDate;
    }

    if (this.normalizeReleaseStatus(release?.status) === 'to-be-tested') {
      return this.getFirstDateValue(release, ['updateddate', 'updated_date']);
    }

    return null;
  }

  private getFirstToBeTestedTimelineDate(logs: any): string | null {
    const timeline = Array.isArray(logs) ? logs : [];
    const toBeTestedLogs = timeline
      .map((log: any) => ({
        date: this.getFirstDateValue(log, ['logdate', 'created_date', 'createddate', 'updated_date', 'updateddate']),
        status: this.normalizeReleaseStatus(log?.status)
      }))
      .filter((log: any) => log.status === 'to-be-tested' && !!log.date)
      .map((log: any) => ({
        date: log.date,
        time: this.getReleaseDateTime(log.date)
      }))
      .filter((log: any) => log.time !== null)
      .sort((first: any, second: any) => first.time - second.time);

    return toBeTestedLogs[0]?.date || null;
  }

  private getFirstDateValue(source: any, keys: string[]): string | null {
    for (const key of keys) {
      const value = `${source?.[key] ?? ''}`.trim();
      if (value && this.getReleaseDateTime(value) !== null) {
        return value;
      }
    }

    return null;
  }

  private getReleaseDateTime(value: string): number | null {
    const parsed = this.parseReleaseDate(value);
    return parsed ? parsed.getTime() : null;
  }

  private getStartOfDayTime(date: Date): number {
    const normalizedDate = new Date(date);
    normalizedDate.setHours(0, 0, 0, 0);
    return normalizedDate.getTime();
  }

  private normalizeReleaseStatus(status: any): string {
    return `${status ?? ''}`.trim().toLowerCase().replace(/[-_\s]+/g, '-');
  }

  private formatReleaseDateOnly(value: string): string {
    const parsed = this.parseReleaseDate(`${value ?? ''}`.trim());

    if (!parsed) {
      return `${value ?? ''}`.trim();
    }

    return `${parsed.getFullYear()}-${String(parsed.getMonth() + 1).padStart(2, '0')}-${String(
      parsed.getDate()
    ).padStart(2, '0')}`;
  }

  private getDaysUntilRelease(releasedDate: string | null | undefined): number | null {
    const rawValue = `${releasedDate ?? ''}`.trim();
    if (!rawValue) {
      return null;
    }

    const releaseDate = this.parseReleaseDate(rawValue);
    if (!releaseDate) {
      return null;
    }

    releaseDate.setHours(0, 0, 0, 0);

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    return Math.ceil((releaseDate.getTime() - today.getTime()) / 86400000);
  }

  private parseReleaseDate(value: string): Date | null {
    const normalized = value.trim();
    const ymdParts = normalized.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})(?:[T\s].*)?$/);

    if (ymdParts) {
      const year = Number(ymdParts[1]);
      const month = Number(ymdParts[2]);
      const day = Number(ymdParts[3]);
      const parsed = new Date(year, month - 1, day);
      return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    const dmyParts = normalized.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{4})(?:[T\s].*)?$/);

    if (dmyParts) {
      const day = Number(dmyParts[1]);
      const month = Number(dmyParts[2]);
      const year = Number(dmyParts[3]);
      const parsed = new Date(year, month - 1, day);
      return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    const parsed = new Date(normalized);
    return Number.isNaN(parsed.getTime()) ? null : parsed;
  }

  private downloadWorkbook(file: any, filename: string): void {
    const blob = new Blob([file], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  private releaseStylesXml(): string {
    return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <fonts count="15">
    <font><sz val="11"/><color theme="1"/><name val="Calibri"/><family val="2"/><scheme val="minor"/></font>
    <font><b/><sz val="20"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font>
    <font><i/><sz val="10"/><color rgb="FFBFDBFE"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FF1D4ED8"/><name val="Calibri"/></font>
    <font><sz val="10"/><color rgb="FF1E293B"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font>
    <font><sz val="10"/><color rgb="FF334155"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FF475569"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FF2563EB"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FF16A34A"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FFD97706"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FFDC2626"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FF7C3AED"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FFDB2777"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FFEA580C"/><name val="Calibri"/></font>
  </fonts>
  <fills count="13">
    <fill><patternFill patternType="none"/></fill>
    <fill><patternFill patternType="gray125"/></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF059669"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFEFF6FF"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF2563EB"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFFFFFFF"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFF8FAFC"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFDCFCE7"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFFEE2E2"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFDBEAFE"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFFEF3C7"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFF3E8FF"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFF1F5F9"/><bgColor indexed="64"/></patternFill></fill>
  </fills>
  <borders count="2">
    <border><left/><right/><top/><bottom/><diagonal/></border>
    <border><left style="thin"><color rgb="FFE2E8F0"/></left><right style="thin"><color rgb="FFE2E8F0"/></right><top style="thin"><color rgb="FFE2E8F0"/></top><bottom style="thin"><color rgb="FFE2E8F0"/></bottom><diagonal/></border>
  </borders>
  <cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>
  <cellXfs count="25">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
    <xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1" shrinkToFit="1"/></xf>
    <xf numFmtId="0" fontId="2" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1" shrinkToFit="1"/></xf>
    <xf numFmtId="0" fontId="3" fillId="3" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center"/></xf>
    <xf numFmtId="0" fontId="4" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center"/></xf>
    <xf numFmtId="0" fontId="5" fillId="4" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="6" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center" indent="1" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="7" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="6" fillId="6" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center" indent="1" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="7" fillId="6" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="8" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="9" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="10" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="11" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="12" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="13" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="14" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="7" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center" indent="1" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="7" fillId="6" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center" indent="1" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="9" fillId="7" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="11" fillId="8" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="8" fillId="9" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="10" fillId="10" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="12" fillId="11" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="7" fillId="12" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
  </cellXfs>
  <cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>
  <dxfs count="0"/>
  <tableStyles count="0" defaultTableStyle="TableStyleMedium2" defaultPivotStyle="PivotStyleLight16"/>
</styleSheet>`;
  }
}
