import { Injectable } from '@angular/core';
import * as XLSX from 'xlsx';

@Injectable({
  providedIn: 'root'
})
export class ExcelService {
  generateReleaseOverviewExcel(
    filters: any,
    fromDate: string,
    toDate: string,
    rawData: any[]
  ): void {
    if (typeof XLSX === 'undefined') {
      throw new Error('Excel export library is not available.');
    }

    const data = Array.isArray(rawData) ? rawData : rawData ? [rawData] : [];
    const generatedBy = filters?.generatedBy || 'System User';
    const project = filters?.filteredProject || 'All Projects';
    const releaseType = filters?.releaseType || 'All';
    const exportedAt = new Date().toLocaleString();
    const internalReleaseCount = data.filter(
      (release: any) => String(release?.release_type || '').trim().toLowerCase() === 'internal'
    ).length;
    const externalReleaseCount = data.filter(
      (release: any) => String(release?.release_type || '').trim().toLowerCase() === 'external'
    ).length;
    const headers = [
      'PROJECT', 'TITLE', 'VERSION', 'WORKED BY / RELEASED BY', 'RELEASE PERFORMANCE', 'RELEASE DATE', 'TESTED BY',
      'QC RELEASED DATE', 'CLIENT', 'STATUS', 'RELEASE TYPE', 'OVERDUE DATE'
    ];

    // Keep the Excel columns in the same order as the Release Overview PDF.
    const reportRows = data.map((release: any) => [
      release.project_name || release.project_title || '-',
      release.title || '-',
      release.version || '-',
      release.assignee_from_name || '-',
      this.getReleasePerformance(release),
      release.released_date || '-',
      this.getReleaseTesterName(release),
      release.closed_date ? release.closed_date.split('T')[0] : '-',
      release.company_name || '-',
      release.status || '-',
      release.release_type || '-',
      this.getReleaseOverdueDate(release)
    ]);

    const worksheet = XLSX.utils.aoa_to_sheet([
      ['RELEASE OVERVIEW REPORT', '', '', '', '', '', '', '', '', '', '', ''],
      ['R-SPACE PRO  |  RELEASE ACTIVITY REPORT', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', ''],
      ['GENERATED BY', generatedBy, '', '', 'REPORTING PERIOD', `${fromDate} to ${toDate}`, '', '', '', '', '', ''],
      ['PROJECT', project, '', '', 'RELEASE TYPE', releaseType, '', '', '', '', '', ''],
      ['TOTAL RELEASES', data.length, '', '', 'INTERNAL RELEASES', internalReleaseCount, '', '', '', '', '', ''],
      ['EXTERNAL RELEASES', externalReleaseCount, '', '', 'EXPORTED AT', exportedAt, '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', ''],
      headers,
      ...reportRows
    ]);

    worksheet['!merges'] = [
      XLSX.utils.decode_range('A1:L1'),
      XLSX.utils.decode_range('A2:L2'),
      XLSX.utils.decode_range('B4:D4'),
      XLSX.utils.decode_range('F4:L4'),
      XLSX.utils.decode_range('B5:D5'),
      XLSX.utils.decode_range('F5:L5'),
      XLSX.utils.decode_range('B6:D6'),
      XLSX.utils.decode_range('F6:L6'),
      XLSX.utils.decode_range('B7:D7'),
      XLSX.utils.decode_range('F7:L7'),
      XLSX.utils.decode_range('F8:L8')
    ];
    worksheet['!cols'] = [
      { wch: 25 }, { wch: 38 }, { wch: 14 }, { wch: 20 },
      { wch: 20 }, { wch: 18 }, { wch: 25 }, { wch: 18 }, { wch: 18 }, { wch: 18 },
      { wch: 18 }, { wch: 18 }
    ];
    const dataRowHeights = reportRows.map((row: any[]) => {
      const projectLines = Math.ceil(String(row[0] || '').length / 24);
      const titleLines = Math.ceil(String(row[1] || '').length / 36);
      const assigneeLines = Math.ceil(String(row[3] || '').length / 24);
      const testerLines = Math.ceil(String(row[6] || '').length / 24);
      const visibleLines = Math.max(1, projectLines, titleLines, assigneeLines, testerLines);
      return { hpt: Math.min(66, Math.max(24, visibleLines * 18)) };
    });
    worksheet['!rows'] = [
      { hpt: 28 }, { hpt: 19 }, { hpt: 8 },
      { hpt: 23 }, { hpt: 23 }, { hpt: 23 }, { hpt: 23 }, { hpt: 8 }, { hpt: 29 },{ hpt: 29 },
      ...dataRowHeights
    ];
    worksheet['!autofilter'] = { ref: `A9:L${Math.max(data.length + 9, 9)}` };
    worksheet['!margins'] = {
      left: 0.25, right: 0.25, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2
    };

    const workbook = XLSX.utils.book_new();
    workbook.Props = {
      Title: 'Release Overview Report',
      Subject: `${project} release activity`,
      Author: String(generatedBy),
      Company: 'RIDSYS'
    };
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Release Overview');

    const statusStyles = data.map((release: any) => this.getStatusStyleId(release?.status));
    const releasePerformanceStyles = data.map((release: any) => this.getReleasePerformanceStyleId(release));
    const overdueStyles = data.map((release: any) => this.getReleaseOverdueStyleId(release));
    const baseFile = XLSX.write(workbook, {
      bookType: 'xlsx',
      type: 'array',
      cellStyles: true
    });
    const styledFile = this.applyProfessionalReleaseStyles(baseFile, statusStyles, releasePerformanceStyles, overdueStyles);

    const safeUser = String(generatedBy).replace(/[^a-z0-10_-]+/gi, '_');
    const filename = `RELEASE_REPORT_${fromDate}_to_${toDate}.xlsx`;
    this.downloadWorkbook(styledFile, filename);
  }

  private applyProfessionalReleaseStyles(
    file: ArrayBuffer,
    statusStyles: number[],
    releasePerformanceStyles: number[],
    overdueStyles: number[]
  ): any {
    const archive = XLSX.CFB.read(new Uint8Array(file), { type: 'buffer' });
    const stylesFile = XLSX.CFB.find(archive, 'styles.xml');
    const sheetFile = XLSX.CFB.find(archive, 'sheet1.xml');

    if (!stylesFile || !sheetFile) {
      throw new Error('Unable to apply Excel report styling.');
    }

    stylesFile.content = new TextEncoder().encode(this.releaseStylesXml());

    let sheetXml = new TextDecoder().decode(sheetFile.content);
    sheetXml = sheetXml.replace(
      /<sheetViews>[\s\S]*?<\/sheetViews>/,
      '<sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="9" topLeftCell="A10" activePane="bottomLeft" state="frozen"/><selection pane="bottomLeft" activeCell="A10" sqref="A10"/></sheetView></sheetViews>'
    );
    sheetXml = sheetXml.replace(/<c r="([A-L])(\d+)"([^>]*)>/g, (match, column, rowText, attributes) => {
      const row = Number(rowText);
      let styleId = 0;

      if (row === 1) styleId = 1;
      else if (row === 2) styleId = 2;
      else if (row >= 4 && row <= 7) styleId = column === 'A' || column === 'E' ? 3 : 4;
      else if (row === 9) styleId = 5;
      else if (row >= 10) {
        const alternate = (row - 10) % 2 === 1;
        const centered = ['C', 'D', 'E', 'F', 'H', 'I', 'J', 'K', 'L'].includes(column);
        const boldBodyColumn = ['C', 'D', 'G'].includes(column);
        if (boldBodyColumn && centered) {
          styleId = alternate ? 9 : 7;
        } else if (boldBodyColumn) {
          styleId = alternate ? 18 : 17;
        } else {
          styleId = centered ? (alternate ? 9 : 7) : (alternate ? 8 : 6);
        }
        if (column === 'E') styleId = releasePerformanceStyles[row - 10] || styleId;
        if (column === 'J') styleId = statusStyles[row - 10] || styleId;
        if (column === 'L') styleId = overdueStyles[row - 10] || styleId;
      }

      const cleanAttributes = String(attributes).replace(/\s+s="\d+"/, '');
      return `<c r="${column}${row}" s="${styleId}"${cleanAttributes}>`;
    });
    sheetFile.content = new TextEncoder().encode(sheetXml);
    
    return XLSX.CFB.write(archive, {
      fileType: 'zip',
      type: 'array',
      compression: true
    });
  }

  private getStatusStyleId(status: any): number {
    const key = String(status || '').trim().toLowerCase().replace(/[\s_]+/g, '-');
    if (key === 'open') return 7;
    if (['in-progress', 'active'].includes(key)) return 10;
    if (key === 'upcoming-release') return 15;
    if (key === 'on-hold') return 16;
    if (key === 'to-be-tested' || key === 'in-review') return 14;
    if (key === 'rejected') return 12;
    if (['pass', 'passed', 'completed', 'approved'].includes(key)) return 11;
    if (['failed', 'cancelled'].includes(key)) return 13;
    return 7;
  }

  private isReleaseOverdue(release: any): boolean {
    if (!this.isUpcomingRelease(release)) {
      return false;
    }

    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);
    return daysUntilRelease !== null && daysUntilRelease < 0;
  }

  private getReleaseOverdueDate(release: any): string {
    const overdueState = this.getReleaseOverdueState(release);
    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);

    if (overdueState === 'overdue') {
      return `${release?.released_date ?? ''}`.trim() || '-';
    }

    if (overdueState === 'high-warning') {
      return daysUntilRelease === 0 ? 'Due Today' : 'Due Tomorrow';
    }

    if (overdueState === 'warning') {
      return `Due in ${daysUntilRelease} days`;
    }

    return '-';
  }

  private getReleaseOverdueState(release: any): 'none' | 'warning' | 'high-warning' | 'overdue' {
    if (!this.isUpcomingRelease(release)) {
      return 'none';
    }

    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);

    if (daysUntilRelease === null) {
      return 'none';
    }

    if (daysUntilRelease < 0) {
      return 'overdue';
    }

    if (daysUntilRelease <= 1) {
      return 'high-warning';
    }

    return 'warning';
  }

  private getReleaseOverdueStyleId(release: any): number {
    const overdueState = this.getReleaseOverdueState(release);
    if (overdueState === 'warning') return 12;
    if (overdueState === 'high-warning') return 16;
    if (overdueState === 'overdue') return 13;
    return 0;
  }

  private getReleaseTesterName(release: any): string {
    if (this.isUpcomingRelease(release)) {
      return '-';
    }

    return `${release?.assignee_to_name ?? ''}`.trim() || '-';
  }

  private isUpcomingRelease(release: any): boolean {
    const status = String(release?.status || '').trim().toLowerCase().replace(/[-_\s]+/g, '-');
    return status === 'upcoming-release';
  }

  private getReleasePerformance(release: any): string {
    if (this.isUpcomingRelease(release)) {
      return this.isReleaseOverdue(release) ? 'Poor' : 'Pending';
    }

    if (this.isReleasePerformancePending(release)) {
      return 'Pending';
    }

    const plannedDate = this.parseReleaseDate(`${release?.planned_date ?? ''}`.trim());
    const releaseDate = this.parseReleaseDate(`${release?.released_date ?? ''}`.trim());

    if (!plannedDate || !releaseDate) {
      return '-';
    }

    plannedDate.setHours(0, 0, 0, 0);
    releaseDate.setHours(0, 0, 0, 0);

    if (releaseDate.getTime() < plannedDate.getTime()) {
      return 'Very Good';
    }

    if (releaseDate.getTime() === plannedDate.getTime()) {
      return 'Good';
    }

    return 'Poor';
  }

  private getReleasePerformanceStyleId(release: any): number {
    const performance = this.getReleasePerformance(release);
    if (performance === 'Very Good') return 11;
    if (performance === 'Good') return 10;
    if (performance === 'Poor') return 13;
    return 0;
  }

  private isReleasePerformancePending(release: any): boolean {
    const statusKey = String(release?.status || '').trim().toLowerCase().replace(/[-_\s]+/g, '-');
    return statusKey === 'pending';
  }

  private getDaysUntilRelease(releasedDate: string | null | undefined): number | null {
    const rawValue = `${releasedDate ?? ''}`.trim();
    if (!rawValue) {
      return null;
    }

    if (rawValue.toLowerCase() === 'overdue') {
      return 0;
    }

    const releaseDate = this.parseReleaseDate(rawValue);
    if (!releaseDate) {
      return null;
    }

    releaseDate.setHours(0, 0, 0, 0);

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    return Math.ceil((releaseDate.getTime() - today.getTime()) / 86400000);
  }

  private parseReleaseDate(value: string): Date | null {
    const normalized = value.trim();
    const ymdParts = normalized.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})$/);

    if (ymdParts) {
      const year = Number(ymdParts[1]);
      const month = Number(ymdParts[2]);
      const day = Number(ymdParts[3]);
      const parsed = new Date(year, month - 1, day);
      return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    const dmyParts = normalized.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{4})$/);

    if (dmyParts) {
      const day = Number(dmyParts[1]);
      const month = Number(dmyParts[2]);
      const year = Number(dmyParts[3]);
      const parsed = new Date(year, month - 1, day);
      return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    const parsed = new Date(normalized);
    return Number.isNaN(parsed.getTime()) ? null : parsed;
  }

  private downloadWorkbook(file: any, filename: string): void {
    const blob = new Blob([file], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  private releaseStylesXml(): string {
    return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <fonts count="15">
    <font><sz val="11"/><color theme="1"/><name val="Calibri"/><family val="2"/><scheme val="minor"/></font>
    <font><b/><sz val="20"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font>
    <font><i/><sz val="10"/><color rgb="FFBFDBFE"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FF1D4ED8"/><name val="Calibri"/></font>
    <font><sz val="10"/><color rgb="FF1E293B"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font>
    <font><sz val="10"/><color rgb="FF334155"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FF475569"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FF2563EB"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FF16A34A"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FFD97706"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FFDC2626"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FF7C3AED"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FFDB2777"/><name val="Calibri"/></font>
    <font><b/><sz val="10"/><color rgb="FFEA580C"/><name val="Calibri"/></font>
  </fonts>
  <fills count="7">
    <fill><patternFill patternType="none"/></fill>
    <fill><patternFill patternType="gray125"/></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF059669"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFEFF6FF"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF2563EB"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFFFFFFF"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FFF8FAFC"/><bgColor indexed="64"/></patternFill></fill>
  </fills>
  <borders count="2">
    <border><left/><right/><top/><bottom/><diagonal/></border>
    <border><left style="thin"><color rgb="FFE2E8F0"/></left><right style="thin"><color rgb="FFE2E8F0"/></right><top style="thin"><color rgb="FFE2E8F0"/></top><bottom style="thin"><color rgb="FFE2E8F0"/></bottom><diagonal/></border>
  </borders>
  <cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>
  <cellXfs count="19">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
    <xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1" shrinkToFit="1"/></xf>
    <xf numFmtId="0" fontId="2" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1" shrinkToFit="1"/></xf>
    <xf numFmtId="0" fontId="3" fillId="3" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center"/></xf>
    <xf numFmtId="0" fontId="4" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center"/></xf>
    <xf numFmtId="0" fontId="5" fillId="4" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="6" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center" indent="1" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="7" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="6" fillId="6" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center" indent="1" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="7" fillId="6" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="8" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="9" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="10" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="11" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="12" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="13" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="14" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>
    <xf numFmtId="0" fontId="7" fillId="5" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center" indent="1" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="7" fillId="6" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="center" indent="1" wrapText="1"/></xf>
  </cellXfs>
  <cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>
  <dxfs count="0"/>
  <tableStyles count="0" defaultTableStyle="TableStyleMedium2" defaultPivotStyle="PivotStyleLight16"/>
</styleSheet>`;
  }
}
