import { Injectable } from '@angular/core';
interface DSRRecord {
  id: number;
  date: string;
  employee_name: string;
  project_title: string;
  sub_task: string;
  worked_hours: string;
  completion_percentage: number;
  task: string;
  comments: string;
  statusText?: string;
}
@Injectable({
  providedIn: 'root'
})
export class PdfService {

  constructor() { }

  private finalizePdf(doc: any, filename: string, mode: 'download' | 'preview' = 'download'): void {
    if (mode === 'preview') {
      const previewUrl = doc.output('bloburl');
      window.open(previewUrl, '_blank', 'noopener');
      return;
    }

    doc.save(filename);
  }

  generateDSRPdf(
    employeeName: string,
    monthLabel: string,
    data: any[]
  ): void {
    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a4');

      const PRIMARY_BLUE = [37, 99, 235];
      const TEXT_DARK = [30, 41, 59];

      /* HEADER */
      doc.setFontSize(28);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.setFont(undefined, 'bold');
      doc.text('RIDSYS', 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(148, 163, 184);
      doc.text('ENTERPRISE RESOURCE PERFORMANCE SYSTEM', 15, 26);

      /* TITLE */
      doc.setFontSize(22);
      doc.setTextColor(...TEXT_DARK);
      doc.text('EMPLOYEE DSR REPORT', 15, 45);

      doc.setDrawColor(...PRIMARY_BLUE);
      doc.setLineWidth(1);
      doc.line(15, 50, 80, 50);

      /* META */
      doc.setFontSize(11);
      doc.text(employeeName, 15, 66);
      doc.text(monthLabel.toUpperCase(), 120, 66);
      doc.text(`TOTAL LOGS: ${data.length}`, 220, 66);

      /* TABLE */
      (doc as any).autoTable({
        startY: 85,
        theme: 'grid',
        headStyles: {
          fillColor: [30, 41, 59],
          textColor: 255,
          fontStyle: 'bold',
          halign: 'center',
        },
        styles: {
          fontSize: 11,
          cellPadding: 6,
          overflow: 'linebreak',
          textColor: [51, 65, 85],
        },
        columns: [
          { header: 'DATE', dataKey: 'date' },
          { header: 'PROJECT', dataKey: 'project_title' },
          { header: 'SUB TASK', dataKey: 'sub_task' },
          { header: 'HOURS', dataKey: 'worked_hours' },
          { header: '%', dataKey: 'completion_percentage' },
          { header: 'REMARKS', dataKey: 'comments' },
        ],
        body: data,
        didDrawPage: () => {
          const pages = doc.internal.getNumberOfPages();
          doc.setFontSize(8);
          doc.setTextColor(148, 163, 184);
          doc.text(
            `DSR Page ${pages} • Generated by RIDSYS • Confidential`,
            15,
            202
          );
        },
      });

      doc.save(`DSR_${employeeName}_${monthLabel}.pdf`);
    } finally {

    }
  }


  generatePDF(employee: any, fromdate: any, todate: any, rawData: any[]) {

    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a4');
      const PRIMARY_BLUE = [37, 99, 235]; // bg-blue-600
      const TEXT_DARK = [30, 41, 59]; // slate-900

      const data = (Array.isArray(rawData) ? rawData : rawData ? [rawData] : []).map((item: any) => ({
        ...item,
        statusText: item?.statusText || 'Present'
      }));
      const isAllEmployeeExport = employee?.id === 0;
      const employeeName = employee?.id === 0
        ? 'All Employee'
        : employee?.employee_name || 'Employee';
      const employeePosition = employee?.position || 'All Employee';

      // 1. TOP HEADER (BRANDING)
      doc.setFontSize(28);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.setFont(undefined, 'bold');
      doc.text("RIDSYS", 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(148, 163, 184);
      doc.setFont(undefined, 'normal');
      doc.text("ENTERPRISE RESOURCE PERFORMANCE SYSTEM", 15, 26);

      // 2. MAIN TITLE SECTION
      doc.setFontSize(22);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.text("EMPLOYEE DSR REPORT", 15, 45);

      doc.setDrawColor(...PRIMARY_BLUE);
      doc.setLineWidth(1);
      doc.line(15, 50, 80, 50);

      // 3. METADATA GRID
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.setFont(undefined, 'bold');
      doc.text("EMPLOYEE DETAILS", 15, 60);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(employeeName.toUpperCase(), 15, 66);
      doc.setFont(undefined, 'normal');
      doc.text(`${employeePosition.toUpperCase()}`, 15, 71);

      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.setFont(undefined, 'bold');
      doc.text("REPORTING PERIOD", 120, 60);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      const rangeText = this.getDateRangeLabel(new Date(fromdate), new Date(todate));
      doc.text(rangeText.toUpperCase(), 120, 66);
      doc.setFont(undefined, 'normal');
      doc.text("Activity Log Output", 120, 71);

      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.setFont(undefined, 'bold');
      doc.text("EXPORT METRICS", 220, 60);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(`DATE: ${new Date().toLocaleDateString().toUpperCase()}`, 220, 66);
      doc.setFont(undefined, 'normal');
      doc.text(`TOTAL LOGS: ${data.length}`, 220, 71);

      // 4. MAIN DATA TABLE
      const columns = [
        { header: 'DATE', dataKey: 'date' },
        ...(isAllEmployeeExport ? [{ header: 'EMPLOYEE NAME', dataKey: 'employee_name' }] : []),
        { header: 'PROJECT TITLE', dataKey: 'project_title' },
        // { header: 'SUB TASK', dataKey: 'sub_task' },
        { header: 'TASK', dataKey: 'task' },
        { header: 'WORKED HRS', dataKey: 'worked_hours' },
        { header: 'PERCENTAGE', dataKey: 'completion_percentage' },
        { header: 'DETAILED REMARKS / TECHNICAL LOGS', dataKey: 'comments' }
      ];

      (doc as any).autoTable({
        columns: columns,
        body: data,
        startY: 85,
        theme: 'grid',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center',
          valign: 'middle',
          fontSize: 10,
          cellPadding: { top: 4, bottom: 4, left: 2, right: 2 },
          minCellWidth: 'wrap' // Header text won't wrap
        },
        styles: {
          fontSize: isAllEmployeeExport ? 10 : 11,
          cellPadding: 6,
          overflow: 'linebreak',
          textColor: [51, 65, 85],
          lineColor: [226, 232, 240],
          lineWidth: 0.1
        },
        columnStyles: isAllEmployeeExport ? {
          0: { cellWidth: 28, halign: 'center', fontStyle: 'bold' },
          1: { cellWidth: 38, fontStyle: 'bold' },
          2: { cellWidth: 32 },
          3: { cellWidth: 36 },
          4: { cellWidth: 20, halign: 'center' },
          5: { cellWidth: 28, halign: 'center',fontStyle: 'bold' },
          6: { cellWidth: 'auto' }
        } : {
          0: { cellWidth: 32, halign: 'center', fontStyle: 'bold' }, // Increased width to prevent date wrap
          1: { cellWidth: 35 },
          2: { cellWidth: 40 },
          3: { cellWidth: 28, halign: 'center' },
          4: { cellWidth: 28, halign: 'center' ,fontStyle: 'bold'},
          5: { cellWidth: 'auto' }
        },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        didParseCell: (cellData: any) => {
          if (cellData.section === 'body') {
            const status = cellData.row.raw.statusText;
            if (status === 'Holiday') cellData.cell.styles.textColor = PRIMARY_BLUE;
            if (status === 'Absent') cellData.cell.styles.textColor = [220, 38, 38];
          }
        },
        didDrawPage: (pageData: any) => {
          const pages = doc.internal.getNumberOfPages();
          doc.setFontSize(10);
          doc.setTextColor(148, 163, 184);
          doc.text(`DSR Report Page ${pages} • Generated by R-Space Perform Pro • Confidential`, 15, 202);
        }
      });

      // 5. SUMMARY TABLE (BOTTOM OF LAST PAGE)
      const finalY = (doc as any).lastAutoTable.finalY || 85;
      const workingDays = data.filter(d => d.statusText === 'Present').length;
      const holidays = data.filter(d => d.statusText === 'Holiday').length;
      const missingDsr = data.filter(d => d.statusText === 'Absent').length;

      (doc as any).autoTable({
        head: [['ATTENDANCE SUMMARY', 'COUNT']],
        body: [
          ['WORKING DAYS (PRESENT)', workingDays],
          ['HOLIDAYS (WEEKLY OFF)', holidays],
          ['MISSING DSR (ABSENT)', missingDsr],
          ['TOTAL CYCLE DAYS', data.length]
        ],
        startY: finalY + 10,
        margin: { left: 180 },
        tableWidth: 100,
        theme: 'grid',
        headStyles: {
          fillColor: [30, 41, 59],
          fontSize: 9,
          halign: 'center'
        },
        styles: {
          fontSize: 9,
          fontStyle: 'bold',
          cellPadding: 3
        },
        columnStyles: {
          1: { halign: 'center', cellWidth: 30 }
        }
      });

      doc.save(`RIDSYS_DSR_${employeeName}_${rangeText}.pdf`);
    } catch (error) {
      console.error("PDF Generation failed", error);
    } finally {

    }
  }

  generateOverviewPDF(
    employee: any,
    fromdate: any,
    todate: any,
    rawData: any[],
    mode: 'download' | 'preview' = 'download'
  ) {
    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a4');
      const PRIMARY_BLUE = [37, 99, 235];
      const TEXT_DARK = [30, 41, 59];
      const TEXT_MUTED = [100, 116, 139];
      const BORDER = [226, 232, 240];
      const SUCCESS = [22, 163, 74];
      const WARNING = [245, 158, 11];
      const DANGER = [220, 38, 38];

      const data = Array.isArray(rawData) ? rawData : rawData ? [rawData] : [];
      const generatedBy =
        (typeof employee === 'string' && employee.trim()) ||
        employee?.generatedBy ||
        employee?.employee_name ||
        'SYSTEM USER';
      const filteredEmployee =
        employee?.filteredEmployee ||
        data?.[0]?.assigned_to_name ||
        data?.[0]?.employee_name ||
        'ALL EMPLOYEES';
      const rangeText = this.getDateRangeLabel(new Date(fromdate), new Date(todate));

      doc.setFillColor(248, 250, 252);
      doc.rect(0, 0, 420, 297, 'F');

      // Header
      doc.setFontSize(28);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.setFont(undefined, 'bold');
      doc.text("RIDSYS", 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'normal');
      doc.text("ENTERPRISE RESOURCE PERFORMANCE SYSTEM", 15, 26);

      doc.setFontSize(22);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.text("TASK OVERVIEW REPORT", 15, 45);

      doc.setDrawColor(...PRIMARY_BLUE);
      doc.setLineWidth(1);
      doc.line(15, 50, 110, 50);

      // Metadata blocks
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(...BORDER);
      // doc.roundedRect(15, 58, 110, 24, 3, 3, 'FD');
      // doc.roundedRect(115, 58, 110, 24, 3, 3, 'FD');
      // doc.roundedRect(205, 58, 120, 24, 3, 3, 'FD');

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text("FILTER DETAILS", 20, 65);

      doc.setFontSize(11);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.text(`GENERATED BY: ${String(generatedBy).toUpperCase()}`, 20, 71);
      doc.setFont(undefined, 'normal');

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text("REPORTING PERIOD", 120, 65);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(rangeText.toUpperCase(), 120, 71);
      doc.setFont(undefined, 'normal');
      doc.text("Overview timeline", 120, 77);

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text("EXPORT METRICS", 210, 65);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(`EXPORT DATE: ${new Date().toLocaleDateString().toUpperCase()}`, 210, 71);
      doc.setFont(undefined, 'normal');
      doc.text(`TOTAL TASKS: ${data.length}`, 210, 77);


      // Main table
      const columns = [
        { header: 'OWNER', dataKey: 'assigned_from_name' },
        { header: 'ASSIGNEE', dataKey: 'assigned_to_name' },
        { header: 'PROJECT TITLE', dataKey: 'project_title' },
        { header: 'STATUS', dataKey: 'status' },
        { header: 'TASK NAME', dataKey: 'task' },
        { header: 'DESCRIPTION', dataKey: 'description' }
      ];

      (doc as any).autoTable({
        columns: columns,
        body: data,
        startY: ((doc as any).lastAutoTable?.finalY || 90) + 10,
        theme: 'grid',
        margin: { left: 15, right: 15, bottom: 18 },
        tableWidth: 'auto',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center',
          valign: 'middle',
          fontSize: 11,
          cellPadding: { top: 3, bottom: 3, left: 2, right: 2 }
        },
        styles: {
          fontSize: 10,
          cellPadding: 3,
          overflow: 'linebreak',
          textColor: [51, 65, 85],
          lineColor: BORDER,
          lineWidth: 0.1
        },
        columnStyles: {
          0: { cellWidth: 38, fontStyle: 'bold' },
          1: { cellWidth: 37 },
          2: { cellWidth: 46 },
          3: { cellWidth: 30, halign: 'center', fontStyle: 'bold' },
          4: { cellWidth: 60, halign: 'center' },
          5: { cellWidth: 60, halign: 'center' },
        },

        alternateRowStyles: { fillColor: [249, 250, 251] },
        didParseCell: (cellData: any) => {
          if (cellData.section === 'body' && cellData.column.dataKey === 'status') {
            const statusKey = this.getOverviewStatusKey(cellData.row.raw?.status);
            cellData.cell.styles.fontStyle = 'bold';
            if (statusKey === 'open') {
              cellData.cell.styles.textColor = WARNING;
            } else if (statusKey === 'in-progress') {
              cellData.cell.styles.textColor = TEXT_DARK;
            } else if (statusKey === 'completed') {
              cellData.cell.styles.textColor = SUCCESS;
            } else if (statusKey === 'closed') {
              cellData.cell.styles.textColor = PRIMARY_BLUE;
            } else if (statusKey === 'failed') {
              cellData.cell.styles.textColor = DANGER;
            }
          }
        },
        didDrawPage: () => {
          const pages = doc.internal.getNumberOfPages();
          const pageHeight = doc.internal.pageSize.getHeight();
          doc.setFontSize(10);
          doc.setTextColor(...TEXT_MUTED);
          doc.text(`Overview Report Page ${pages} • Generated by R-Space Perform Pro • Confidential`, 15, pageHeight - 8);
        }
      });

      this.finalizePdf(doc, `TASK_${generatedBy}_${rangeText}.pdf`, mode);
    } catch (error) {
      console.error("PDF Generation failed", error);
    } finally {

    }
  }

  generateReleaseOverviewPDF(
    filters: any,
    fromdate: any,
    todate: any,
    rawData: any[],
    mode: 'download' | 'preview' = 'download'
  ) {
    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a4');
      const PRIMARY_BLUE = [37, 99, 235];
      const TEXT_DARK = [30, 41, 59];
      const TEXT_MUTED = [100, 116, 139];
      const BORDER = [226, 232, 240];
      const DANGER = [220, 38, 38];

      const data = Array.isArray(rawData) ? rawData : rawData ? [rawData] : [];
      const generatedBy = filters?.generatedBy || 'SYSTEM USER';
      const filteredProject = filters?.filteredProject || 'ALL PROJECTS';
      const releaseType = filters?.releaseType || 'All';
      const fromDate = String(fromdate || '').trim();
      const toDate = String(todate || '').trim();
      const rangeText = `${fromDate} to ${toDate}`;

      const internalReleaseCount = data.filter(
        (row: any) => String(row?.release_type || '').trim().toLowerCase() === 'internal'
      ).length;
      const externalReleaseCount = data.filter(
        (row: any) => String(row?.release_type || '').trim().toLowerCase() === 'external'
      ).length;

      doc.setFillColor(248, 250, 252);
      doc.rect(0, 0, 420, 297, 'F');

      doc.setFontSize(28);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.setFont(undefined, 'bold');
      doc.text('RIDSYS', 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'normal');
      doc.text('ENTERPRISE RESOURCE PERFORMANCE SYSTEM', 15, 26);

      doc.setFontSize(22);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.text('RELEASE OVERVIEW REPORT', 15, 45);

      doc.setDrawColor(...PRIMARY_BLUE);
      doc.setLineWidth(1);
      doc.line(15, 50, 100, 50);

      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(...BORDER);
      // doc.roundedRect(15, 58, 110, 28, 3, 3, 'FD');
      // doc.roundedRect(133, 58, 110, 28, 3, 3, 'FD');
      // doc.roundedRect(251, 58, 120, 28, 3, 3, 'FD');

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text('FILTER DETAILS', 20, 65);

      doc.setFontSize(11);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.text(`GENERATED BY: ${String(generatedBy).toUpperCase()}`, 20, 71);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(...TEXT_DARK);
      doc.text(`PROJECT: ${String(filteredProject).toUpperCase()}`, 20, 77);
      doc.text(`RELEASE TYPE: ${String(releaseType).toUpperCase()}`, 20, 83);

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text('REPORTING PERIOD', 120, 65);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(rangeText.toUpperCase(), 120, 71);
      doc.setFont(undefined, 'normal');
      doc.text('Release activity timeline', 120, 77);
      doc.text(`TOTAL RELEASES: ${data.length}`, 120, 83);

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text('EXPORT METRICS', 210, 65);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(`EXPORT DATE: ${new Date().toLocaleDateString().toUpperCase()}`, 210, 71);
      doc.setFont(undefined, 'normal');
      doc.text(`INTERNAL RELEASES: ${internalReleaseCount}`, 210, 77);
      doc.text(`EXTERNAL RELEASES: ${externalReleaseCount}`, 210, 83);



      const tableData = data.map((item: any) => ({
        project_name: item.project_name || item.project_title || '-',
        title: item.title || '-',
        version: item.version || '-',
        assignee_from_name: item.assignee_from_name || '-',
        release_performance: this.getReleasePerformance(item),
        released_date: item.released_date || '-',
        tested_by_name: this.getReleaseTesterName(item),
        qc_released_date: item.closed_date ? String(item.closed_date).split('T')[0] : '-',
        company_name: item.company_name || '-',
        status: item.status || '-',
        release_type: item.release_type || '-',
        overdue_date: this.getReleaseOverdueDate(item),
        overdue_state: this.getReleaseOverdueState(item),
      }));

      (doc as any).autoTable({
        columns: [
          { header: 'PROJECT', dataKey: 'project_name' },
          { header: 'TITLE', dataKey: 'title' },
          { header: 'VERSION', dataKey: 'version' },
          { header: 'WORKED BY / RELEASED BY', dataKey: 'assignee_from_name' },
          { header: 'RELEASE PERFORMANCE', dataKey: 'release_performance' },
          { header: 'RELEASE DATE', dataKey: 'released_date' },
          { header: 'TESTED BY', dataKey: 'tested_by_name' },
          { header: 'QC RELEASED DATE', dataKey: 'qc_released_date' },
          { header: 'CLIENT', dataKey: 'company_name' },
          { header: 'STATUS', dataKey: 'status' },
          { header: 'RELEASE TYPE', dataKey: 'release_type' },
          { header: 'OVERDUE DATE', dataKey: 'overdue_date' },
        ],
        body: tableData,
        startY: ((doc as any).lastAutoTable?.finalY || 94) + 10,
        theme: 'grid',
        margin: { left: 15, right: 15, bottom: 18 },
        tableWidth: 'auto',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: 255,
          fontStyle: 'bold',
          halign: 'center',
          valign: 'middle',
          fontSize: 9,
          cellPadding: { top: 3, bottom: 3, left: 2, right: 2 }
        },
        styles: {
          fontSize: 9,
          cellPadding: 2.5,
          overflow: 'linebreak',
          textColor: TEXT_DARK,
          lineColor: BORDER,
          lineWidth: 0.1
        },
        columnStyles: {
          0: { cellWidth: 24 },
          1: { cellWidth: 29 },
          2: { cellWidth: 13, halign: 'center', fontStyle: 'bold' },
          3: { cellWidth: 23, halign: 'center', fontStyle: 'bold' },
          4: { cellWidth: 20, halign: 'center', fontStyle: 'bold' },
          5: { cellWidth: 20, halign: 'center' },
          6: { cellWidth: 22, fontStyle: 'bold' },
          7: { cellWidth: 20, halign: 'center' },
          8: { cellWidth: 20, halign: 'center' },
          9: { cellWidth: 19, halign: 'center', fontStyle: 'bold' },
          10: { cellWidth: 17, halign: 'center' },
          11: { cellWidth: 20, halign: 'center', fontStyle: 'bold' },
        },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        didParseCell: (cellData: any) => {
          if (
            cellData.section === 'body' &&
            cellData.column.dataKey === 'release_performance' &&
            cellData.row.raw?.release_performance !== '-'
          ) {
            cellData.cell.styles.fontStyle = 'bold';
            cellData.cell.styles.textColor = this.getReleasePerformanceTextColor(cellData.row.raw?.release_performance);
          }

          if (cellData.section === 'body' && cellData.column.dataKey === 'status') {
            cellData.cell.styles.fontStyle = 'bold';
            cellData.cell.styles.textColor = this.getReleaseStatusTextColor(cellData.row.raw?.status);
          }

          if (
            cellData.section === 'body' &&
            cellData.column.dataKey === 'overdue_date' &&
            cellData.row.raw?.overdue_date !== '-'
          ) {
            cellData.cell.styles.fontStyle = 'bold';
            cellData.cell.styles.textColor = this.getReleaseOverdueTextColor(cellData.row.raw?.overdue_state);
          }
        },
        didDrawPage: () => {
          const pages = doc.internal.getNumberOfPages();
          const pageHeight = doc.internal.pageSize.getHeight();
          doc.setFontSize(9);
          doc.setTextColor(...TEXT_MUTED);
          doc.text(`Release Overview Report Page ${pages} • Generated by R-Space Perform Pro • Confidential`, 15, pageHeight - 8);
        }
      });

      this.finalizePdf(doc, `RELEASE_REPORT_${fromDate}_to_${toDate}.pdf`, mode);

    } catch (error) {
      console.error('Release PDF Generation failed', error);
    }
  }

  generateAttendancePDF(empId: any, fromdate: any, todate: any, rawData: any[]) {

    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a4');

      const PRIMARY_BLUE = [37, 99, 235];
      const TEXT_DARK = [30, 41, 59];

      const employeeName = rawData?.length ? rawData[0].employee_name : 'Employee';

      // ===============================
      // 1️⃣ HEADER BRANDING
      // ===============================
      doc.setFontSize(28);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.setFont(undefined, 'bold');
      doc.text("RIDSYS", 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(148, 163, 184);
      doc.setFont(undefined, 'normal');
      doc.text("ENTERPRISE RESOURCE PERFORMANCE SYSTEM", 15, 26);

      // ===============================
      // 2️⃣ MAIN TITLE
      // ===============================
      doc.setFontSize(22);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.text("EMPLOYEE ATTENDANCE REPORT", 15, 45);

      doc.setDrawColor(...PRIMARY_BLUE);
      doc.setLineWidth(1);
      doc.line(15, 50, 110, 50);

      // ===============================
      // 3️⃣ EMPLOYEE + DATE INFO
      // ===============================
      doc.setFontSize(10);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.text(`EMPLOYEE: ${employeeName.toUpperCase()}`, 15, 60);

      doc.setFont(undefined, 'normal');
      doc.text(`PERIOD: ${fromdate} TO ${todate}`, 15, 66);

      doc.text(`EXPORT DATE: ${new Date().toLocaleDateString()}`, 220, 60);
      doc.text(`TOTAL DAYS: ${rawData.length}`, 220, 66);

      // ===============================
      // 4️⃣ ATTENDANCE TABLE
      // ===============================

      const columns = [
        { header: 'DATE', dataKey: 'attendance_date' },
        { header: 'DAY', dataKey: 'day' },
        { header: 'PUNCH TIME', dataKey: 'punch_time' },
        { header: 'WORKED HRS', dataKey: 'worked_hrs' },
        { header: 'STATUS', dataKey: 'status' },
        { header: 'REMARKS', dataKey: 'remarks' }
      ];

      (doc as any).autoTable({
        columns: columns,
        body: rawData,
        startY: 75,
        theme: 'grid',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center',
          fontSize: 10
        },
        styles: {
          fontSize: 10,
          cellPadding: 4,
          overflow: 'linebreak',
          textColor: [51, 65, 85],
          lineColor: [226, 232, 240],
          lineWidth: 0.1
        },
        columnStyles: {
          0: { cellWidth: 30, halign: 'center' },
          1: { cellWidth: 40, halign: 'center' },
          2: { cellWidth: 50, halign: 'center' },
          3: { cellWidth: 30, halign: 'center' },
          4: { cellWidth: 45, halign: 'center' },
          5: { cellWidth: 'auto', halign: 'center' }
        },
        alternateRowStyles: { fillColor: [249, 250, 251] },

        didParseCell: (cellData: any) => {
          if (cellData.section === 'body' && cellData.column.dataKey === 'status') {

            const status = cellData.cell.raw;

            if (status === 'Present')
              cellData.cell.styles.textColor = [22, 163, 74];

            if (status === 'Absent')
              cellData.cell.styles.textColor = [220, 38, 38];

            if (status === 'Late')
              cellData.cell.styles.textColor = [234, 88, 12];
          }
        },

        didDrawPage: () => {
          const pageCount = doc.internal.getNumberOfPages();
          doc.setFontSize(9);
          doc.setTextColor(148, 163, 184);
          doc.text(
            `Attendance Report • Page ${pageCount} • Generated by RIDSYS ERP • Confidential`,
            15,
            202
          );
        }
      });

      // ===============================
      // 5️⃣ SUMMARY
      // ===============================

      const present = rawData.filter(d => d.status === 'Present').length;
      const absent = rawData.filter(d => d.status === 'Absent').length;
      const late = rawData.filter(d => d.status === 'Late').length;

      const finalY = (doc as any).lastAutoTable.finalY || 75;

      (doc as any).autoTable({
        head: [['ATTENDANCE SUMMARY', 'COUNT']],
        body: [
          ['PRESENT DAYS', present],
          ['ABSENT DAYS', absent],
          ['LATE DAYS', late],
          ['TOTAL DAYS', rawData.length]
        ],
        startY: finalY + 10,
        margin: { left: 180 },
        tableWidth: 100,
        theme: 'grid',
        headStyles: {
          fillColor: [30, 41, 59],
          textColor: [255, 255, 255],
          fontSize: 9,
          halign: 'center'
        },
        styles: {
          fontSize: 9,
          fontStyle: 'bold',
          cellPadding: 3
        },
        columnStyles: {
          1: { halign: 'center', cellWidth: 30 }
        }
      });

      doc.save(`RIDSYS_Attendance_${employeeName}_${fromdate}_to_${todate}.pdf`);

    } catch (error) {
      console.error("Attendance PDF generation failed", error);
    }
  }


  private getDateRangeLabel(start: Date, end: Date): string {
    if (!start || !end) return '';
    const sameMonthYear = start.getMonth() === end.getMonth() && start.getFullYear() === end.getFullYear();

    if (sameMonthYear) {
      return `${start.getDate()}–${end.getDate()} ${start.toLocaleString('en-US', { month: 'long', year: 'numeric' })}`;
    }
    const startLabel = start.toLocaleDateString('en-US', { day: '2-digit', month: 'short', year: 'numeric' });
    const endLabel = end.toLocaleDateString('en-US', { day: '2-digit', month: 'short', year: 'numeric' });
    return `${startLabel} – ${endLabel}`;
  }

  private getInputDateRangeText(fromdate: any, todate: any): string {
    const fromDate = this.formatInputDateToYMD(fromdate);
    const toDate = this.formatInputDateToYMD(todate);

    if (fromDate && toDate) {
      return `${fromDate} to ${toDate}`;
    }

    return fromDate || toDate || '';
  }

  private formatInputDateToYMD(value: any): string {
    if (!value) {
      return '';
    }

    if (typeof value === 'string') {
      const trimmed = value.trim();
      const ymdMatch = /^(\d{4})-(\d{2})-(\d{2})/.exec(trimmed);
      if (ymdMatch) {
        return `${ymdMatch[1]}-${ymdMatch[2]}-${ymdMatch[3]}`;
      }
    }

    const date = new Date(value);
    if (Number.isNaN(date.getTime())) {
      return String(value);
    }

    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(
      date.getDate()
    ).padStart(2, '0')}`;
  }

  private formatDate(date: Date): string {
    const d = date.getDate().toString().padStart(2, '0');
    const m = (date.getMonth() + 1).toString().padStart(2, '0');
    const y = date.getFullYear();
    return `${d}-${m}-${y}`;
  }

  private getOverviewStatusKey(status: any): string {
    const normalized = String(status ?? '')
      .trim()
      .toLowerCase()
      .replace(/[_\s]+/g, '-');

    if (normalized === 'closed') return 'closed';
    if (normalized === 'in-progress' || normalized === 'inprogress') return 'in-progress';
    if (normalized === 'open') return 'open';
    if (normalized === 'completed' || normalized === 'complete') return 'completed';
    if (normalized === 'failed' || normalized === 'fail') return 'failed';
    return normalized;
  }

  private getReleaseStatusKey(status: any): string {
    const normalized = String(status ?? '')
      .trim()
      .toLowerCase()
      .replace(/[_\s]+/g, '-');

    if (normalized === 'open') return 'open';
    if (normalized === 'in-progress' || normalized === 'inprogress') return 'in-progress';
    if (normalized === 'to-be-tested' || normalized === 'tobe-tested' || normalized === 'to-be-test' || normalized === 'to-be-tested') return 'to-be-tested';
    if (normalized === 'in-review' || normalized === 'inreview') return 'in-review';
    if (normalized === 'completed' || normalized === 'complete') return 'completed';
    if (normalized === 'failed' || normalized === 'fail') return 'failed';
    return normalized;
  }

  private getReleaseStatusTextColor(status: any): number[] {
    const statusKey = this.getReleaseStatusKey(status);

    if (statusKey === 'open') return [71, 85, 105];
    if (statusKey === 'upcoming-release') return [219, 39, 119];
    if (statusKey === 'on-hold') return [234, 88, 12];
    if (statusKey === 'in-progress') return [37, 99, 235];
    if (statusKey === 'to-be-tested') return [124, 58, 237];
    if (statusKey === 'rejected') return [202, 138, 4];
    if (statusKey === 'pass' || statusKey === 'passed') return [22, 163, 74];
    if (statusKey === 'failed') return [220, 38, 38];
    if (statusKey === 'in-review') return [147, 51, 234];
    if (statusKey === 'approved') return [5, 150, 105];
    if (statusKey === 'completed') return [21, 128, 61];
    if (statusKey === 'cancelled') return [185, 28, 28];

    return [30, 41, 59];
  }

  private isReleaseOverdue(release: any): boolean {
    if (!this.isUpcomingRelease(release)) {
      return false;
    }

    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);
    return daysUntilRelease !== null && daysUntilRelease < 0;
  }

  private getReleaseOverdueDate(release: any): string {
    const overdueState = this.getReleaseOverdueState(release);
    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);

    if (overdueState === 'overdue') {
      return `${release?.released_date ?? ''}`.trim() || '-';
    }

    if (overdueState === 'high-warning') {
      return daysUntilRelease === 0 ? 'Due Today' : 'Due Tomorrow';
    }

    if (overdueState === 'warning') {
      return `Due in ${daysUntilRelease} days`;
    }

    return '-';
  }

  private getReleaseOverdueState(release: any): 'none' | 'warning' | 'high-warning' | 'overdue' {
    if (!this.isUpcomingRelease(release)) {
      return 'none';
    }

    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);

    if (daysUntilRelease === null) {
      return 'none';
    }

    if (daysUntilRelease < 0) {
      return 'overdue';
    }

    if (daysUntilRelease <= 1) {
      return 'high-warning';
    }

    return 'warning';
  }

  private getReleaseOverdueTextColor(state: any): number[] {
    if (state === 'warning') return [217, 119, 6];
    if (state === 'high-warning') return [234, 88, 12];
    if (state === 'overdue') return [220, 38, 38];
    return [30, 41, 59];
  }

  private getReleaseTesterName(release: any): string {
    if (this.isUpcomingRelease(release)) {
      return '-';
    }

    return `${release?.assignee_to_name ?? ''}`.trim() || '-';
  }

  private isUpcomingRelease(release: any): boolean {
    const status = String(release?.status || '').trim().toLowerCase().replace(/[-_\s]+/g, '-');
    return status === 'upcoming-release';
  }

  private getReleasePerformance(release: any): string {
    if (this.isReleasePerformancePending(release)) {
      return 'Pending';
    }

    const plannedDate = this.parseReleaseDate(`${release?.planned_date ?? ''}`.trim());
    const releaseDate = this.parseReleaseDate(`${release?.released_date ?? ''}`.trim());

    if (!plannedDate || !releaseDate) {
      return '-';
    }

    plannedDate.setHours(0, 0, 0, 0);
    releaseDate.setHours(0, 0, 0, 0);

    if (releaseDate.getTime() < plannedDate.getTime()) {
      return 'Very Good';
    }

    if (releaseDate.getTime() === plannedDate.getTime()) {
      return 'Good';
    }

    return 'Poor';
  }

  private getReleasePerformanceTextColor(performance: any): number[] {
    const key = String(performance || '').trim().toLowerCase();
    if (key === 'very good') return [22, 163, 74];
    if (key === 'good') return [37, 99, 235];
    if (key === 'poor') return [220, 38, 38];
    if (key === 'pending') return [71, 85, 105];
    return [30, 41, 59];
  }

  private isReleasePerformancePending(release: any): boolean {
    const statusKey = this.getReleaseStatusKey(release?.status);
    return statusKey === 'upcoming-release';
  }

  private getDaysUntilRelease(releasedDate: string | null | undefined): number | null {
    const rawValue = `${releasedDate ?? ''}`.trim();
    if (!rawValue) {
      return null;
    }

    if (rawValue.toLowerCase() === 'overdue') {
      return 0;
    }

    const releaseDate = this.parseReleaseDate(rawValue);
    if (!releaseDate) {
      return null;
    }

    releaseDate.setHours(0, 0, 0, 0);

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    return Math.ceil((releaseDate.getTime() - today.getTime()) / 86400000);
  }

  private parseReleaseDate(value: string): Date | null {
    const normalized = value.trim();
    const ymdParts = normalized.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})$/);

    if (ymdParts) {
      const year = Number(ymdParts[1]);
      const month = Number(ymdParts[2]);
      const day = Number(ymdParts[3]);
      const parsed = new Date(year, month - 1, day);
      return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    const dmyParts = normalized.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{4})$/);

    if (dmyParts) {
      const day = Number(dmyParts[1]);
      const month = Number(dmyParts[2]);
      const year = Number(dmyParts[3]);
      const parsed = new Date(year, month - 1, day);
      return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    const parsed = new Date(normalized);
    return Number.isNaN(parsed.getTime()) ? null : parsed;
  }

  getProcessedData(fromDate: any, toDate: any, rawData: any): DSRRecord[] {
    const start = new Date(fromDate);
    const end = new Date(toDate);
    const result: DSRRecord[] = [];
    console.log("RAWDATA   =", rawData);

    for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
      const formatted = this.formatDate(d);
      const existing = rawData.find((item: any) => {
        console.log(item.date, formatted);
        const date = new Date(item.date);
        return this.formatDate(date) === formatted;
      });

      if (existing) {
        result.push({ ...existing, date: formatted, statusText: 'Present' });
      } else {
        const isSunday = d.getDay() === 0;
        result.push({
          id: Math.random(),
          date: formatted,
          employee_name: "PRASADARAO GAJULA",
          project_title: "N/A",
          sub_task: isSunday ? "Holiday - Weekly Off" : "Not DSR Entered",
          worked_hours: isSunday ? "-" : "0 Hours",
          completion_percentage: 0,
          task: isSunday ? "Holiday" : "Absent",
          comments: isSunday ? "Sunday - Weekly Off" : "Log Missing: No entry submitted for this date.",
          statusText: isSunday ? "Holiday" : "Absent"
        });
      }
    }
    return result;
  }

  generateTicketsPDF(
    filters: any,
    fromdate: any,
    todate: any,
    rawData: any[],
    mode: 'download' | 'preview' = 'download'
  ) {
    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a4');

      const PRIMARY_BLUE = [37, 99, 235];
      const TEXT_DARK = [30, 41, 59];
      const TEXT_MUTED = [100, 116, 139];
      const BORDER = [226, 232, 240];
      const SUCCESS = [22, 163, 74];
      const WARNING = [245, 158, 11];
      const PURPLE = [124, 58, 237];
      const RED = [250, 35, 35];

      const data = Array.isArray(rawData) ? rawData : rawData ? [rawData] : [];
      const generatedBy = filters?.generatedBy || 'SYSTEM USER';
      const rangeText = this.getInputDateRangeText(fromdate, todate);

      // Background
      doc.setFillColor(248, 250, 252);
      doc.rect(0, 0, 420, 297, 'F');

      // Header
      doc.setFontSize(28);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.setFont(undefined, 'bold');
      doc.text("RIDSYS", 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'normal');
      doc.text("SUPPORT TICKET MANAGEMENT SYSTEM", 15, 26);

      doc.setFontSize(22);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.text("TICKET REPORT", 15, 45);

      doc.setDrawColor(...PRIMARY_BLUE);
      doc.setLineWidth(1);
      doc.line(15, 50, 95, 50);

      // Metadata blocks
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(...BORDER);

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text("FILTER DETAILS", 20, 65);

      doc.setFontSize(11);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.text(`GENERATED BY: ${String(generatedBy).toUpperCase()}`, 20, 71);
      doc.setFont(undefined, 'normal');

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text("REPORTING PERIOD", 120, 65);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(rangeText.toUpperCase(), 120, 71);
      doc.setFont(undefined, 'normal');

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text("EXPORT METRICS", 210, 65);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(`EXPORT DATE: ${new Date().toLocaleDateString().toUpperCase()}`, 210, 71);
      doc.setFont(undefined, 'normal');
      doc.text(`TOTAL TICKETS: ${data.length}`, 210, 77);

      // ✅ Simplified Tickets Table - Removed unnecessary columns
      const columns = [
        { header: 'TICKET', dataKey: 'code' },
        { header: 'TITLE', dataKey: 'ticket_name' },
        { header: 'CLIENT', dataKey: 'company_name' },
        { header: 'ASSIGNEE', dataKey: 'assigned_to_name' },
        { header: 'STATUS', dataKey: 'status' },
        { header: 'DESCRIPTION', dataKey: 'description' }
      ];

      (doc as any).autoTable({
        columns: columns,
        body: data.map((ticket: any) => ({
          code: ticket.code || '-',
          ticket_name: ticket.ticket_name || '-',
          company_name: ticket.company_name || '-',
          assigned_to_name: ticket.assigned_to_name || '-',
          status: this.getTicketStatusLabel(ticket.status),
          // ✅ Don't truncate description - let it wrap
          description: ticket.description || 'No description'
        })),
        startY: ((doc as any).lastAutoTable?.finalY || 90) + 10,
        theme: 'grid',
        margin: { left: 15, right: 15, bottom: 18 },
        tableWidth: 'auto',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center',
          valign: 'middle',
          fontSize: 10,
          cellPadding: { top: 3, bottom: 3, left: 2, right: 2 }
        },
        styles: {
          fontSize: 9,
          cellPadding: 3,
          overflow: 'linebreak', // ✅ Allow text to break to next line
          textColor: TEXT_DARK,
          lineColor: BORDER,
          lineWidth: 0.1,
          halign: 'left',
          valign: 'top' // ✅ Align to top for multi-line cells
        },
        columnStyles: {
          0: { cellWidth: 28, fontStyle: 'bold', halign: 'center' },     // Code
          1: { cellWidth: 45, fontStyle: 'bold' },                       // Ticket
          2: { cellWidth: 40 },                                          // Client
          3: { cellWidth: 42 },                                          // Assignee
          4: { cellWidth: 32, halign: 'center', fontStyle: 'bold' },    // Status
          5: { cellWidth: 90 }                                           // Description - Full width
        },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        didParseCell: (cellData: any) => {
          // ✅ Status column styling
          if (cellData.section === 'body' && cellData.column.dataKey === 'status') {
            const status = cellData.row.raw?.status;
            cellData.cell.styles.fontStyle = 'bold';

            if (status === 'In-Progress') {
              cellData.cell.styles.textColor = PRIMARY_BLUE;
            } else if (status === 'To-be-Tested') {
              cellData.cell.styles.textColor = WARNING;
            } else if (status === 'Delayed') {
              cellData.cell.styles.textColor = PURPLE;
            } else if (status === 'Closed') {
              cellData.cell.styles.textColor = TEXT_MUTED;
            } else if (status === 'Cancelled') {
              cellData.cell.styles.textColor = RED;
            } else if (status === 'Approved') {
              cellData.cell.styles.textColor = SUCCESS;
            } else if (status === 'Completed') {
              cellData.cell.styles.textColor = SUCCESS;
            } else if (status === 'Rejected') {
              cellData.cell.styles.textColor = RED;
            } else if (status === 'Failed') {
              cellData.cell.styles.textColor = RED;
            } else if (status === 'Passed') {
              cellData.cell.styles.textColor = SUCCESS;
            }
          }

          // ✅ Description column - ensure it wraps properly
          if (cellData.section === 'body' && cellData.column.dataKey === 'description') {
            cellData.cell.styles.halign = 'left';
            cellData.cell.styles.valign = 'top';
          }
        },
        didDrawPage: () => {
          const pages = doc.internal.getNumberOfPages();
          const pageHeight = doc.internal.pageSize.getHeight();
          doc.setFontSize(10);
          doc.setTextColor(...TEXT_MUTED);
          doc.text(`Ticket Report Page ${pages} • Generated by R-Space Perform Pro • Confidential`, 15, pageHeight - 8);
        }
      });

      this.finalizePdf(doc, `TICKETS_REPORT_${rangeText}.pdf`, mode);
    } catch (error) {
      console.error("PDF Generation failed", error);
    }
  }

  private getTicketStatusLabel(status: any): string {
    const map: any = {
      0: 'Open',
      1: 'In-Progress',
      2: 'To-be-Tested',
      3: 'Delayed',
      4: 'Closed',
      5: 'Cancelled',
      6: 'Approved',
      7: 'Completed',
      8: 'Rejected',
      9: 'Failed',
      10: 'Passed'
    };
    return map[Number(status)] || '-';
  }
}
