import { Injectable } from '@angular/core';
interface DSRRecord {
  id: number;
  date: string;
  employee_name: string;
  project_title: string;
  version?: string;
  start_date?: string;
  end_date?: string;
  sub_task: string;
  worked_hours: string;
  completion_percentage: number;
  task: string;
  comments: string;
  statusText?: string;
}
interface ReleaseOverviewExportSection {
  departmentName: string;
  managerName?: string;
  releases: any[];
}
type ReleasePerformanceState = 'none' | 'excellent' | 'very-good' | 'good' | 'poor';
@Injectable({
  providedIn: 'root'
})
export class PdfService {

  constructor() { }

  private finalizePdf(doc: any, filename: string, mode: 'download' | 'preview' = 'download'): void {
    if (mode === 'preview') {
      const previewUrl = doc.output('bloburl');
      window.open(previewUrl, '_blank', 'noopener');
      return;
    }

    doc.save(filename);
  }

  generateDSRPdf(
    employeeName: string,
    monthLabel: string,
    data: any[]
  ): void {
    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a3');

      const PRIMARY_BLUE = [37, 99, 235];
      const TEXT_DARK = [30, 41, 59];

      /* HEADER */
      doc.setFontSize(28);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.setFont(undefined, 'bold');
      doc.text('RIDSYS', 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(148, 163, 184);
      doc.text('ENTERPRISE RESOURCE PERFORMANCE SYSTEM', 15, 26);

      /* TITLE */
      doc.setFontSize(22);
      doc.setTextColor(...TEXT_DARK);
      doc.text('EMPLOYEE DSR REPORT', 15, 45);

      doc.setDrawColor(...PRIMARY_BLUE);
      doc.setLineWidth(1);
      doc.line(15, 50, 80, 50);

      /* META */
      doc.setFontSize(11);
      doc.text(employeeName, 15, 66);
      doc.text(monthLabel.toUpperCase(), 120, 66);
      doc.text(`TOTAL LOGS: ${data.length}`, 220, 66);

      /* TABLE */
      (doc as any).autoTable({
        startY: 85,
        theme: 'grid',
        headStyles: {
          fillColor: [30, 41, 59],
          textColor: 255,
          fontStyle: 'bold',
          halign: 'center',
        },
        styles: {
          fontSize: 11,
          cellPadding: 6,
          overflow: 'linebreak',
          textColor: [51, 65, 85],
        },
        columns: [
          { header: 'DATE', dataKey: 'date' },
          { header: 'PROJECT', dataKey: 'project_title' },
          { header: 'SUB TASK', dataKey: 'sub_task' },
          { header: 'HOURS', dataKey: 'worked_hours' },
          { header: '%', dataKey: 'completion_percentage' },
          { header: 'REMARKS', dataKey: 'comments' },
        ],
        body: data,
        didDrawPage: () => {
          const pages = doc.internal.getNumberOfPages();
          doc.setFontSize(8);
          doc.setTextColor(148, 163, 184);
          doc.text(
            `DSR Page ${pages} • Generated by RIDSYS • Confidential`,
            15,
            202
          );
        },
      });

      doc.save(`DSR_${employeeName}_${monthLabel}.pdf`);
    } finally {

    }
  }


  generatePDF(employee: any, fromdate: any, todate: any, rawData: any[]) {

    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a4');
      const PRIMARY_BLUE = [37, 99, 235]; // bg-blue-600
      const TEXT_DARK = [30, 41, 59]; // slate-900

      const data = (Array.isArray(rawData) ? rawData : rawData ? [rawData] : []).map((item: any) => ({
        ...item,
        version: item?.version || '-',
        start_date: item?.start_date || '-',
        end_date: item?.end_date || '-',
        statusText: item?.statusText || 'Present'
      }));
      const isAllEmployeeExport = employee?.id === 0;
      const employeeName = employee?.id === 0
        ? 'All Employee'
        : employee?.employee_name || 'Employee';
      const employeePosition = employee?.position || 'All Employee';

      // 1. TOP HEADER (BRANDING)
      doc.setFontSize(28);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.setFont(undefined, 'bold');
      doc.text("RIDSYS", 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(148, 163, 184);
      doc.setFont(undefined, 'normal');
      doc.text("ENTERPRISE RESOURCE PERFORMANCE SYSTEM", 15, 26);

      // 2. MAIN TITLE SECTION
      doc.setFontSize(22);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.text("EMPLOYEE DSR REPORT", 15, 45);

      doc.setDrawColor(...PRIMARY_BLUE);
      doc.setLineWidth(1);
      doc.line(15, 50, 80, 50);

      // 3. METADATA GRID
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.setFont(undefined, 'bold');
      doc.text("EMPLOYEE DETAILS", 15, 60);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(employeeName.toUpperCase(), 15, 66);
      doc.setFont(undefined, 'normal');
      doc.text(`${employeePosition.toUpperCase()}`, 15, 71);

      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.setFont(undefined, 'bold');
      doc.text("REPORTING PERIOD", 120, 60);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      const rangeText = this.getDateRangeLabel(new Date(fromdate), new Date(todate));
      doc.text(rangeText.toUpperCase(), 120, 66);
      doc.setFont(undefined, 'normal');
      doc.text("Activity Log Output", 120, 71);

      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.setFont(undefined, 'bold');
      doc.text("EXPORT METRICS", 220, 60);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(`DATE: ${new Date().toLocaleDateString().toUpperCase()}`, 220, 66);
      doc.setFont(undefined, 'normal');
      doc.text(`TOTAL LOGS: ${data.length}`, 220, 71);

      // 4. MAIN DATA TABLE
      const columns = [
        { header: 'DATE', dataKey: 'date' },
        ...(isAllEmployeeExport ? [{ header: 'EMPLOYEE NAME', dataKey: 'employee_name' }] : []),
        { header: 'PROJECT TITLE', dataKey: 'project_title' },
        // { header: 'SUB TASK', dataKey: 'sub_task' },
        { header: 'VERSION', dataKey: 'version' },
        { header: 'START DATE', dataKey: 'start_date' },
        { header: 'END DATE', dataKey: 'end_date' },
        { header: 'TASK', dataKey: 'task' },
        { header: 'WORKED HRS', dataKey: 'worked_hours' },
        { header: 'PERCENTAGE', dataKey: 'completion_percentage' },
        { header: 'DETAILED REMARKS / TECHNICAL LOGS', dataKey: 'comments' }
      ];

      (doc as any).autoTable({
        columns: columns,
        body: data,
        startY: 85,
        theme: 'grid',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center',
          valign: 'middle',
          fontSize: 10,
          cellPadding: { top: 4, bottom: 4, left: 2, right: 2 },
          minCellWidth: 'wrap' // Header text won't wrap
        },
        styles: {
          // fontSize: isAllEmployeeExport ? 10 : 11,
          // cellPadding: 6,
          fontSize: isAllEmployeeExport ? 8 : 9,
          cellPadding: { top: 4, bottom: 4, left: 2, right: 2 },
          overflow: 'linebreak',
          textColor: [51, 65, 85],
          lineColor: [226, 232, 240],
          lineWidth: 0.1
        },
        // columnStyles: isAllEmployeeExport ? {
        //   0: { cellWidth: 28, halign: 'center', fontStyle: 'bold' },
        //   1: { cellWidth: 38, fontStyle: 'bold' },
        //   2: { cellWidth: 32 },
        //   3: { cellWidth: 36 },
        //   4: { cellWidth: 20, halign: 'center' },
        //   5: { cellWidth: 28, halign: 'center', fontStyle: 'bold' },
        //   6: { cellWidth: 'auto' }
        // } : {
        //   0: { cellWidth: 32, halign: 'center', fontStyle: 'bold' }, // Increased width to prevent date wrap
        //   1: { cellWidth: 35 },
        //   2: { cellWidth: 40 },
        //   3: { cellWidth: 28, halign: 'center' },
        //   4: { cellWidth: 28, halign: 'center', fontStyle: 'bold' },
        //   5: { cellWidth: 'auto' }
        // },
        columnStyles: {
          date: { cellWidth: 22, halign: 'center', fontStyle: 'bold' },
          employee_name: { cellWidth: 32, fontStyle: 'bold' },
          project_title: { cellWidth: 30 },
          version: { cellWidth: 22, halign: 'center' },
          start_date: { cellWidth: 24, halign: 'center' },
          end_date: { cellWidth: 24, halign: 'center' },
          task: { cellWidth: isAllEmployeeExport ? 34 : 45 },
          worked_hours: { cellWidth: 20, halign: 'center' },
          completion_percentage: { cellWidth: 24, halign: 'center', fontStyle: 'bold' },
          comments: { cellWidth: 'auto' }
        },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        didParseCell: (cellData: any) => {
          if (cellData.section === 'body') {
            const status = cellData.row.raw.statusText;
            if (status === 'Holiday') cellData.cell.styles.textColor = PRIMARY_BLUE;
            if (status === 'Absent') cellData.cell.styles.textColor = [220, 38, 38];
          }
        },
        didDrawPage: (pageData: any) => {
          const pages = doc.internal.getNumberOfPages();
          doc.setFontSize(10);
          doc.setTextColor(148, 163, 184);
          doc.text(`DSR Report Page ${pages} • Generated by DSR Perform Pro • Confidential`, 15, 202);
        }
      });

      // 5. SUMMARY TABLE (BOTTOM OF LAST PAGE)
      const finalY = (doc as any).lastAutoTable.finalY || 85;
      const workingDays = data.filter(d => d.statusText === 'Present').length;
      const holidays = data.filter(d => d.statusText === 'Holiday').length;
      const missingDsr = data.filter(d => d.statusText === 'Absent').length;

      (doc as any).autoTable({
        head: [['ATTENDANCE SUMMARY', 'COUNT']],
        body: [
          ['WORKING DAYS (PRESENT)', workingDays],
          ['HOLIDAYS (WEEKLY OFF)', holidays],
          ['MISSING DSR (ABSENT)', missingDsr],
          ['TOTAL CYCLE DAYS', data.length]
        ],
        startY: finalY + 10,
        margin: { left: 180 },
        tableWidth: 100,
        theme: 'grid',
        headStyles: {
          fillColor: [30, 41, 59],
          fontSize: 9,
          halign: 'center'
        },
        styles: {
          fontSize: 9,
          fontStyle: 'bold',
          cellPadding: 3
        },
        columnStyles: {
          1: { halign: 'center', cellWidth: 30 }
        }
      });

      doc.save(`RIDSYS_DSR_${employeeName}_${rangeText}.pdf`);
    } catch (error) {
      console.error("PDF Generation failed", error);
    } finally {

    }
  }

  generateOverviewPDF(
    employee: any,
    fromdate: any,
    todate: any,
    rawData: any[],
    mode: 'download' | 'preview' = 'download'
  ) {
    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a4');
      const PRIMARY_BLUE = [37, 99, 235];
      const TEXT_DARK = [30, 41, 59];
      const TEXT_MUTED = [100, 116, 139];
      const BORDER = [226, 232, 240];
      const SUCCESS = [22, 163, 74];
      const WARNING = [245, 158, 11];
      const DANGER = [220, 38, 38];

      const data = Array.isArray(rawData) ? rawData : rawData ? [rawData] : [];
      const generatedBy =
        (typeof employee === 'string' && employee.trim()) ||
        employee?.generatedBy ||
        employee?.employee_name ||
        'SYSTEM USER';
      const filteredEmployee =
        employee?.filteredEmployee ||
        data?.[0]?.assigned_to_name ||
        data?.[0]?.employee_name ||
        'ALL EMPLOYEES';
      const rangeText = this.getDateRangeLabel(new Date(fromdate), new Date(todate));

      doc.setFillColor(248, 250, 252);
      doc.rect(0, 0, 420, 297, 'F');

      // Header
      doc.setFontSize(28);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.setFont(undefined, 'bold');
      doc.text("RIDSYS", 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'normal');
      doc.text("ENTERPRISE RESOURCE PERFORMANCE SYSTEM", 15, 26);

      doc.setFontSize(22);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.text("TASK OVERVIEW REPORT", 15, 45);

      doc.setDrawColor(...PRIMARY_BLUE);
      doc.setLineWidth(1);
      doc.line(15, 50, 110, 50);

      // Metadata blocks
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(...BORDER);
      // doc.roundedRect(15, 58, 110, 24, 3, 3, 'FD');
      // doc.roundedRect(115, 58, 110, 24, 3, 3, 'FD');
      // doc.roundedRect(205, 58, 120, 24, 3, 3, 'FD');

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text("FILTER DETAILS", 20, 65);

      doc.setFontSize(11);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.text(`GENERATED BY: ${String(generatedBy).toUpperCase()}`, 20, 71);
      doc.setFont(undefined, 'normal');

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text("REPORTING PERIOD", 120, 65);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(rangeText.toUpperCase(), 120, 71);
      doc.setFont(undefined, 'normal');
      doc.text("Overview timeline", 120, 77);

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text("EXPORT METRICS", 210, 65);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(`EXPORT DATE: ${new Date().toLocaleDateString().toUpperCase()}`, 210, 71);
      doc.setFont(undefined, 'normal');
      doc.text(`TOTAL TASKS: ${data.length}`, 210, 77);


      // Main table
      const columns = [
        { header: 'OWNER', dataKey: 'assigned_from_name' },
        { header: 'ASSIGNEE', dataKey: 'assigned_to_name' },
        { header: 'PROJECT TITLE', dataKey: 'project_title' },
        { header: 'STATUS', dataKey: 'status' },
        { header: 'TASK NAME', dataKey: 'task' },
        { header: 'DESCRIPTION', dataKey: 'description' }
      ];

      (doc as any).autoTable({
        columns: columns,
        body: data,
        startY: ((doc as any).lastAutoTable?.finalY || 90) + 10,
        theme: 'grid',
        margin: { left: 15, right: 15, bottom: 18 },
        tableWidth: 'auto',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center',
          valign: 'middle',
          fontSize: 11,
          cellPadding: { top: 3, bottom: 3, left: 2, right: 2 }
        },
        styles: {
          fontSize: 10,
          cellPadding: 3,
          overflow: 'linebreak',
          textColor: [51, 65, 85],
          lineColor: BORDER,
          lineWidth: 0.1
        },
        columnStyles: {
          0: { cellWidth: 38, fontStyle: 'bold' },
          1: { cellWidth: 37 },
          2: { cellWidth: 46 },
          3: { cellWidth: 30, halign: 'center', fontStyle: 'bold' },
          4: { cellWidth: 60, halign: 'center' },
          5: { cellWidth: 60, halign: 'center' },
        },

        alternateRowStyles: { fillColor: [249, 250, 251] },
        didParseCell: (cellData: any) => {
          if (cellData.section === 'body' && cellData.column.dataKey === 'status') {
            const statusKey = this.getOverviewStatusKey(cellData.row.raw?.status);
            cellData.cell.styles.fontStyle = 'bold';
            if (statusKey === 'open') {
              cellData.cell.styles.textColor = WARNING;
            } else if (statusKey === 'in-progress') {
              cellData.cell.styles.textColor = TEXT_DARK;
            } else if (statusKey === 'completed') {
              cellData.cell.styles.textColor = SUCCESS;
            } else if (statusKey === 'closed') {
              cellData.cell.styles.textColor = PRIMARY_BLUE;
            } else if (statusKey === 'failed') {
              cellData.cell.styles.textColor = DANGER;
            }
          }
        },
        didDrawPage: () => {
          const pages = doc.internal.getNumberOfPages();
          const pageHeight = doc.internal.pageSize.getHeight();
          doc.setFontSize(10);
          doc.setTextColor(...TEXT_MUTED);
          doc.text(`Overview Report Page ${pages} • Generated by DSR Perform Pro • Confidential`, 15, pageHeight - 8);
        }
      });

      this.finalizePdf(doc, `TASK_${generatedBy}_${rangeText}.pdf`, mode);
    } catch (error) {
      console.error("PDF Generation failed", error);
    } finally {

    }
  }

  generateReleaseOverviewPDF(
    filters: any,
    fromdate: any,
    todate: any,
    rawData: any[],
    mode: 'download' | 'preview' = 'download'
  ) {
    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a3');
      const PRIMARY_BLUE = [37, 99, 235];
      const TEXT_DARK = [30, 41, 59];
      const TEXT_MUTED = [100, 116, 139];
      const BORDER = [226, 232, 240];
      const DANGER = [220, 38, 38];

      const data = this.getProjectOrderedReleaseData(rawData);
      const generatedBy = filters?.generatedBy || 'SYSTEM USER';
      const filteredEmployee = filters?.filteredEmployee || filters?.employee || 'All Employees';
      const filteredProject = filters?.filteredProject || 'ALL PROJECTS';
      const releaseType = filters?.releaseType || 'All';
      const department = filters?.department || 'All Departments';
      const managerName = filters?.managerName || 'All Managers';
      const fromDate = String(fromdate || '').trim();
      const toDate = String(todate || '').trim();
      const rangeText = `${fromDate} to ${toDate}`;
      const normalizedDepartment = String(department).trim().toLowerCase();
      const departmentFilePart = normalizedDepartment && !['all', 'all departments'].includes(normalizedDepartment)
        ? `_${this.getSafePdfFilePart(department)}`
        : '';
      const departmentSections = this.getReleaseOverviewDepartmentSections(filters, rawData);
      if (departmentSections.length) {
        this.generateDepartmentWiseReleaseOverviewPDF(doc, filters, fromDate, toDate, departmentSections, mode);
        return;
      }

      const internalReleaseCount = data.filter(
        (row: any) => String(row?.release_type || '').trim().toLowerCase() === 'internal'
      ).length;
      const externalReleaseCount = data.filter(
        (row: any) => String(row?.release_type || '').trim().toLowerCase() === 'external'
      ).length;

      doc.setFillColor(248, 250, 252);
      doc.rect(0, 0, 420, 297, 'F');

      doc.setFontSize(28);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.setFont(undefined, 'bold');
      doc.text('RIDSYS', 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'normal');
      doc.text('ENTERPRISE RESOURCE PERFORMANCE SYSTEM', 15, 26);

      doc.setFontSize(22);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.text('RELEASE OVERVIEW REPORT', 15, 45);

      doc.setDrawColor(...PRIMARY_BLUE);
      doc.setLineWidth(1);
      doc.line(15, 50, 100, 50);

      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(...BORDER);
      // doc.roundedRect(15, 58, 110, 28, 3, 3, 'FD');
      // doc.roundedRect(133, 58, 110, 28, 3, 3, 'FD');
      // doc.roundedRect(251, 58, 120, 28, 3, 3, 'FD');

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text('FILTER DETAILS', 20, 65);

      doc.setFontSize(11);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.text(`GENERATED BY: ${String(generatedBy).toUpperCase()}`, 20, 71);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(...TEXT_DARK);
      doc.text(`PROJECT: ${String(filteredProject).toUpperCase()}`, 20, 77);
      doc.text(`RELEASE TYPE: ${String(releaseType).toUpperCase()}`, 20, 83);
      doc.text(`DEPARTMENT: ${String(department).toUpperCase()}`, 20, 89);
      doc.text(`EMPLOYEE: ${String(filteredEmployee).toUpperCase()}`, 20, 95);

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text('REPORTING PERIOD', 120, 65);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(rangeText.toUpperCase(), 120, 71);
      doc.setFont(undefined, 'normal');
      doc.text('Release activity timeline', 120, 77);
      doc.text(`TOTAL RELEASES: ${data.length}`, 120, 83);
      doc.text(`MANAGER: ${String(managerName).toUpperCase()}`, 120, 89);

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'bold');
      doc.text('EXPORT METRICS', 210, 65);

      doc.setFontSize(11);
      doc.setTextColor(...TEXT_DARK);
      doc.text(`EXPORT DATE: ${new Date().toLocaleDateString().toUpperCase()}`, 210, 71);
      doc.setFont(undefined, 'normal');
      doc.text(`INTERNAL RELEASES: ${internalReleaseCount}`, 210, 77);
      doc.text(`EXTERNAL RELEASES: ${externalReleaseCount}`, 210, 83);



      const tableData = data.map((item: any, index: number) => ({
        s_no: index + 1,
        project_name: item.project_name || item.project_title || '-',
        title: item.title || '-',
        version: item.version || '-',
        manager_name: item.manager_name || '-',
        assignee_from_name: item.assignee_from_name || '-',
        release_performance: this.getReleasePerformance(item),
        planned_date: item.planned_date || '-',
        released_date: item.released_date || '-',
        tested_by_name: this.getReleaseTesterName(item),
        // qc_testing_start_date: this.getReleaseQcTestingStartDate(item),
        // qc_testing_end_date: item.qc_testing_end_date ? String(item.qc_testing_end_date).split('T')[0] : '-',
        // qc_released_date: item.closed_date ? String(item.closed_date).split('T')[0] : '-',
        company_name: item.company_name || '-',
        status: item.status || '-',
        release_type: item.release_type || '-',
        overdue_date: this.getReleaseOverdueDate(item),
        overdue_state: this.getReleaseOverdueState(item),
        overdue_status: this.getReleaseOverdueStatus(item),
        overdue_status_state: this.getReleaseOverdueStatusState(item),
        remarks: item.remarks || '-'
      }));

      (doc as any).autoTable({
        columns: [
          { header: 'S/NO', dataKey: 's_no' },
          { header: 'PROJECT', dataKey: 'project_name' },
          { header: 'TITLE', dataKey: 'title' },
          { header: 'VERSION', dataKey: 'version' },
          { header: 'MANAGER / TL', dataKey: 'manager_name' },
          { header: 'WORKED BY / RELEASED BY', dataKey: 'assignee_from_name' },
          { header: 'RELEASE PERFORMANCE', dataKey: 'release_performance' },
          { header: 'PLANNED DATE', dataKey: 'planned_date' },
          { header: 'RELEASE DATE', dataKey: 'released_date' },
          { header: 'TESTED BY', dataKey: 'tested_by_name' },
          // { header: 'QC TESTING START DATE', dataKey: 'qc_testing_start_date' },
          // { header: 'QC TESTING END DATE', dataKey: 'qc_testing_end_date' },
          // { header: 'QC RELEASED DATE', dataKey: 'qc_released_date' },
          { header: 'CLIENT', dataKey: 'company_name' },
          { header: 'STATUS', dataKey: 'status' },
          { header: 'RELEASE TYPE', dataKey: 'release_type' },
          { header: 'OVERDUE', dataKey: 'overdue_date' },
          { header: 'OVERDUE STATUS', dataKey: 'overdue_status' },
          { header: 'REMARKS', dataKey: 'remarks' },
        ],
        body: tableData,
        startY: ((doc as any).lastAutoTable?.finalY || 94) + 10,
        theme: 'grid',
        margin: { left: 15, right: 15, bottom: 18 },
        tableWidth: 'auto',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: 255,
          fontStyle: 'bold',
          halign: 'center',
          valign: 'middle',
          fontSize: 9,
          cellPadding: { top: 3, bottom: 3, left: 2, right: 2 }
        },
        styles: {
          fontSize: 9,
          cellPadding: 2.5,
          overflow: 'linebreak',
          textColor: TEXT_DARK,
          lineColor: BORDER,
          lineWidth: 0.1
        },
        columnStyles: {
          0: { cellWidth: 15, halign: 'center' },
          1: { cellWidth: 26 },
          2: { cellWidth: 30 },
          3: { cellWidth: 20, halign: 'center', fontStyle: 'bold' },
          4: { cellWidth: 35, halign: 'center', fontStyle: 'bold' },
          5: { cellWidth: 30, halign: 'center', fontStyle: 'bold' },
          6: { cellWidth: 24, halign: 'center', fontStyle: 'bold' },
          7: { cellWidth: 20, halign: 'center' },
          8: { cellWidth: 20, halign: 'center' },
          9: { cellWidth: 25, fontStyle: 'bold' },
          // 10: { cellWidth: 24, halign: 'center' },
          // 11: { cellWidth: 22, halign: 'center' },
          // 12: { cellWidth: 22, halign: 'center' },
          13: { cellWidth: 22, halign: 'center' },
          14: { cellWidth: 22, halign: 'center', fontStyle: 'bold' },
          15: { cellWidth: 20, halign: 'center' },
          16: { cellWidth: 22, halign: 'center', fontStyle: 'bold' },
          18: { cellWidth: 25 },
          17: { cellWidth: 24, halign: 'center', fontStyle: 'bold' },
        },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        didParseCell: (cellData: any) => {
          if (
            cellData.section === 'body' &&
            cellData.column.dataKey === 'release_performance' &&
            cellData.row.raw?.release_performance !== '-'
          ) {
            cellData.cell.styles.fontStyle = 'bold';
            cellData.cell.styles.textColor = this.getReleasePerformanceTextColor(cellData.row.raw?.release_performance);
          }

          if (cellData.section === 'body' && cellData.column.dataKey === 'status') {
            cellData.cell.styles.fontStyle = 'bold';
            cellData.cell.styles.textColor = this.getReleaseStatusTextColor(cellData.row.raw?.status);
          }

          if (
            cellData.section === 'body' &&
            cellData.column.dataKey === 'overdue_date' &&
            cellData.row.raw?.overdue_date !== '-'
          ) {
            cellData.cell.styles.fontStyle = 'bold';
            cellData.cell.styles.textColor = this.getReleaseOverdueTextColor(cellData.row.raw?.overdue_state);
          }

          if (
            cellData.section === 'body' &&
            cellData.column.dataKey === 'overdue_status' &&
            cellData.row.raw?.overdue_status !== '-'
          ) {
            cellData.cell.styles.fontStyle = 'bold';
            cellData.cell.styles.textColor = this.getReleaseOverdueStatusTextColor(cellData.row.raw?.overdue_status_state);
          }
        },
        didDrawPage: () => {
          const pages = doc.internal.getNumberOfPages();
          const pageHeight = doc.internal.pageSize.getHeight();
          doc.setFontSize(9);
          doc.setTextColor(...TEXT_MUTED);
          doc.text(`Release Overview Report Page ${pages} • Generated by DSR Perform Pro • Confidential`, 15, pageHeight - 8);
        }
      });

      this.finalizePdf(doc, `RELEASE_REPORT${departmentFilePart}_${fromDate}_to_${toDate}.pdf`, mode);

    } catch (error) {
      console.error('Release PDF Generation failed', error);
    }
  }

  private getReleaseOverviewDepartmentSections(filters: any, rawData: any[]): ReleaseOverviewExportSection[] {
    if (!filters?.departmentWiseReleaseReport || !Array.isArray(filters?.departmentSections)) {
      return [];
    }

    const fallbackDepartmentName = filters?.department || 'All Departments';
    const fallbackManagerName = filters?.managerName || 'All Managers';
    const sections = filters.departmentSections
      .map((section: any): ReleaseOverviewExportSection => ({
        departmentName: `${section?.departmentName || section?.department || fallbackDepartmentName}`.trim(),
        managerName: `${section?.managerName || fallbackManagerName}`.trim(),
        releases: this.getProjectOrderedReleaseData(section?.releases || section?.data || [])
      }))
      .filter((section: ReleaseOverviewExportSection) => !!section.departmentName || section.releases.length > 0);

    if (sections.length) {
      return sections;
    }

    const data = this.getProjectOrderedReleaseData(rawData);
    return data.length
      ? [{
        departmentName: `${fallbackDepartmentName}`.trim(),
        managerName: `${fallbackManagerName}`.trim(),
        releases: data
      }]
      : [];
  }

  private generateDepartmentWiseReleaseOverviewPDF(
    doc: any,
    filters: any,
    fromDate: string,
    toDate: string,
    sections: ReleaseOverviewExportSection[],
    mode: 'download' | 'preview'
  ): void {
    const PRIMARY_BLUE = [37, 99, 235];
    const TEXT_DARK = [30, 41, 59];
    const TEXT_MUTED = [100, 116, 139];
    const BORDER = [226, 232, 240];
    const generatedBy = filters?.generatedBy || 'SYSTEM USER';
    const filteredEmployee = filters?.filteredEmployee || filters?.employee || 'All Employees';
    const filteredProject = filters?.filteredProject || 'ALL PROJECTS';
    const releaseType = filters?.releaseType || 'All';
    const department = filters?.department || 'All Departments';
    const managerName = filters?.managerName || 'All Managers';
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const rangeText = `${fromDate} to ${toDate}`;
    const allSectionReleases = sections.flatMap(section => section.releases);
    const totalReleaseCount = allSectionReleases.length;
    const internalReleaseCount = allSectionReleases.filter(
      (row: any) => String(row?.release_type || '').trim().toLowerCase() === 'internal'
    ).length;
    const externalReleaseCount = allSectionReleases.filter(
      (row: any) => String(row?.release_type || '').trim().toLowerCase() === 'external'
    ).length;
    const normalizedDepartment = String(department).trim().toLowerCase();
    const departmentFilePart = normalizedDepartment && !['all', 'all departments'].includes(normalizedDepartment)
      ? `_${this.getSafePdfFilePart(department)}`
      : sections.length > 1
        ? '_DEPARTMENT_WISE'
        : '';
    const tableColumns = [
      { header: 'S/NO', dataKey: 's_no' },
      { header: 'PROJECT', dataKey: 'project_name' },
      { header: 'TITLE', dataKey: 'title' },
      { header: 'VERSION', dataKey: 'version' },
      { header: 'MANAGER / TL', dataKey: 'manager_name' },
      { header: 'WORKED BY / RELEASED BY', dataKey: 'assignee_from_name' },
      { header: 'RELEASE PERFORMANCE', dataKey: 'release_performance' },
      { header: 'PLANNED DATE', dataKey: 'planned_date' },
      { header: 'RELEASE DATE', dataKey: 'released_date' },
      { header: 'TESTED BY', dataKey: 'tested_by_name' },
      { header: 'CLIENT', dataKey: 'company_name' },
      { header: 'STATUS', dataKey: 'status' },
      { header: 'RELEASE TYPE', dataKey: 'release_type' },
      { header: 'OVERDUE', dataKey: 'overdue_date' },
      { header: 'OVERDUE STATUS', dataKey: 'overdue_status' },
      { header: 'REMARKS', dataKey: 'remarks' },
    ];
    const buildTableData = (releases: any[]): any[] => releases.map((item: any, index: number) => ({
      s_no: index + 1,
      project_name: item.project_name || item.project_title || '-',
      title: item.title || '-',
      version: item.version || '-',
      manager_name: item.manager_name || '-',
      assignee_from_name: item.assignee_from_name || '-',
      release_performance: this.getReleasePerformance(item),
      planned_date: item.planned_date || '-',
      released_date: item.released_date || '-',
      tested_by_name: this.getReleaseTesterName(item),
      company_name: item.company_name || '-',
      status: item.status || '-',
      release_type: item.release_type || '-',
      overdue_date: this.getReleaseOverdueDate(item),
      overdue_state: this.getReleaseOverdueState(item),
      overdue_status: this.getReleaseOverdueStatus(item),
      overdue_status_state: this.getReleaseOverdueStatusState(item),
      remarks: item.remarks || '-'
    }));
    const emptyTableRow = {
      s_no: '-',
      project_name: 'No release records found for this department.',
      title: '-',
      version: '-',
      manager_name: '-',
      assignee_from_name: '-',
      release_performance: '-',
      planned_date: '-',
      released_date: '-',
      tested_by_name: '-',
      company_name: '-',
      status: '-',
      release_type: '-',
      overdue_date: '-',
      overdue_state: 'none',
      overdue_status: '-',
      overdue_status_state: 'none',
      remarks: '-'
    };

    doc.setFillColor(248, 250, 252);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');

    doc.setFontSize(28);
    doc.setTextColor(...PRIMARY_BLUE);
    doc.setFont(undefined, 'bold');
    doc.text('RIDSYS', 15, 20);

    doc.setFontSize(10);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont(undefined, 'normal');
    doc.text('ENTERPRISE RESOURCE PERFORMANCE SYSTEM', 15, 26);

    doc.setFontSize(22);
    doc.setTextColor(...TEXT_DARK);
    doc.setFont(undefined, 'bold');
    doc.text('RELEASE OVERVIEW REPORT', 15, 45);

    doc.setDrawColor(...PRIMARY_BLUE);
    doc.setLineWidth(1);
    doc.line(15, 50, 100, 50);

    doc.setFontSize(9);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont(undefined, 'bold');
    doc.text('FILTER DETAILS', 20, 65);

    doc.setFontSize(11);
    doc.setTextColor(...PRIMARY_BLUE);
    doc.text(`GENERATED BY: ${String(generatedBy).toUpperCase()}`, 20, 71);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(...TEXT_DARK);
    doc.text(`PROJECT: ${String(filteredProject).toUpperCase()}`, 20, 77);
    doc.text(`RELEASE TYPE: ${String(releaseType).toUpperCase()}`, 20, 83);
    doc.text(`DEPARTMENT: ${String(department).toUpperCase()}`, 20, 89);
    doc.text(`EMPLOYEE: ${String(filteredEmployee).toUpperCase()}`, 20, 95);

    doc.setFontSize(9);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont(undefined, 'bold');
    doc.text('REPORTING PERIOD', 120, 65);

    doc.setFontSize(11);
    doc.setTextColor(...TEXT_DARK);
    doc.text(rangeText.toUpperCase(), 120, 71);
    doc.setFont(undefined, 'normal');
    doc.text('Department-wise release report', 120, 77);
    doc.text(`TOTAL RELEASES: ${totalReleaseCount}`, 120, 83);
    doc.text(`MANAGER: ${String(managerName).toUpperCase()}`, 120, 89);

    doc.setFontSize(9);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont(undefined, 'bold');
    doc.text('EXPORT METRICS', 210, 65);

    doc.setFontSize(11);
    doc.setTextColor(...TEXT_DARK);
    doc.text(`EXPORT DATE: ${new Date().toLocaleDateString().toUpperCase()}`, 210, 71);
    doc.setFont(undefined, 'normal');
    doc.text(`INTERNAL RELEASES: ${internalReleaseCount}`, 210, 77);
    doc.text(`EXTERNAL RELEASES: ${externalReleaseCount}`, 210, 83);

    let cursorY = 104;

    sections.forEach((section, sectionIndex) => {
      const releases = this.getProjectOrderedReleaseData(section.releases);

      if (sectionIndex > 0 && cursorY > pageHeight - 72) {
        doc.addPage();
        cursorY = 20;
      }

      doc.setFillColor(30, 41, 59);
      doc.setDrawColor(30, 41, 59);
      doc.roundedRect(15, cursorY, pageWidth - 30, 12, 2, 2, 'F');
      doc.setFont(undefined, 'bold');
      doc.setFontSize(10);
      doc.setTextColor(255, 255, 255);
      doc.text(`${section.departmentName.toUpperCase()} DEPARTMENT`, 20, cursorY + 7.5);
      doc.text(`Release Report | ${releases.length} Records`, pageWidth - 20, cursorY + 7.5, { align: 'right' });

      doc.setFont(undefined, 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(...TEXT_MUTED);
      doc.text(`Manager: ${section.managerName || managerName}`, 20, cursorY + 18);

      (doc as any).autoTable({
        columns: tableColumns,
        body: releases.length ? buildTableData(releases) : [emptyTableRow],
        startY: cursorY + 24,
        theme: 'grid',
        margin: { left: 15, right: 15, bottom: 18 },
        tableWidth: 'auto',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: 255,
          fontStyle: 'bold',
          halign: 'center',
          valign: 'middle',
          fontSize: 9,
          cellPadding: { top: 3, bottom: 3, left: 2, right: 2 }
        },
        styles: {
          fontSize: 9,
          cellPadding: 2.5,
          overflow: 'linebreak',
          textColor: TEXT_DARK,
          lineColor: BORDER,
          lineWidth: 0.1
        },
        columnStyles: {
          0: { cellWidth: 15, halign: 'center' },
          1: { cellWidth: 26 },
          2: { cellWidth: 30 },
          3: { cellWidth: 20, halign: 'center', fontStyle: 'bold' },
          4: { cellWidth: 35, halign: 'center', fontStyle: 'bold' },
          5: { cellWidth: 30, halign: 'center', fontStyle: 'bold' },
          6: { cellWidth: 24, halign: 'center', fontStyle: 'bold' },
          7: { cellWidth: 20, halign: 'center' },
          8: { cellWidth: 20, halign: 'center' },
          9: { cellWidth: 25, fontStyle: 'bold' },
          13: { cellWidth: 22, halign: 'center' },
          14: { cellWidth: 22, halign: 'center', fontStyle: 'bold' },
          15: { cellWidth: 20, halign: 'center' },
          16: { cellWidth: 22, halign: 'center', fontStyle: 'bold' },
          18: { cellWidth: 25 },
          17: { cellWidth: 24, halign: 'center', fontStyle: 'bold' },
        },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        didParseCell: (cellData: any) => {
          if (
            cellData.section === 'body' &&
            cellData.column.dataKey === 'release_performance' &&
            cellData.row.raw?.release_performance !== '-'
          ) {
            cellData.cell.styles.fontStyle = 'bold';
            cellData.cell.styles.textColor = this.getReleasePerformanceTextColor(cellData.row.raw?.release_performance);
          }

          if (cellData.section === 'body' && cellData.column.dataKey === 'status') {
            cellData.cell.styles.fontStyle = 'bold';
            cellData.cell.styles.textColor = this.getReleaseStatusTextColor(cellData.row.raw?.status);
          }

          if (
            cellData.section === 'body' &&
            cellData.column.dataKey === 'overdue_date' &&
            cellData.row.raw?.overdue_date !== '-'
          ) {
            cellData.cell.styles.fontStyle = 'bold';
            cellData.cell.styles.textColor = this.getReleaseOverdueTextColor(cellData.row.raw?.overdue_state);
          }

          if (
            cellData.section === 'body' &&
            cellData.column.dataKey === 'overdue_status' &&
            cellData.row.raw?.overdue_status !== '-'
          ) {
            cellData.cell.styles.fontStyle = 'bold';
            cellData.cell.styles.textColor = this.getReleaseOverdueStatusTextColor(cellData.row.raw?.overdue_status_state);
          }
        },
        didDrawPage: () => {
          const pages = doc.internal.getNumberOfPages();
          const footerY = doc.internal.pageSize.getHeight() - 8;
          doc.setFontSize(9);
          doc.setTextColor(...TEXT_MUTED);
          doc.text(`Release Overview Report Page ${pages} • Generated by DSR Perform Pro • Confidential`, 15, footerY);
        }
      });

      cursorY = ((doc as any).lastAutoTable?.finalY || cursorY + 24) + 14;
    });

    this.finalizePdf(doc, `RELEASE_REPORT${departmentFilePart}_${fromDate}_to_${toDate}.pdf`, mode);
  }

  generateAttendancePDF(empId: any, fromdate: any, todate: any, rawData: any[]) {

    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a4');

      const PRIMARY_BLUE = [37, 99, 235];
      const TEXT_DARK = [30, 41, 59];

      const employeeName = rawData?.length ? rawData[0].employee_name : 'Employee';

      // ===============================
      // 1️⃣ HEADER BRANDING
      // ===============================
      doc.setFontSize(28);
      doc.setTextColor(...PRIMARY_BLUE);
      doc.setFont(undefined, 'bold');
      doc.text("RIDSYS", 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(148, 163, 184);
      doc.setFont(undefined, 'normal');
      doc.text("ENTERPRISE RESOURCE PERFORMANCE SYSTEM", 15, 26);

      // ===============================
      // 2️⃣ MAIN TITLE
      // ===============================
      doc.setFontSize(22);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.text("EMPLOYEE ATTENDANCE REPORT", 15, 45);

      doc.setDrawColor(...PRIMARY_BLUE);
      doc.setLineWidth(1);
      doc.line(15, 50, 110, 50);

      // ===============================
      // 3️⃣ EMPLOYEE + DATE INFO
      // ===============================
      doc.setFontSize(10);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.text(`EMPLOYEE: ${employeeName.toUpperCase()}`, 15, 60);

      doc.setFont(undefined, 'normal');
      doc.text(`PERIOD: ${fromdate} TO ${todate}`, 15, 66);

      doc.text(`EXPORT DATE: ${new Date().toLocaleDateString()}`, 220, 60);
      doc.text(`TOTAL DAYS: ${rawData.length}`, 220, 66);

      // ===============================
      // 4️⃣ ATTENDANCE TABLE
      // ===============================

      const columns = [
        { header: 'DATE', dataKey: 'attendance_date' },
        { header: 'DAY', dataKey: 'day' },
        { header: 'PUNCH TIME', dataKey: 'punch_time' },
        { header: 'WORKED HRS', dataKey: 'worked_hrs' },
        { header: 'STATUS', dataKey: 'status' },
        { header: 'REMARKS', dataKey: 'remarks' }
      ];

      (doc as any).autoTable({
        columns: columns,
        body: rawData,
        startY: 75,
        theme: 'grid',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center',
          fontSize: 10
        },
        styles: {
          fontSize: 10,
          cellPadding: 4,
          overflow: 'linebreak',
          textColor: [51, 65, 85],
          lineColor: [226, 232, 240],
          lineWidth: 0.1
        },
        columnStyles: {
          0: { cellWidth: 30, halign: 'center' },
          1: { cellWidth: 40, halign: 'center' },
          2: { cellWidth: 50, halign: 'center' },
          3: { cellWidth: 30, halign: 'center' },
          4: { cellWidth: 45, halign: 'center' },
          5: { cellWidth: 'auto', halign: 'center' }
        },
        alternateRowStyles: { fillColor: [249, 250, 251] },

        didParseCell: (cellData: any) => {
          if (cellData.section === 'body' && cellData.column.dataKey === 'status') {

            const status = cellData.cell.raw;

            if (status === 'Present')
              cellData.cell.styles.textColor = [22, 163, 74];

            if (status === 'Absent')
              cellData.cell.styles.textColor = [220, 38, 38];

            if (status === 'Late')
              cellData.cell.styles.textColor = [234, 88, 12];
          }
        },

        didDrawPage: () => {
          const pageCount = doc.internal.getNumberOfPages();
          doc.setFontSize(9);
          doc.setTextColor(148, 163, 184);
          doc.text(
            `Attendance Report • Page ${pageCount} • Generated by RIDSYS ERP • Confidential`,
            15,
            202
          );
        }
      });

      // ===============================
      // 5️⃣ SUMMARY
      // ===============================

      const present = rawData.filter(d => d.status === 'Present').length;
      const absent = rawData.filter(d => d.status === 'Absent').length;
      const late = rawData.filter(d => d.status === 'Late').length;

      const finalY = (doc as any).lastAutoTable.finalY || 75;

      (doc as any).autoTable({
        head: [['ATTENDANCE SUMMARY', 'COUNT']],
        body: [
          ['PRESENT DAYS', present],
          ['ABSENT DAYS', absent],
          ['LATE DAYS', late],
          ['TOTAL DAYS', rawData.length]
        ],
        startY: finalY + 10,
        margin: { left: 180 },
        tableWidth: 100,
        theme: 'grid',
        headStyles: {
          fillColor: [30, 41, 59],
          textColor: [255, 255, 255],
          fontSize: 9,
          halign: 'center'
        },
        styles: {
          fontSize: 9,
          fontStyle: 'bold',
          cellPadding: 3
        },
        columnStyles: {
          1: { halign: 'center', cellWidth: 30 }
        }
      });

      doc.save(`RIDSYS_Attendance_${employeeName}_${fromdate}_to_${todate}.pdf`);

    } catch (error) {
      console.error("Attendance PDF generation failed", error);
    }
  }


  private getDateRangeLabel(start: Date, end: Date): string {
    if (!start || !end) return '';
    const sameMonthYear = start.getMonth() === end.getMonth() && start.getFullYear() === end.getFullYear();

    if (sameMonthYear) {
      return `${start.getDate()}–${end.getDate()} ${start.toLocaleString('en-US', { month: 'long', year: 'numeric' })}`;
    }
    const startLabel = start.toLocaleDateString('en-US', { day: '2-digit', month: 'short', year: 'numeric' });
    const endLabel = end.toLocaleDateString('en-US', { day: '2-digit', month: 'short', year: 'numeric' });
    return `${startLabel} – ${endLabel}`;
  }

  private getInputDateRangeText(fromdate: any, todate: any): string {
    const fromDate = this.formatInputDateToYMD(fromdate);
    const toDate = this.formatInputDateToYMD(todate);

    if (fromDate && toDate) {
      return `${fromDate} to ${toDate}`;
    }

    return fromDate || toDate || '';
  }

  private formatInputDateToYMD(value: any): string {
    if (!value) {
      return '';
    }

    if (typeof value === 'string') {
      const trimmed = value.trim();
      const ymdMatch = /^(\d{4})-(\d{2})-(\d{2})/.exec(trimmed);
      if (ymdMatch) {
        return `${ymdMatch[1]}-${ymdMatch[2]}-${ymdMatch[3]}`;
      }
    }

    const date = new Date(value);
    if (Number.isNaN(date.getTime())) {
      return String(value);
    }

    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(
      date.getDate()
    ).padStart(2, '0')}`;
  }

  private formatDate(date: Date): string {
    const d = date.getDate().toString().padStart(2, '0');
    const m = (date.getMonth() + 1).toString().padStart(2, '0');
    const y = date.getFullYear();
    return `${d}-${m}-${y}`;
  }

  private getOverviewStatusKey(status: any): string {
    const normalized = String(status ?? '')
      .trim()
      .toLowerCase()
      .replace(/[_\s]+/g, '-');

    if (normalized === 'closed') return 'closed';
    if (normalized === 'in-progress' || normalized === 'inprogress') return 'in-progress';
    if (normalized === 'open') return 'open';
    if (normalized === 'completed' || normalized === 'complete') return 'completed';
    if (normalized === 'failed' || normalized === 'fail') return 'failed';
    return normalized;
  }

  private getReleaseStatusKey(status: any): string {
    const normalized = String(status ?? '')
      .trim()
      .toLowerCase()
      .replace(/[_\s]+/g, '-');

    if (normalized === 'open') return 'open';
    if (normalized === 'in-progress' || normalized === 'inprogress') return 'in-progress';
    if (normalized === 'to-be-tested' || normalized === 'tobe-tested' || normalized === 'to-be-test' || normalized === 'to-be-tested') return 'to-be-tested';
    if (normalized === 'in-review' || normalized === 'inreview') return 'in-review';
    if (normalized === 'completed' || normalized === 'complete') return 'completed';
    if (normalized === 'failed' || normalized === 'fail') return 'failed';
    return normalized;
  }

  private getReleaseStatusTextColor(status: any): number[] {
    const statusKey = this.getReleaseStatusKey(status);

    if (statusKey === 'open') return [71, 85, 105];
    if (statusKey === 'upcoming-release') return [219, 39, 119];
    if (statusKey === 'on-hold') return [234, 88, 12];
    if (statusKey === 'in-progress') return [37, 99, 235];
    if (statusKey === 'to-be-tested') return [124, 58, 237];
    if (statusKey === 'rejected') return [202, 138, 4];
    if (statusKey === 'pass' || statusKey === 'passed') return [22, 163, 74];
    if (statusKey === 'failed') return [220, 38, 38];
    if (statusKey === 'in-review') return [147, 51, 234];
    if (statusKey === 'approved') return [5, 150, 105];
    if (statusKey === 'completed') return [21, 128, 61];
    if (statusKey === 'cancelled') return [185, 28, 28];

    return [30, 41, 59];
  }

  private isReleaseOverdue(release: any): boolean {
    if (!this.isUpcomingRelease(release)) {
      return false;
    }

    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);
    return daysUntilRelease !== null && daysUntilRelease < 0;
  }

  private getProjectOrderedReleaseData(rawData: any[]): any[] {
    const data = Array.isArray(rawData) ? rawData : rawData ? [rawData] : [];

    return [...data].sort((first: any, second: any) => {
      const projectCompare = this.getReleaseProjectName(first).localeCompare(
        this.getReleaseProjectName(second),
        undefined,
        { sensitivity: 'base', numeric: true }
      );

      if (projectCompare !== 0) {
        return projectCompare;
      }

      const dateCompare = this.getReleaseDateSortValue(first?.released_date) - this.getReleaseDateSortValue(second?.released_date);

      if (dateCompare !== 0) {
        return dateCompare;
      }

      const titleCompare = `${first?.title ?? ''}`.localeCompare(`${second?.title ?? ''}`, undefined, {
        sensitivity: 'base',
        numeric: true
      });

      if (titleCompare !== 0) {
        return titleCompare;
      }

      return `${first?.version ?? ''}`.localeCompare(`${second?.version ?? ''}`, undefined, {
        sensitivity: 'base',
        numeric: true
      });
    });
  }

  private getReleaseProjectName(release: any): string {
    return `${release?.project_name || release?.project_title || ''}`.trim();
  }

  private getReleaseDateSortValue(value: any): number {
    const parsed = this.parseReleaseDate(`${value ?? ''}`.trim());
    return parsed ? parsed.getTime() : Number.MAX_SAFE_INTEGER;
  }

  private getReleaseOverdueDate(release: any): string {
    if (!this.isUpcomingRelease(release)) {
      const completionDate = this.getReleaseCompletionDate(release);
      return completionDate ? this.formatReleaseDateOnly(completionDate) : '-';
    }

    const overdueState = this.getReleaseOverdueState(release);

    if (overdueState === 'overdue') {
      return this.formatReleaseDateOnly(`${release?.released_date ?? ''}`.trim()) || '-';
    }

    return '-';
  }

  private getReleaseOverdueStatus(release: any): string {
    if (!this.isUpcomingRelease(release)) {
      return '-';
    }

    const overdueStatusState = this.getReleaseOverdueStatusState(release);
    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);

    if (overdueStatusState === 'overdue') {
      return 'Overdue';
    }

    if (overdueStatusState === 'high-warning') {
      return daysUntilRelease === 0 ? 'Due Today' : 'Due Tomorrow';
    }

    if (overdueStatusState === 'warning') {
      return `Due in ${daysUntilRelease} Days`;
    }

    return '-';
  }

  private getReleaseOverdueState(release: any): ReleasePerformanceState | 'warning' | 'high-warning' | 'overdue' {
    if (!this.isUpcomingRelease(release)) {
      return this.getReleasePerformanceState(release);
    }

    return this.isReleaseOverdue(release) ? 'overdue' : 'none';
  }

  private getReleaseOverdueStatusState(release: any): 'none' | 'warning' | 'high-warning' | 'overdue' {
    if (!this.isUpcomingRelease(release)) {
      return 'none';
    }

    const daysUntilRelease = this.getDaysUntilRelease(release?.released_date);

    if (daysUntilRelease === null) {
      return 'none';
    }

    if (daysUntilRelease < 0) {
      return 'overdue';
    }

    if (daysUntilRelease <= 1) {
      return 'high-warning';
    }

    return 'warning';
  }

  private getReleaseOverdueTextColor(state: any): number[] {
    if (state === 'excellent') return [22, 163, 74];
    if (state === 'very-good') return [124, 58, 237];
    if (state === 'good') return [37, 99, 235];
    if (state === 'poor') return [220, 38, 38];
    if (state === 'warning') return [217, 119, 6];
    if (state === 'high-warning') return [234, 88, 12];
    if (state === 'overdue') return [220, 38, 38];
    return [30, 41, 59];
  }

  private getReleaseOverdueStatusTextColor(state: any): number[] {
    if (state === 'warning') return [217, 119, 6];
    if (state === 'high-warning') return [234, 88, 12];
    if (state === 'overdue') return [220, 38, 38];
    return [30, 41, 59];
  }

  private getReleaseTesterName(release: any): string {
    if (this.isUpcomingRelease(release)) {
      return '-';
    }

    return `${release?.assignee_to_name ?? ''}`.trim() || '-';
  }

  private getReleaseQcTestingStartDate(release: any): string {
    const qcTestingStartDate = this.getFirstDateValue(release, ['qc_testing_start_date', 'qcTestingStartDate']);

    if (qcTestingStartDate) {
      return this.formatReleaseDateOnly(qcTestingStartDate) || '';
    }

    return '';
  }

  private isUpcomingRelease(release: any): boolean {
    return this.normalizeReleaseStatus(release?.status) === 'upcoming-release';
  }

  private getReleasePerformance(release: any): string {
    if (this.isUpcomingRelease(release)) {
      return 'Pending';
    }

    if (this.isReleasePerformancePending(release)) {
      return 'Pending';
    }

    const performanceState = this.getReleasePerformanceState(release);
    if (performanceState === 'excellent') return 'Excellent';
    if (performanceState === 'very-good') return 'Very Good';
    if (performanceState === 'good') return 'Good';
    if (performanceState === 'poor') return 'Poor';
    return '-';
  }

  private getReleasePerformanceTextColor(performance: any): number[] {
    const key = String(performance || '').trim().toLowerCase();
    if (key === 'excellent') return [22, 163, 74];
    if (key === 'very good' || key === 'very-good') return [124, 58, 237];
    if (key === 'good') return [37, 99, 235];
    if (key === 'poor') return [220, 38, 38];
    if (key === 'pending') return [71, 85, 105];
    return [30, 41, 59];
  }

  private isReleasePerformancePending(release: any): boolean {
    const statusKey = this.getReleaseStatusKey(release?.status);
    return statusKey === 'pending';
  }

  private getReleasePerformanceState(release: any): ReleasePerformanceState {
    const releaseDate = this.parseReleaseDate(this.getFirstDateValue(release, [
      'released_date',
      'release_date',
      'releaseDate',
      'scheduled_release_date',
      'scheduledReleaseDate'
    ]) || '');
    const completedDate = this.parseReleaseDate(this.getReleaseCompletionDate(release) || '');

    if (!releaseDate || !completedDate) {
      return 'none';
    }

    const plannedDate = this.parseReleaseDate(this.getFirstDateValue(release, [
      'planned_date',
      'plannedDate',
      'scheduled_date',
      'scheduledDate'
    ]) || '');
    const releaseTime = this.getStartOfDayTime(releaseDate);
    const completedTime = this.getStartOfDayTime(completedDate);
    const plannedTime = plannedDate ? this.getStartOfDayTime(plannedDate) : null;
    const daysBeforeRelease = Math.floor((releaseTime - completedTime) / 86400000);

    if (daysBeforeRelease >= 2) {
      return 'excellent';
    }

    if (daysBeforeRelease === 1) {
      return 'very-good';
    }

    if (daysBeforeRelease === 0) {
      return plannedTime === releaseTime ? 'excellent' : 'good';
    }

    return 'poor';
  }

  private getReleaseCompletionDate(release: any): string | null {
    const transitionDate = this.getToBeTestedTransitionDate(release);

    if (transitionDate) {
      return transitionDate;
    }

    return this.getFirstDateValue(release, [
      'completed_date',
      'completedDate',
      'completion_date',
      'completionDate',
      'closed_date',
      'closedDate',
      'qc_released_date',
      'qcReleasedDate',
      'qc_release_date',
      'qcReleaseDate',
      'actual_release_date',
      'actualReleaseDate'
    ]);
  }

  private getToBeTestedTransitionDate(release: any): string | null {
    const explicitTransitionDate = this.getFirstDateValue(release, [
      'to_be_tested_date',
      'toBeTestedDate',
      'to_be_tested_at',
      'toBeTestedAt',
      'release_tested_date',
      'release_status_changed_date',
      'status_changed_date'
    ]);

    if (explicitTransitionDate) {
      return explicitTransitionDate;
    }

    const timelineDate = this.getFirstToBeTestedTimelineDate(
      release?.status_logs || release?.statusLogs || release?.activity_logs || release?.activityLogs || release?.logs
    );

    if (timelineDate) {
      return timelineDate;
    }

    if (this.normalizeReleaseStatus(release?.status) === 'to-be-tested') {
      return this.getFirstDateValue(release, ['updateddate', 'updated_date']);
    }

    return null;
  }

  private getFirstToBeTestedTimelineDate(logs: any): string | null {
    const timeline = Array.isArray(logs) ? logs : [];
    const toBeTestedLogs = timeline
      .map((log: any) => ({
        date: this.getFirstDateValue(log, ['logdate', 'created_date', 'createddate', 'updated_date', 'updateddate']),
        status: this.normalizeReleaseStatus(log?.status)
      }))
      .filter((log: any) => log.status === 'to-be-tested' && !!log.date)
      .map((log: any) => ({
        date: log.date,
        time: this.getReleaseDateTime(log.date)
      }))
      .filter((log: any) => log.time !== null)
      .sort((first: any, second: any) => first.time - second.time);

    return toBeTestedLogs[0]?.date || null;
  }

  private getFirstDateValue(source: any, keys: string[]): string | null {
    for (const key of keys) {
      const value = `${source?.[key] ?? ''}`.trim();
      if (value && this.getReleaseDateTime(value) !== null) {
        return value;
      }
    }

    return null;
  }

  private getReleaseDateTime(value: string): number | null {
    const parsed = this.parseReleaseDate(value);
    return parsed ? parsed.getTime() : null;
  }

  private getStartOfDayTime(date: Date): number {
    const normalizedDate = new Date(date);
    normalizedDate.setHours(0, 0, 0, 0);
    return normalizedDate.getTime();
  }

  private normalizeReleaseStatus(status: any): string {
    return `${status ?? ''}`.trim().toLowerCase().replace(/[-_\s]+/g, '-');
  }

  private formatReleaseDateOnly(value: string): string {
    const parsed = this.parseReleaseDate(`${value ?? ''}`.trim());

    if (!parsed) {
      return `${value ?? ''}`.trim();
    }

    return `${parsed.getFullYear()}-${String(parsed.getMonth() + 1).padStart(2, '0')}-${String(
      parsed.getDate()
    ).padStart(2, '0')}`;
  }

  private getDaysUntilRelease(releasedDate: string | null | undefined): number | null {
    const rawValue = `${releasedDate ?? ''}`.trim();
    if (!rawValue) {
      return null;
    }

    const releaseDate = this.parseReleaseDate(rawValue);
    if (!releaseDate) {
      return null;
    }

    releaseDate.setHours(0, 0, 0, 0);

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    return Math.ceil((releaseDate.getTime() - today.getTime()) / 86400000);
  }

  private parseReleaseDate(value: string): Date | null {
    const normalized = value.trim();
    const ymdParts = normalized.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})(?:[T\s].*)?$/);

    if (ymdParts) {
      const year = Number(ymdParts[1]);
      const month = Number(ymdParts[2]);
      const day = Number(ymdParts[3]);
      const parsed = new Date(year, month - 1, day);
      return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    const dmyParts = normalized.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{4})(?:[T\s].*)?$/);

    if (dmyParts) {
      const day = Number(dmyParts[1]);
      const month = Number(dmyParts[2]);
      const year = Number(dmyParts[3]);
      const parsed = new Date(year, month - 1, day);
      return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    const parsed = new Date(normalized);
    return Number.isNaN(parsed.getTime()) ? null : parsed;
  }

  getProcessedData(fromDate: any, toDate: any, rawData: any): DSRRecord[] {
    const start = new Date(fromDate);
    const end = new Date(toDate);
    const result: DSRRecord[] = [];
    console.log("RAWDATA   =", rawData);

    for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
      const formatted = this.formatDate(d);
      const existing = rawData.find((item: any) => {
        console.log(item.date, formatted);
        const date = new Date(item.date);
        return this.formatDate(date) === formatted;
      });

      if (existing) {
        result.push({ ...existing, date: formatted, statusText: 'Present' });
      } else {
        const isSunday = d.getDay() === 0;
        result.push({
          id: Math.random(),
          date: formatted,
          employee_name: "PRASADARAO GAJULA",
          project_title: "N/A",
          sub_task: isSunday ? "Holiday - Weekly Off" : "Not DSR Entered",
          worked_hours: isSunday ? "-" : "0 Hours",
          completion_percentage: 0,
          task: isSunday ? "Holiday" : "Absent",
          comments: isSunday ? "Sunday - Weekly Off" : "Log Missing: No entry submitted for this date.",
          statusText: isSunday ? "Holiday" : "Absent"
        });
      }
    }
    return result;
  }

  generateTicketsPDF(
    filters: any,
    fromdate: any,
    todate: any,
    rawData: any[],
    mode: 'download' | 'preview' = 'download'
  ) {
    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a3');

      const PRIMARY_BLUE = [0, 150, 232];
      const TEXT_DARK = [0, 0, 0];
      const TEXT_MUTED = [71, 85, 105];
      const BORDER = [0, 0, 0];
      const SUNDAY_FILL = [255, 247, 237];
      const PLACEHOLDER_TEXT = [100, 116, 139];
      const LEAVE_TEXT = [217, 119, 6];

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const data = this.buildOverallTicketReportRows(rawData, fromdate, todate);
      const totalTickets = data.filter((row: any) => !row._isPlaceholderRow && !row._isLeaveRow).length;
      const generatedBy = filters?.generatedBy || 'SYSTEM USER';
      const rangeText = this.getInputDateRangeText(fromdate, todate);
      const generatedOn = this.getTicketGeneratedDateTime();

      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'bold');
      doc.setFontSize(15);
      doc.text('OVERALL TICKET REPORT', pageWidth / 2, 18, { align: 'center' });

      (doc as any).autoTable({
        head: [['Date Range']],
        body: [[rangeText || '-']],
        startY: 28,
        margin: { left: 34 },
        tableWidth: 78,
        theme: 'grid',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: [255, 255, 255],
          fontSize: 8,
          fontStyle: 'bold',
          halign: 'center',
          cellPadding: 2
        },
        styles: {
          fontSize: 8,
          textColor: TEXT_DARK,
          lineColor: BORDER,
          lineWidth: 0.25,
          halign: 'center',
          cellPadding: 2
        }
      });

      doc.setFontSize(9);
      doc.setTextColor(0, 0, 120);
      doc.setFont(undefined, 'bold');
      doc.text('REPORT DETAILS', pageWidth - 130, 28);

      doc.setTextColor(...TEXT_DARK);
      doc.setFont(undefined, 'normal');
      doc.text(`Generated By : ${this.cleanPdfText(generatedBy)}`, pageWidth - 130, 34);
      doc.text(`Total Tickets : ${totalTickets}`, pageWidth - 130, 40);
      doc.text(`Generated On : ${generatedOn}`, pageWidth - 130, 46);

      doc.setDrawColor(...BORDER);
      doc.setLineWidth(0.3);
      doc.line(28, 58, pageWidth - 28, 58);

      const columns = [
        { header: 'S.No', dataKey: 'sno' },
        { header: 'Date', dataKey: 'date' },
        { header: 'Day', dataKey: 'day' },
        { header: 'Code', dataKey: 'code' },
        { header: 'Ticket', dataKey: 'ticket_name' },
        { header: 'Client', dataKey: 'client' },
        { header: 'Product', dataKey: 'product' },
        { header: 'Department', dataKey: 'department' },
        { header: 'Assigned From', dataKey: 'assigned_from' },
        { header: 'Assigned To', dataKey: 'assigned_to' },
        { header: 'Remarks', dataKey: 'remarks' },
        { header: 'Worked Hrs', dataKey: 'worked_hours' },
        { header: 'Entry Date', dataKey: 'entry_date' },
        { header: 'STATUS', dataKey: 'status' },
      ];

      (doc as any).autoTable({
        columns,
        body: data,
        startY: 72,
        theme: 'grid',
        margin: { left: 6, right: 6, bottom: 18 },
        tableWidth: pageWidth - 12,
        showHead: 'everyPage',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center',
          valign: 'middle',
          fontSize: 8.5,
          cellPadding: { top: 2.4, bottom: 2.4, left: 1.4, right: 1.4 },
          lineColor: BORDER,
          lineWidth: 0.25
        },
        styles: {
          fontSize: 8,
          cellPadding: { top: 2.2, bottom: 2.2, left: 1.4, right: 1.4 },
          overflow: 'linebreak',
          textColor: TEXT_DARK,
          lineColor: BORDER,
          lineWidth: 0.2,
          halign: 'left',
          valign: 'top',
          minCellHeight: 10
        },
        columnStyles: {
          0: { cellWidth: 10, halign: 'left' },
          1: { cellWidth: 22 },
          2: { cellWidth: 13, halign: 'center', fontStyle: 'bold' },
          3: { cellWidth: 23, fontStyle: 'bold' },
          4: { cellWidth: 28 },
          5: { cellWidth: 29 },
          6: { cellWidth: 27 },
          7: { cellWidth: 24 },
          8: { cellWidth: 25 },
          9: { cellWidth: 25 },
          10: { cellWidth: 108 },
          11: { cellWidth: 16, halign: 'center' },
          12: { cellWidth: 34 },
          13: { cellWidth: 24, halign: 'center', fontStyle: 'bold' }
        },
        didParseCell: (cellData: any) => {
          if (cellData.section === 'body' && cellData.row.raw?._isSundayRow) {
            cellData.cell.styles.fillColor = SUNDAY_FILL;
          }

          if (cellData.section === 'body' && cellData.row.raw?._isPlaceholderRow) {
            cellData.cell.styles.textColor = PLACEHOLDER_TEXT;
          }

          if (cellData.section === 'body' && cellData.row.raw?._isLeaveRow) {
            cellData.cell.styles.textColor = LEAVE_TEXT;
            cellData.cell.styles.fontStyle = 'bold';
          }

          if (cellData.section === 'body' && cellData.column.dataKey === 'status') {
            cellData.cell.styles.textColor = cellData.row.raw?._isLeaveRow
              ? LEAVE_TEXT
              : this.getTicketStatusTextColor(cellData.row.raw?.status);
            cellData.cell.styles.fontStyle = 'bold';
          }

          if (
            cellData.section === 'body' &&
            cellData.column.dataKey === 'remarks' &&
            Array.isArray(cellData.row.raw?.remarks_items) &&
            cellData.row.raw.remarks_items.length
          ) {
            cellData.cell.styles.halign = 'left';
            cellData.cell.styles.valign = 'top';
            cellData.cell.styles.fontSize = 8;
            cellData.cell.text = [''];
            cellData.cell.styles.minCellHeight = this.getTicketRemarkCellHeight(
              doc,
              cellData.row.raw?.remarks_items,
              108
            );
          }
        },
        didDrawCell: (cellData: any) => {
          if (
            cellData.section === 'body' &&
            cellData.column.dataKey === 'remarks' &&
            Array.isArray(cellData.row.raw?.remarks_items) &&
            cellData.row.raw.remarks_items.length
          ) {
            this.drawTicketRemarks(doc, cellData.cell, cellData.row.raw?.remarks_items);
          }
        },
        didDrawPage: () => {
          const pages = doc.internal.getNumberOfPages();
          doc.setFontSize(7);
          doc.setTextColor(...TEXT_MUTED);
          doc.text(`Generated on : ${generatedOn}`, 10, pageHeight - 8);
          doc.text(String(pages), pageWidth / 2, pageHeight - 8, { align: 'center' });
        }
      });

      this.finalizePdf(doc, `OVERALL_TICKETS_REPORT_${rangeText}.pdf`, mode);
    } catch (error) {
      console.error("PDF Generation failed", error);
    }
  }

  private buildOverallTicketReportRows(rawData: any[], fromdate: any, todate: any): any[] {
    const source = Array.isArray(rawData) ? rawData : rawData ? [rawData] : [];
    const grouped: any = {};

    for (const ticket of source) {
      const dateKey = this.getTicketWorkDateKey(this.getOverallTicketDateValue(ticket));
      if (!dateKey) {
        continue;
      }

      if (!grouped[dateKey]) {
        grouped[dateKey] = [];
      }

      grouped[dateKey].push(this.mapOverallTicketReportRow(ticket));
    }

    const dateKeys = this.getTicketWorkReportDateKeys(fromdate, todate, Object.keys(grouped));
    const rows: any[] = [];

    for (const dateKey of dateKeys) {
      const day = this.getTicketWorkDayLabel(dateKey);
      const dateRows = grouped[dateKey] || [];

      if (!dateRows.length) {
        rows.push(this.createOverallTicketPlaceholderRow(dateKey, day));
        continue;
      }

      for (const row of dateRows) {
        rows.push({
          ...row,
          date: this.getTicketDateLabel(dateKey),
          day,
          _isSundayRow: day === 'SUN'
        });
      }
    }

    return rows.map((row: any, index: number) => ({
      ...row,
      sno: index + 1
    }));
  }

  private mapOverallTicketReportRow(ticket: any): any {
    const leaveText = this.formatTicketWorkStatusText(this.firstPresentPdfValue(
      ticket?.ticket_not_found,
      ticket?.ticketNotFound,
      ticket?.ticket_notfound,
      ticket?.not_found,
      ticket?.notFound
    ));
    const isLeaveRow = !!leaveText;
    const dateValue = this.getOverallTicketDateValue(ticket);

    return {
      sno: 0,
      date: this.getTicketDateLabel(dateValue),
      day: this.getTicketWorkDayLabel(dateValue),
      code: isLeaveRow ? '-' : this.cleanPdfText(this.firstPresentPdfValue(ticket?.code, ticket?.ticket_code, ticket?.ticketCode, ticket?.id, '-')),
      ticket_name: isLeaveRow ? leaveText : this.cleanPdfText(this.firstPresentPdfValue(ticket?.ticket_name, ticket?.ticketName, ticket?.ticket, ticket?.title, '-')),
      client: isLeaveRow ? '-' : this.cleanPdfText(this.firstPresentPdfValue(ticket?.company_name, ticket?.companyName, ticket?.customer_name, ticket?.customerName, ticket?.customer, '-')),
      product: isLeaveRow ? '-' : this.cleanPdfText(this.firstPresentPdfValue(ticket?.product_name, ticket?.productName, ticket?.product, '-')),
      department: isLeaveRow ? '-' : this.cleanPdfText(this.firstPresentPdfValue(ticket?.department_name, ticket?.departmentName, ticket?.dept_name, ticket?.deptName, '-')),
      assigned_from: isLeaveRow ? '-' : this.cleanPdfText(this.firstPresentPdfValue(ticket?.assigned_from_name, ticket?.assignedFromName, '-')),
      assigned_to: this.cleanPdfText(this.firstPresentPdfValue(ticket?.assigned_to_name, ticket?.assignedToName, ticket?.employee_name, ticket?.employeeName, '-')),
      remarks_items: isLeaveRow ? [] : this.getTicketRemarkItems(ticket),
      remarks: isLeaveRow ? leaveText : this.getTicketRemarks(ticket),
      worked_hours: isLeaveRow ? '-' : this.cleanPdfText(this.firstPresentPdfValue(ticket?.worked_hours, ticket?.workedHours, '-')),
      entry_date: isLeaveRow ? '-' : this.getTicketDateTimeLabel(this.firstPresentPdfValue(ticket?.created_date, ticket?.createdDate, ticket?.assigned_date, ticket?.assignedDate, dateValue)),
      status: isLeaveRow ? leaveText : this.getTicketStatusLabel(ticket?.status),
      _isLeaveRow: isLeaveRow,
      _isPlaceholderRow: false,
      _isSundayRow: this.getTicketWorkDayLabel(dateValue) === 'SUN'
    };
  }

  private createOverallTicketPlaceholderRow(dateKey: string, day: string): any {
    return {
      sno: 0,
      date: this.getTicketDateLabel(dateKey),
      day,
      code: '-',
      ticket_name: '-',
      client: '-',
      product: '-',
      department: '-',
      assigned_from: '-',
      assigned_to: '-',
      remarks_items: [],
      remarks: '-',
      worked_hours: '-',
      entry_date: '-',
      status: '-',
      _isPlaceholderRow: true,
      _isLeaveRow: false,
      _isSundayRow: day === 'SUN'
    };
  }

  private getOverallTicketDateValue(ticket: any): any {
    return this.firstPresentPdfValue(
      ticket?.date,
      ticket?.Date,
      ticket?.work_date,
      ticket?.workDate,
      ticket?.ticket_date,
      ticket?.ticketDate,
      ticket?.created_date,
      ticket?.createdDate,
      ticket?.assigned_date,
      ticket?.assignedDate,
      ticket?.updated_date,
      ticket?.updatedDate,
      ticket?.entry_date,
      ticket?.entryDate
    );
  }

  generateTicketWorkReportPDF(
    filters: any,
    fromdate: any,
    todate: any,
    rawData: any[],
    mode: 'download' | 'preview' = 'download'
  ) {
    try {
      const { jsPDF } = (window as any).jspdf;
      const doc = new jsPDF('l', 'mm', 'a3');

      const PRIMARY_BLUE = [0, 150, 232];
      const HEADER_DARK = [15, 23, 42];
      const TEXT_DARK = [0, 0, 0];
      const TEXT_MUTED = [71, 85, 105];
      const BORDER = [0, 0, 0];
      const SUNDAY_FILL = [241, 245, 249];

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const source = Array.isArray(rawData) ? rawData : rawData ? [rawData] : [];
      const employeeNames = this.getTicketWorkReportEmployees(source, filters);
      const data = this.buildTicketWorkReportRows(source, fromdate, todate, employeeNames);
      const rangeText = this.getInputDateRangeText(fromdate, todate);
      const generatedOn = this.getTicketGeneratedDateTime();
      const title = this.cleanPdfText(filters?.reportTitle || 'Ticket Work Report').toUpperCase();
      const department = this.cleanPdfText(filters?.department || 'All Departments');
      const selectedEmployee = this.cleanPdfText(filters?.selectedEmployee || 'All Employees');
      const generatedBy = this.cleanPdfText(filters?.generatedBy || 'SYSTEM USER');
      const employeeColumnWidth = Math.max(42, Math.min(82, (pageWidth - 18 - 46) / Math.max(employeeNames.length, 1)));

      doc.setTextColor(...HEADER_DARK);
      doc.setFont(undefined, 'bold');
      doc.setFontSize(15);
      doc.text(title, pageWidth / 2, 16, { align: 'center' });

      doc.setFontSize(8);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(...TEXT_DARK);
      doc.text(`Date Range : ${rangeText || '-'}`, 8, 28);
      doc.text(`Department : ${department}`, 8, 34);
      doc.text(`Employee : ${selectedEmployee}`, 8, 40);
      doc.text(`Generated By : ${generatedBy}`, pageWidth - 105, 28);
      doc.text(`Generated On : ${generatedOn}`, pageWidth - 105, 34);
      doc.text(`Total Days : ${data.length}`, pageWidth - 105, 40);

      doc.setDrawColor(...BORDER);
      doc.setLineWidth(0.3);
      doc.line(8, 46, pageWidth - 8, 46);

      const columns: any[] = [
        { header: 'S.No', dataKey: 'sno' },
        { header: 'Date', dataKey: 'date' },
        { header: 'Day', dataKey: 'day' },
        ...employeeNames.map((name: string, index: number) => ({
          header: this.cleanPdfText(name).toUpperCase(),
          dataKey: this.getTicketWorkEmployeeDataKey(index)
        }))
      ];

      const columnStyles: any = {
        sno: { cellWidth: 10, halign: 'center', valign: 'middle' },
        date: { cellWidth: 22, halign: 'center', valign: 'middle' },
        day: { cellWidth: 14, halign: 'center', valign: 'middle', fontStyle: 'bold' }
      };

      employeeNames.forEach((name: string, index: number) => {
        columnStyles[this.getTicketWorkEmployeeDataKey(index)] = {
          cellWidth: employeeColumnWidth,
          minCellWidth: 38,
          fontSize: 7.1,
          valign: 'top'
        };
      });

      (doc as any).autoTable({
        columns,
        body: data,
        startY: 52,
        theme: 'grid',
        margin: { left: 8, right: 8, bottom: 18 },
        showHead: 'everyPage',
        horizontalPageBreak: true,
        horizontalPageBreakRepeat: 'date',
        headStyles: {
          fillColor: PRIMARY_BLUE,
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center',
          valign: 'middle',
          fontSize: 8,
          cellPadding: { top: 2, bottom: 2, left: 1.2, right: 1.2 },
          lineColor: BORDER,
          lineWidth: 0.25
        },
        styles: {
          fontSize: 7.4,
          cellPadding: { top: 1.8, bottom: 1.8, left: 1.2, right: 1.2 },
          overflow: 'linebreak',
          textColor: TEXT_DARK,
          lineColor: BORDER,
          lineWidth: 0.18,
          halign: 'left',
          valign: 'top',
          minCellHeight: 9
        },
        alternateRowStyles: {
          fillColor: [248, 250, 252]
        },
        columnStyles,
        didParseCell: (cellData: any) => {
          const row = cellData.row.raw || {};

          if (cellData.section === 'body' && row.day === 'SUN') {
            cellData.cell.styles.fillColor = SUNDAY_FILL;
          }

          if (cellData.section === 'body' && cellData.column.dataKey === 'day' && row.day === 'SUN') {
            cellData.cell.styles.textColor = [220, 38, 38];
          }

          if (cellData.section === 'body' && String(cellData.column.dataKey || '').startsWith('employee_')) {
            const text = Array.isArray(cellData.cell.raw) ? cellData.cell.raw.join(' ') : String(cellData.cell.raw || '');
            if (text.trim().toLowerCase() === 'sunday') {
              cellData.cell.styles.halign = 'center';
              cellData.cell.styles.valign = 'middle';
              cellData.cell.styles.fontStyle = 'bold';
              cellData.cell.styles.textColor = [100, 116, 139];
            }
          }
        },
        didDrawPage: () => {
          const pages = doc.internal.getNumberOfPages();
          doc.setFontSize(7);
          doc.setTextColor(...TEXT_MUTED);
          doc.text(`Generated on : ${generatedOn}`, 10, pageHeight - 8);
          doc.text(String(pages), pageWidth / 2, pageHeight - 8, { align: 'center' });
        }
      });

      this.finalizePdf(doc, `TICKET_WORK_REPORT_${this.getSafePdfFilePart(rangeText)}.pdf`, mode);
    } catch (error) {
      console.error("Ticket work report PDF generation failed", error);
    }
  }

  private getTicketWorkReportEmployees(source: any[], filters: any): string[] {
    const selectedEmployee = this.cleanTicketWorkText(filters?.selectedEmployee);
    if (selectedEmployee) {
      return [selectedEmployee];
    }

    const names: string[] = [];

    for (const ticket of source) {
      this.addUniqueTicketWorkName(names, this.getTicketWorkEmployeeName(ticket));
    }

    if (!names.length) {
      for (const row of source) {
        for (const key of this.getTicketWorkMatrixKeys(row)) {
          this.addUniqueTicketWorkName(names, this.formatTicketWorkMatrixKey(key));
        }
      }
    }

    return names.length ? names : ['Employee'];
  }

  private buildTicketWorkReportRows(source: any[], fromdate: any, todate: any, employeeNames: string[]): any[] {
    const matrixRows = this.buildTicketWorkMatrixRows(source, employeeNames);
    if (matrixRows.length) {
      return matrixRows;
    }

    const grouped: any = {};

    for (const ticket of source) {
      const dateKey = this.getTicketWorkDateKey(this.getTicketWorkDateValue(ticket));
      if (!dateKey) {
        continue;
      }

      const employeeName = this.getTicketWorkEmployeeName(ticket) || employeeNames[0] || 'Employee';
      const employeeKey = this.normalizeTicketWorkKey(employeeName);
      const text = this.getTicketWorkReportText(ticket);

      if (!grouped[dateKey]) {
        grouped[dateKey] = {};
      }

      if (!grouped[dateKey][employeeKey]) {
        grouped[dateKey][employeeKey] = [];
      }

      if (text) {
        grouped[dateKey][employeeKey].push(text);
      }
    }

    const dateKeys = this.getTicketWorkReportDateKeys(fromdate, todate, Object.keys(grouped));

    return dateKeys.map((dateKey: string, index: number) => {
      const day = this.getTicketWorkDayLabel(dateKey);
      const row: any = {
        sno: index + 1,
        date: this.getTicketDateLabel(dateKey),
        day
      };

      employeeNames.forEach((employeeName: string, employeeIndex: number) => {
        const employeeKey = this.normalizeTicketWorkKey(employeeName);
        const entries = grouped[dateKey]?.[employeeKey] || [];
        row[this.getTicketWorkEmployeeDataKey(employeeIndex)] = entries.length
          ? entries.join('\n\n')
          : day === 'SUN' ? 'Sunday' : '';
      });

      return row;
    });
  }

  private buildTicketWorkMatrixRows(source: any[], employeeNames: string[]): any[] {
    const rows = source
      .filter((row: any) => row && typeof row === 'object' && this.getTicketWorkMatrixKeys(row).length)
      .map((row: any, index: number) => {
        const dateKey = this.getTicketWorkDateKey(this.getTicketWorkDateValue(row));
        const day = this.cleanTicketWorkText(row?.day || row?.Day) || this.getTicketWorkDayLabel(dateKey);
        const reportRow: any = {
          _dateKey: dateKey,
          sno: this.firstPresentPdfValue(row?.sno, row?.SNo, row?.['S.No'], row?.s_no, row?.serial_no, row?.serialNo, index + 1),
          date: this.getTicketDateLabel(dateKey),
          day
        };

        employeeNames.forEach((employeeName: string, employeeIndex: number) => {
          const matrixKey = this.findTicketWorkMatrixKey(row, employeeName);
          reportRow[this.getTicketWorkEmployeeDataKey(employeeIndex)] = matrixKey
            ? this.cleanTicketWorkText(row[matrixKey])
            : '';
        });

        return reportRow;
      })
      .filter((row: any) => row._dateKey);

    return rows
      .sort((first: any, second: any) => String(first._dateKey).localeCompare(String(second._dateKey)))
      .map((row: any, index: number) => {
        const { _dateKey, ...cleanRow } = row;
        return { ...cleanRow, sno: cleanRow.sno || index + 1 };
      });
  }

  private getTicketWorkReportDateKeys(fromdate: any, todate: any, dataDateKeys: string[]): string[] {
    const start = this.parseTicketWorkDate(fromdate);
    const end = this.parseTicketWorkDate(todate);

    if (start && end && start.getTime() <= end.getTime()) {
      const keys: string[] = [];
      const cursor = new Date(start.getFullYear(), start.getMonth(), start.getDate());

      while (cursor.getTime() <= end.getTime() && keys.length < 1500) {
        keys.push(this.formatTicketWorkDateKey(cursor));
        cursor.setDate(cursor.getDate() + 1);
      }

      if (keys.length) {
        return keys;
      }
    }

    return [...new Set(dataDateKeys.filter(Boolean))].sort((first: string, second: string) => first.localeCompare(second));
  }

  private getTicketWorkReportText(ticket: any): string {
    if (typeof ticket === 'string') {
      return this.cleanTicketWorkText(ticket);
    }

    const code = this.cleanTicketWorkText(this.firstPresentPdfValue(ticket?.code, ticket?.ticket_code, ticket?.ticketCode, ticket?.id));
    const title = this.cleanTicketWorkText(this.firstPresentPdfValue(ticket?.ticket_name, ticket?.ticketName, ticket?.ticket, ticket?.title, ticket?.type, ticket?.ticket_type));
    const ticketNotFound = this.formatTicketWorkStatusText(this.firstPresentPdfValue(
      ticket?.ticket_not_found,
      ticket?.ticketNotFound,
      ticket?.ticket_notfound,
      ticket?.not_found,
      ticket?.notFound
    ));
    const solution = this.cleanTicketWorkText(this.firstPresentPdfValue(
      ticket?.solution,
      ticket?.ticket_details,
      ticket?.ticketDetails,
      ticket?.work_report,
      ticket?.workReport,
      ticket?.work_details,
      ticket?.workDetails,
      ticket?.work,
      ticket?.details,
      ticket?.description,
      ticket?.purpose,
      ticket?.reason_f_issue,
      ticket?.reasonFIssue,
      ticket?.reason_for_issue,
      ticket?.comments,
      ticket?.remarks
    ));
    const summary = [code, title].filter(Boolean).join(' - ');
    const parts = [];

    if (!summary && !solution && ticketNotFound) {
      return ticketNotFound;
    }

    if (summary) {
      parts.push(summary);
    }

    if (solution) {
      parts.push(`solution - ${solution}`);
    }

    return parts.join('\n');
  }

  private getTicketWorkEmployeeName(ticket: any): string {
    return this.cleanTicketWorkText(this.firstPresentPdfValue(
      ticket?.assigned_to_name,
      ticket?.assignedToName,
      ticket?.employee_name,
      ticket?.employeeName,
      ticket?.emp_name,
      ticket?.empName,
      ticket?.name,
      ticket?.username
    ));
  }

  private getTicketWorkDateValue(ticket: any): any {
    return this.firstPresentPdfValue(
      ticket?.date,
      ticket?.Date,
      ticket?.work_date,
      ticket?.workDate,
      ticket?.ticket_date,
      ticket?.ticketDate,
      ticket?.created_date,
      ticket?.createdDate,
      ticket?.assigned_date,
      ticket?.assignedDate,
      ticket?.updated_date,
      ticket?.updatedDate,
      ticket?.entry_date,
      ticket?.entryDate
    );
  }

  private getTicketWorkMatrixKeys(row: any): string[] {
    if (!row || typeof row !== 'object' || Array.isArray(row)) {
      return [];
    }

    const reservedKeys = new Set([
      'sno', 'sno', 'serial', 'serialno', 'serialnumber', 'date', 'workdate', 'ticketdate', 'createddate',
      'assigneddate', 'updateddate', 'entrydate', 'day', 'id', 'ticketid', 'code', 'ticketcode', 'ticket',
      'ticketname', 'title', 'customer', 'client', 'companyname', 'companyid', 'product', 'productname',
      'productid', 'version', 'type', 'tickettype', 'assignedfrom', 'assignedfromname', 'assignedto',
      'assignedtoname', 'department', 'departmentname', 'departmentid', 'deptid', 'priority', 'status',
      'statustext', 'description', 'solution', 'reasonfissue', 'reasonforissue', 'comments', 'remarks',
      'clientcomments', 'workedhours', 'employeename', 'empname', 'username', 'employeeid', 'empid',
      'userid', 'createdby', 'updatedby', 'ticketnotfound', 'notfound', 'workreport', 'workdetails',
      'details', 'purpose'
    ]);

    return Object.keys(row).filter((key: string) => {
      const normalizedKey = this.normalizeTicketWorkKey(key);
      if (!normalizedKey || reservedKeys.has(normalizedKey)) {
        return false;
      }

      const isLowerSnakeField = key.includes('_') && key === key.toLowerCase();
      return !isLowerSnakeField;
    });
  }

  private findTicketWorkMatrixKey(row: any, employeeName: string): string {
    const targetKey = this.normalizeTicketWorkKey(employeeName);
    return this.getTicketWorkMatrixKeys(row).find((key: string) => this.normalizeTicketWorkKey(key) === targetKey) || '';
  }

  private formatTicketWorkMatrixKey(key: string): string {
    return this.cleanTicketWorkText(key).replace(/[_-]+/g, ' ');
  }

  private addUniqueTicketWorkName(names: string[], name: string): void {
    const cleanName = this.cleanTicketWorkText(name);
    if (!cleanName) {
      return;
    }

    const key = this.normalizeTicketWorkKey(cleanName);
    if (!names.some((existing: string) => this.normalizeTicketWorkKey(existing) === key)) {
      names.push(cleanName);
    }
  }

  private getTicketWorkDateKey(value: any): string {
    const date = this.parseTicketWorkDate(value);
    return date ? this.formatTicketWorkDateKey(date) : '';
  }

  private parseTicketWorkDate(value: any): Date | null {
    if (this.isEmptyPdfValue(value)) {
      return null;
    }

    if (typeof value === 'number' && value > 20000 && value < 60000) {
      const excelDate = new Date(Date.UTC(1899, 11, 30));
      excelDate.setUTCDate(excelDate.getUTCDate() + Math.floor(value));
      return new Date(excelDate.getUTCFullYear(), excelDate.getUTCMonth(), excelDate.getUTCDate());
    }

    const text = String(value).trim();
    const ymdMatch = /^(\d{4})[-/](\d{1,2})[-/](\d{1,2})/.exec(text);
    if (ymdMatch) {
      return new Date(Number(ymdMatch[1]), Number(ymdMatch[2]) - 1, Number(ymdMatch[3]));
    }

    const dmyMatch = /^(\d{1,2})[-/](\d{1,2})[-/](\d{4})/.exec(text);
    if (dmyMatch) {
      return new Date(Number(dmyMatch[3]), Number(dmyMatch[2]) - 1, Number(dmyMatch[1]));
    }

    const date = new Date(value);
    if (Number.isNaN(date.getTime())) {
      return null;
    }

    return new Date(date.getFullYear(), date.getMonth(), date.getDate());
  }

  private formatTicketWorkDateKey(date: Date): string {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
  }

  private getTicketWorkDayLabel(value: any): string {
    const date = this.parseTicketWorkDate(value);
    if (!date) {
      return '-';
    }

    return ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'][date.getDay()];
  }

  private getTicketWorkEmployeeDataKey(index: number): string {
    return `employee_${index}`;
  }

  private normalizeTicketWorkKey(value: any): string {
    return String(value ?? '').trim().toLowerCase().replace(/[^a-z0-9]+/g, '');
  }

  private cleanTicketWorkText(value: any): string {
    if (this.isEmptyPdfValue(value)) {
      return '';
    }

    return String(value)
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/<[^>]*>/g, ' ')
      .replace(/\r\n/g, '\n')
      .replace(/\r/g, '\n')
      .replace(/[ \t]+/g, ' ')
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  }

  private formatTicketWorkStatusText(value: any): string {
    const text = this.cleanTicketWorkText(value);
    if (!text) {
      return '';
    }

    return text.length <= 24
      ? text.replace(/\b\w/g, (letter: string) => letter.toUpperCase())
      : text;
  }

  private firstPresentPdfValue(...values: any[]): any {
    return values.find((value: any) => !this.isEmptyPdfValue(value)) ?? null;
  }

  private getSafePdfFilePart(value: any): string {
    const cleanValue = this.cleanPdfText(value).replace(/[^a-zA-Z0-9_-]+/g, '_').replace(/^_+|_+$/g, '');
    return cleanValue || 'REPORT';
  }

  private getTicketRemarkItems(ticket: any): any[] {
    return [
      { label: 'Description', value: ticket?.description },
      { label: 'Solution', value: ticket?.solution },
      { label: 'Reason For Issue', value: ticket?.reason_f_issue || ticket?.reasonFIssue || ticket?.reason_for_issue }
    ]
      .filter((item: any) => !this.isEmptyPdfValue(item.value))
      .map((item: any) => ({
        label: item.label,
        value: this.cleanPdfText(item.value)
      }));
  }

  private getTicketRemarks(ticket: any): string {
    const remarks = this.getTicketRemarkItems(ticket)
      .map((item: any) => `${item.label} : ${item.value}`);

    return remarks.length ? remarks.join('\n') : '-';
  }

  private drawTicketRemarks(doc: any, cell: any, remarks: any[]): void {
    const fontSize = 8;
    const lineHeight = 4.2;
    const leftPadding = 1.4;
    const topPadding = 2.2;
    const maxWidth = Math.max(cell.width - (leftPadding * 2), 10);
    let y = cell.y + topPadding + 2.8;

    doc.setFontSize(fontSize);
    doc.setTextColor(0, 0, 0);

    if (!Array.isArray(remarks) || !remarks.length) {
      doc.setFont(undefined, 'normal');
      doc.text('-', cell.x + leftPadding, y);
      return;
    }

    for (const remark of remarks) {
      const label = `${remark.label} : `;
      const labelWidth = doc.getTextWidth(label);
      const valueLines = this.wrapTicketRemarkValue(
        doc,
        remark.value,
        Math.max(maxWidth - labelWidth, 18),
        maxWidth
      );

      doc.setFont(undefined, 'bold');
      doc.text(label, cell.x + leftPadding, y);

      doc.setFont(undefined, 'normal');
      doc.text(valueLines[0] || '-', cell.x + leftPadding + labelWidth, y);

      for (const line of valueLines.slice(1)) {
        y += lineHeight;
        doc.text(line, cell.x + leftPadding, y);
      }

      y += lineHeight + 0.8;
    }

    doc.setFont(undefined, 'normal');
  }

  private getTicketRemarkCellHeight(doc: any, remarks: any[], cellWidth: number): number {
    const fontSize = 8;
    const lineHeight = 4.2;
    const verticalPadding = 4.4;
    const maxWidth = Math.max(cellWidth - 2.8, 10);

    if (!Array.isArray(remarks) || !remarks.length) {
      return 11;
    }

    doc.setFontSize(fontSize);

    const contentHeight = remarks.reduce((height: number, remark: any) => {
      const label = `${remark.label} : `;
      const labelWidth = doc.getTextWidth(label);
      const valueLines = this.wrapTicketRemarkValue(
        doc,
        remark.value,
        Math.max(maxWidth - labelWidth, 18),
        maxWidth
      );

      return height + (Math.max(valueLines.length, 1) * lineHeight) + 0.8;
    }, 0);

    return Math.max(11, contentHeight + verticalPadding);
  }

  private wrapTicketRemarkValue(doc: any, value: any, firstLineWidth: number, nextLineWidth: number): string[] {
    const text = this.cleanPdfText(value);
    if (text === '-') {
      return ['-'];
    }

    const words = text.split(/\s+/).filter(Boolean);
    const lines: string[] = [];
    let currentLine = '';
    let activeWidth = firstLineWidth;

    for (const word of words) {
      const candidate = currentLine ? `${currentLine} ${word}` : word;
      if (doc.getTextWidth(candidate) <= activeWidth) {
        currentLine = candidate;
        continue;
      }

      if (currentLine) {
        lines.push(currentLine);
      }

      if (doc.getTextWidth(word) > nextLineWidth) {
        const splitWordLines = doc.splitTextToSize(word, nextLineWidth);
        lines.push(...splitWordLines.slice(0, -1));
        currentLine = splitWordLines[splitWordLines.length - 1] || '';
      } else {
        currentLine = word;
      }

      activeWidth = nextLineWidth;
    }

    if (currentLine) {
      lines.push(currentLine);
    }

    return lines.length ? lines : ['-'];
  }

  private cleanPdfText(value: any): string {
    if (this.isEmptyPdfValue(value)) {
      return '-';
    }

    return String(value)
      .replace(/<[^>]*>/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
  }

  private isEmptyPdfValue(value: any): boolean {
    if (value === null || value === undefined) {
      return true;
    }

    const normalized = String(value).trim();
    return normalized === '' || normalized.toLowerCase() === 'null' || normalized.toLowerCase() === 'undefined';
  }

  private getTicketDateLabel(value: any): string {
    const date = new Date(value);
    if (!value || Number.isNaN(date.getTime())) {
      return '-';
    }

    return `${String(date.getDate()).padStart(2, '0')}-${String(date.getMonth() + 1).padStart(2, '0')}-${date.getFullYear()}`;
  }

  private getTicketDateTimeLabel(value: any): string {
    const date = new Date(value);
    if (!value || Number.isNaN(date.getTime())) {
      return '-';
    }

    const datePart = this.getTicketDateLabel(value);
    const timePart = `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}:${String(date.getSeconds()).padStart(2, '0')}`;
    return `${datePart} ${timePart}`;
  }

  private getTicketGeneratedDateTime(): string {
    const now = new Date();
    return `${this.getTicketDateLabel(now)} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}:${String(now.getSeconds()).padStart(2, '0')}`;
  }

  private getTicketStatusTextColor(status: any): number[] {
    const label = this.getTicketStatusLabel(status).toLowerCase();
    if (label === 'in-progress') return [37, 99, 235];
    if (label === 'to-be-tested') return [245, 158, 11];
    if (label === 'delayed') return [124, 58, 237];
    if (label === 'closed') return [71, 85, 105];
    if (label === 'approved' || label === 'completed' || label === 'passed') return [0, 128, 0];
    if (label === 'cancelled' || label === 'rejected' || label === 'failed') return [220, 38, 38];
    return [0, 0, 0];
  }

  private getTicketStatusLabel(status: any): string {
    const map: any = {
      0: 'Open',
      1: 'In-Progress',
      2: 'To-be-Tested',
      3: 'Delayed',
      4: 'Closed',
      5: 'Cancelled',
      6: 'Approved',
      7: 'Completed',
      8: 'Rejected',
      9: 'Failed',
      10: 'Passed'
    };

    const numericStatus = Number(status);
    if (!Number.isNaN(numericStatus) && map[numericStatus]) {
      return map[numericStatus];
    }

    const rawStatus = String(status ?? '').trim();
    if (!rawStatus) {
      return '-';
    }

    const normalized = rawStatus.toLowerCase().replace(/[_\s]+/g, '-');
    const textMap: any = {
      'open': 'Open',
      'in-progress': 'In-Progress',
      'to-be-tested': 'To-be-Tested',
      'delayed': 'Delayed',
      'closed': 'Closed',
      'cancelled': 'Cancelled',
      'approved': 'Approved',
      'completed': 'Completed',
      'rejected': 'Rejected',
      'failed': 'Failed',
      'passed': 'Passed'
    };

    return textMap[normalized] || rawStatus;
  }
}
